/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;

/**
 *
 * @author emiliano
 */
public class BaseCondcNote extends BaseTableBean{
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.descr
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String descr;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.descr_de
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String descr_de;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.descr_en
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String descr_en;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.descr_es
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String descr_es;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.descr_fr
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String descr_fr;
    
    protected String descr_ru;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.nota
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String nota;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.nota_de
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String nota_de;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.nota_en
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String nota_en;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.nota_es
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String nota_es;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.nota_fr
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String nota_fr;
    
    
    protected String nota_ru;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.archrubrica_condc_note.nrposi
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected Integer nrposi;
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.archrubrica_condc_note.tpnota
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    protected String tpnota;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.descr
     *
     * @return the value of pgmr.vist_condc_grpatti_note.descr
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.descr_de
     *
     * @return the value of pgmr.vist_condc_grpatti_note.descr_de
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getDescr_de() {
        return descr_de;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.descr_en
     *
     * @return the value of pgmr.vist_condc_grpatti_note.descr_en
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getDescr_en() {
        return descr_en;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.descr_es
     *
     * @return the value of pgmr.vist_condc_grpatti_note.descr_es
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getDescr_es() {
        return descr_es;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.descr_fr
     *
     * @return the value of pgmr.vist_condc_grpatti_note.descr_fr
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getDescr_fr() {
        return descr_fr;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.nota
     *
     * @return the value of pgmr.vist_condc_grpatti_note.nota
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getNota() {
        return nota;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.nota_de
     *
     * @return the value of pgmr.vist_condc_grpatti_note.nota_de
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getNota_de() {
        return nota_de;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.nota_en
     *
     * @return the value of pgmr.vist_condc_grpatti_note.nota_en
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getNota_en() {
        return nota_en;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.nota_es
     *
     * @return the value of pgmr.vist_condc_grpatti_note.nota_es
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getNota_es() {
        return nota_es;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.nota_fr
     *
     * @return the value of pgmr.vist_condc_grpatti_note.nota_fr
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getNota_fr() {
        return nota_fr;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.descr
     *
     * @param descr the value for pgmr.vist_condc_grpatti_note.descr
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.descr_de
     *
     * @param descr_de the value for pgmr.vist_condc_grpatti_note.descr_de
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setDescr_de(String descr_de) {
        this.descr_de = descr_de == null ? null : descr_de.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.descr_en
     *
     * @param descr_en the value for pgmr.vist_condc_grpatti_note.descr_en
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setDescr_en(String descr_en) {
        this.descr_en = descr_en == null ? null : descr_en.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.descr_es
     *
     * @param descr_es the value for pgmr.vist_condc_grpatti_note.descr_es
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setDescr_es(String descr_es) {
        this.descr_es = descr_es == null ? null : descr_es.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.descr_fr
     *
     * @param descr_fr the value for pgmr.vist_condc_grpatti_note.descr_fr
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setDescr_fr(String descr_fr) {
        this.descr_fr = descr_fr == null ? null : descr_fr.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.nota
     *
     * @param nota the value for pgmr.vist_condc_grpatti_note.nota
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setNota(String nota) {
        this.nota = nota == null ? null : nota.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.nota_de
     *
     * @param nota_de the value for pgmr.vist_condc_grpatti_note.nota_de
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setNota_de(String nota_de) {
        this.nota_de = nota_de == null ? null : nota_de.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.nota_en
     *
     * @param nota_en the value for pgmr.vist_condc_grpatti_note.nota_en
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setNota_en(String nota_en) {
        this.nota_en = nota_en == null ? null : nota_en.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.nota_es
     *
     * @param nota_es the value for pgmr.vist_condc_grpatti_note.nota_es
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setNota_es(String nota_es) {
        this.nota_es = nota_es == null ? null : nota_es.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.nota_fr
     *
     * @param nota_fr the value for pgmr.vist_condc_grpatti_note.nota_fr
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setNota_fr(String nota_fr) {
        this.nota_fr = nota_fr == null ? null : nota_fr.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.archrubrica_condc_note.nrposi
     *
     * @return the value of pgmr.archrubrica_condc_note.nrposi
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public Integer getNrposi() {
        return nrposi;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.archrubrica_condc_note.tpnota
     *
     * @return the value of pgmr.archrubrica_condc_note.tpnota
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public String getTpnota() {
        return tpnota;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.archrubrica_condc_note.nrposi
     *
     * @param nrposi the value for pgmr.archrubrica_condc_note.nrposi
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setNrposi(Integer nrposi) {
        this.nrposi = nrposi;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.archrubrica_condc_note.tpnota
     *
     * @param tpnota the value for pgmr.archrubrica_condc_note.tpnota
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void setTpnota(String tpnota) {
        this.tpnota = tpnota == null ? null : tpnota.trim();
    }

    public String getDescr_ru() {
        return descr_ru;
    }

    public void setDescr_ru(String descr_ru) {
        this.descr_ru = descr_ru == null ? null : descr_ru.trim();
    }

    public String getNota_ru() {
        return nota_ru;
    }

    public void setNota_ru(String nota_ru) {
        this.nota_ru = nota_ru == null ? null : nota_ru.trim();
    }
    
    
}
