package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;
import java.util.Date;

public class Ep_log extends BaseTableBean {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.tkeplog
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Long tkeplog;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.tkeplog_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Long tkeplog_tipo;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.anno
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Short anno;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.mese
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Short mese;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.dtlog
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Date dtlog;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.jsp_name
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private String jsp_name;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.tkutente
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Long tkutente;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.dtlogin
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Date dtlogin;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.tkfatt
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Long tkfatt;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.dtdown_fatt
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Date dtdown_fatt;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.applicazione
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private String applicazione;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.dtaccesso
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Date dtaccesso;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.giorno
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Short giorno;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.ora
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Short ora;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.session_id
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private String session_id;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.tkcontatto
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private Long tkcontatto;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_log.file_name
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private String file_name;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.tkeplog
     *
     * @return the value of pgmr.ep_log.tkeplog
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Long getTkeplog() {
        return tkeplog;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.tkeplog
     *
     * @param tkeplog the value for pgmr.ep_log.tkeplog
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setTkeplog(Long tkeplog) {
        this.tkeplog = tkeplog;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.tkeplog_tipo
     *
     * @return the value of pgmr.ep_log.tkeplog_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Long getTkeplog_tipo() {
        return tkeplog_tipo;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.tkeplog_tipo
     *
     * @param tkeplog_tipo the value for pgmr.ep_log.tkeplog_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setTkeplog_tipo(Long tkeplog_tipo) {
        this.tkeplog_tipo = tkeplog_tipo;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.anno
     *
     * @return the value of pgmr.ep_log.anno
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Short getAnno() {
        return anno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.anno
     *
     * @param anno the value for pgmr.ep_log.anno
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setAnno(Short anno) {
        this.anno = anno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.mese
     *
     * @return the value of pgmr.ep_log.mese
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Short getMese() {
        return mese;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.mese
     *
     * @param mese the value for pgmr.ep_log.mese
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setMese(Short mese) {
        this.mese = mese;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.dtlog
     *
     * @return the value of pgmr.ep_log.dtlog
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Date getDtlog() {
        return dtlog;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.dtlog
     *
     * @param dtlog the value for pgmr.ep_log.dtlog
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setDtlog(Date dtlog) {
        this.dtlog = dtlog;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.jsp_name
     *
     * @return the value of pgmr.ep_log.jsp_name
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public String getJsp_name() {
        return jsp_name;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.jsp_name
     *
     * @param jsp_name the value for pgmr.ep_log.jsp_name
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setJsp_name(String jsp_name) {
        this.jsp_name = jsp_name == null ? null : jsp_name.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.tkutente
     *
     * @return the value of pgmr.ep_log.tkutente
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Long getTkutente() {
        return tkutente;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.tkutente
     *
     * @param tkutente the value for pgmr.ep_log.tkutente
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setTkutente(Long tkutente) {
        this.tkutente = tkutente;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.dtlogin
     *
     * @return the value of pgmr.ep_log.dtlogin
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Date getDtlogin() {
        return dtlogin;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.dtlogin
     *
     * @param dtlogin the value for pgmr.ep_log.dtlogin
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setDtlogin(Date dtlogin) {
        this.dtlogin = dtlogin;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.tkfatt
     *
     * @return the value of pgmr.ep_log.tkfatt
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Long getTkfatt() {
        return tkfatt;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.tkfatt
     *
     * @param tkfatt the value for pgmr.ep_log.tkfatt
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setTkfatt(Long tkfatt) {
        this.tkfatt = tkfatt;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.dtdown_fatt
     *
     * @return the value of pgmr.ep_log.dtdown_fatt
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Date getDtdown_fatt() {
        return dtdown_fatt;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.dtdown_fatt
     *
     * @param dtdown_fatt the value for pgmr.ep_log.dtdown_fatt
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setDtdown_fatt(Date dtdown_fatt) {
        this.dtdown_fatt = dtdown_fatt;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.applicazione
     *
     * @return the value of pgmr.ep_log.applicazione
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public String getApplicazione() {
        return applicazione;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.applicazione
     *
     * @param applicazione the value for pgmr.ep_log.applicazione
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setApplicazione(String applicazione) {
        this.applicazione = applicazione == null ? null : applicazione.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.dtaccesso
     *
     * @return the value of pgmr.ep_log.dtaccesso
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Date getDtaccesso() {
        return dtaccesso;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.dtaccesso
     *
     * @param dtaccesso the value for pgmr.ep_log.dtaccesso
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setDtaccesso(Date dtaccesso) {
        this.dtaccesso = dtaccesso;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.giorno
     *
     * @return the value of pgmr.ep_log.giorno
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Short getGiorno() {
        return giorno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.giorno
     *
     * @param giorno the value for pgmr.ep_log.giorno
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setGiorno(Short giorno) {
        this.giorno = giorno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.ora
     *
     * @return the value of pgmr.ep_log.ora
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Short getOra() {
        return ora;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.ora
     *
     * @param ora the value for pgmr.ep_log.ora
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setOra(Short ora) {
        this.ora = ora;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.session_id
     *
     * @return the value of pgmr.ep_log.session_id
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public String getSession_id() {
        return session_id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.session_id
     *
     * @param session_id the value for pgmr.ep_log.session_id
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setSession_id(String session_id) {
        this.session_id = session_id == null ? null : session_id.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.tkcontatto
     *
     * @return the value of pgmr.ep_log.tkcontatto
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Long getTkcontatto() {
        return tkcontatto;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.tkcontatto
     *
     * @param tkcontatto the value for pgmr.ep_log.tkcontatto
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setTkcontatto(Long tkcontatto) {
        this.tkcontatto = tkcontatto;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_log.file_name
     *
     * @return the value of pgmr.ep_log.file_name
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public String getFile_name() {
        return file_name;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_log.file_name
     *
     * @param file_name the value for pgmr.ep_log.file_name
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void setFile_name(String file_name) {
        this.file_name = file_name == null ? null : file_name.trim();
    }
}