package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;
import java.util.Date;

public class Ep_posts extends BaseTableBean {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.tkpost
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private Long tkpost;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_content
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String postContent;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_title
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String postTitle;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_category
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private Long postCategory;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_excerpt
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String postExcerpt;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_status
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String postStatus;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_parent
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private Long postParent;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.urlpath
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String urlpath;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_type
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String postType;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_mime_type
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String postMimeType;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.cdgptipm
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String cdgptipm;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_title_en
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String postTitleEn;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_content_en
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String postContentEn;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_date
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private Date postDate;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.fgpubblico
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String fgpubblico;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.cdvistfam
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String cdvistfam;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.cdvisttp
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String cdvisttp;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_dtinev
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private Date postDtinev;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_dtfiev
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private Date postDtfiev;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.meta_description_it
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String metaDescriptionIt;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.meta_description_en
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private String metaDescriptionEn;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.ep_posts.post_dtripubb
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    private Date postDtripubb;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.tkpost
     *
     * @return the value of pgmr.ep_posts.tkpost
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public Long getTkpost() {
        return tkpost;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.tkpost
     *
     * @param tkpost the value for pgmr.ep_posts.tkpost
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setTkpost(Long tkpost) {
        this.tkpost = tkpost;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_content
     *
     * @return the value of pgmr.ep_posts.post_content
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getPostContent() {
        return postContent;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_content
     *
     * @param postContent the value for pgmr.ep_posts.post_content
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostContent(String postContent) {
        this.postContent = postContent == null ? null : postContent.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_title
     *
     * @return the value of pgmr.ep_posts.post_title
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getPostTitle() {
        return postTitle;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_title
     *
     * @param postTitle the value for pgmr.ep_posts.post_title
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostTitle(String postTitle) {
        this.postTitle = postTitle == null ? null : postTitle.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_category
     *
     * @return the value of pgmr.ep_posts.post_category
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public Long getPostCategory() {
        return postCategory;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_category
     *
     * @param postCategory the value for pgmr.ep_posts.post_category
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostCategory(Long postCategory) {
        this.postCategory = postCategory;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_excerpt
     *
     * @return the value of pgmr.ep_posts.post_excerpt
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getPostExcerpt() {
        return postExcerpt;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_excerpt
     *
     * @param postExcerpt the value for pgmr.ep_posts.post_excerpt
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostExcerpt(String postExcerpt) {
        this.postExcerpt = postExcerpt == null ? null : postExcerpt.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_status
     *
     * @return the value of pgmr.ep_posts.post_status
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getPostStatus() {
        return postStatus;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_status
     *
     * @param postStatus the value for pgmr.ep_posts.post_status
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostStatus(String postStatus) {
        this.postStatus = postStatus == null ? null : postStatus.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_parent
     *
     * @return the value of pgmr.ep_posts.post_parent
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public Long getPostParent() {
        return postParent;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_parent
     *
     * @param postParent the value for pgmr.ep_posts.post_parent
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostParent(Long postParent) {
        this.postParent = postParent;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.urlpath
     *
     * @return the value of pgmr.ep_posts.urlpath
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getUrlpath() {
        return urlpath;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.urlpath
     *
     * @param urlpath the value for pgmr.ep_posts.urlpath
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setUrlpath(String urlpath) {
        this.urlpath = urlpath == null ? null : urlpath.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_type
     *
     * @return the value of pgmr.ep_posts.post_type
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getPostType() {
        return postType;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_type
     *
     * @param postType the value for pgmr.ep_posts.post_type
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostType(String postType) {
        this.postType = postType == null ? null : postType.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_mime_type
     *
     * @return the value of pgmr.ep_posts.post_mime_type
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getPostMimeType() {
        return postMimeType;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_mime_type
     *
     * @param postMimeType the value for pgmr.ep_posts.post_mime_type
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostMimeType(String postMimeType) {
        this.postMimeType = postMimeType == null ? null : postMimeType.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.cdgptipm
     *
     * @return the value of pgmr.ep_posts.cdgptipm
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getCdgptipm() {
        return cdgptipm;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.cdgptipm
     *
     * @param cdgptipm the value for pgmr.ep_posts.cdgptipm
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setCdgptipm(String cdgptipm) {
        this.cdgptipm = cdgptipm == null ? null : cdgptipm.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_title_en
     *
     * @return the value of pgmr.ep_posts.post_title_en
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getPostTitleEn() {
        return postTitleEn;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_title_en
     *
     * @param postTitleEn the value for pgmr.ep_posts.post_title_en
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostTitleEn(String postTitleEn) {
        this.postTitleEn = postTitleEn == null ? null : postTitleEn.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_content_en
     *
     * @return the value of pgmr.ep_posts.post_content_en
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getPostContentEn() {
        return postContentEn;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_content_en
     *
     * @param postContentEn the value for pgmr.ep_posts.post_content_en
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostContentEn(String postContentEn) {
        this.postContentEn = postContentEn == null ? null : postContentEn.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_date
     *
     * @return the value of pgmr.ep_posts.post_date
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public Date getPostDate() {
        return postDate;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_date
     *
     * @param postDate the value for pgmr.ep_posts.post_date
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.fgpubblico
     *
     * @return the value of pgmr.ep_posts.fgpubblico
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getFgpubblico() {
        return fgpubblico;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.fgpubblico
     *
     * @param fgpubblico the value for pgmr.ep_posts.fgpubblico
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setFgpubblico(String fgpubblico) {
        this.fgpubblico = fgpubblico == null ? null : fgpubblico.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.cdvistfam
     *
     * @return the value of pgmr.ep_posts.cdvistfam
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getCdvistfam() {
        return cdvistfam;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.cdvistfam
     *
     * @param cdvistfam the value for pgmr.ep_posts.cdvistfam
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setCdvistfam(String cdvistfam) {
        this.cdvistfam = cdvistfam == null ? null : cdvistfam.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.cdvisttp
     *
     * @return the value of pgmr.ep_posts.cdvisttp
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getCdvisttp() {
        return cdvisttp;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.cdvisttp
     *
     * @param cdvisttp the value for pgmr.ep_posts.cdvisttp
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setCdvisttp(String cdvisttp) {
        this.cdvisttp = cdvisttp == null ? null : cdvisttp.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_dtinev
     *
     * @return the value of pgmr.ep_posts.post_dtinev
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public Date getPostDtinev() {
        return postDtinev;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_dtinev
     *
     * @param postDtinev the value for pgmr.ep_posts.post_dtinev
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostDtinev(Date postDtinev) {
        this.postDtinev = postDtinev;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_dtfiev
     *
     * @return the value of pgmr.ep_posts.post_dtfiev
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public Date getPostDtfiev() {
        return postDtfiev;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_dtfiev
     *
     * @param postDtfiev the value for pgmr.ep_posts.post_dtfiev
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostDtfiev(Date postDtfiev) {
        this.postDtfiev = postDtfiev;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.meta_description_it
     *
     * @return the value of pgmr.ep_posts.meta_description_it
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getMetaDescriptionIt() {
        return metaDescriptionIt;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.meta_description_it
     *
     * @param metaDescriptionIt the value for pgmr.ep_posts.meta_description_it
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setMetaDescriptionIt(String metaDescriptionIt) {
        this.metaDescriptionIt = metaDescriptionIt == null ? null : metaDescriptionIt.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.meta_description_en
     *
     * @return the value of pgmr.ep_posts.meta_description_en
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public String getMetaDescriptionEn() {
        return metaDescriptionEn;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.meta_description_en
     *
     * @param metaDescriptionEn the value for pgmr.ep_posts.meta_description_en
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setMetaDescriptionEn(String metaDescriptionEn) {
        this.metaDescriptionEn = metaDescriptionEn == null ? null : metaDescriptionEn.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.ep_posts.post_dtripubb
     *
     * @return the value of pgmr.ep_posts.post_dtripubb
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public Date getPostDtripubb() {
        return postDtripubb;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.ep_posts.post_dtripubb
     *
     * @param postDtripubb the value for pgmr.ep_posts.post_dtripubb
     *
     * @ibatorgenerated Mon Dec 23 14:59:53 CET 2013
     */
    public void setPostDtripubb(Date postDtripubb) {
        this.postDtripubb = postDtripubb;
    }
}