package com.ateikon.internet.eprogen.domain.pgmr;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Ep_utenteExample {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    public Ep_utenteExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    protected Ep_utenteExample(Ep_utenteExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Tue Jul 05 15:26:25 CEST 2011
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andTkutenteIsNull() {
            addCriterion("tkutente is null");
            return this;
        }

        public Criteria andTkutenteIsNotNull() {
            addCriterion("tkutente is not null");
            return this;
        }

        public Criteria andTkutenteEqualTo(Long value) {
            addCriterion("tkutente =", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteNotEqualTo(Long value) {
            addCriterion("tkutente <>", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteGreaterThan(Long value) {
            addCriterion("tkutente >", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteGreaterThanOrEqualTo(Long value) {
            addCriterion("tkutente >=", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteLessThan(Long value) {
            addCriterion("tkutente <", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteLessThanOrEqualTo(Long value) {
            addCriterion("tkutente <=", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteIn(List<Long> values) {
            addCriterion("tkutente in", values, "tkutente");
            return this;
        }

        public Criteria andTkutenteNotIn(List<Long> values) {
            addCriterion("tkutente not in", values, "tkutente");
            return this;
        }

        public Criteria andTkutenteBetween(Long value1, Long value2) {
            addCriterion("tkutente between", value1, value2, "tkutente");
            return this;
        }

        public Criteria andTkutenteNotBetween(Long value1, Long value2) {
            addCriterion("tkutente not between", value1, value2, "tkutente");
            return this;
        }

        public Criteria andUser_nameIsNull() {
            addCriterion("user_name is null");
            return this;
        }

        public Criteria andUser_nameIsNotNull() {
            addCriterion("user_name is not null");
            return this;
        }

        public Criteria andUser_nameEqualTo(String value) {
            addCriterion("user_name =", value, "user_name");
            return this;
        }

        public Criteria andUser_nameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "user_name");
            return this;
        }

        public Criteria andUser_nameGreaterThan(String value) {
            addCriterion("user_name >", value, "user_name");
            return this;
        }

        public Criteria andUser_nameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "user_name");
            return this;
        }

        public Criteria andUser_nameLessThan(String value) {
            addCriterion("user_name <", value, "user_name");
            return this;
        }

        public Criteria andUser_nameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "user_name");
            return this;
        }

        public Criteria andUser_nameLike(String value) {
            addCriterion("user_name like", value, "user_name");
            return this;
        }

        public Criteria andUser_nameNotLike(String value) {
            addCriterion("user_name not like", value, "user_name");
            return this;
        }

        public Criteria andUser_nameIn(List<String> values) {
            addCriterion("user_name in", values, "user_name");
            return this;
        }

        public Criteria andUser_nameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "user_name");
            return this;
        }

        public Criteria andUser_nameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "user_name");
            return this;
        }

        public Criteria andUser_nameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "user_name");
            return this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return this;
        }

        public Criteria andDsutenteIsNull() {
            addCriterion("dsutente is null");
            return this;
        }

        public Criteria andDsutenteIsNotNull() {
            addCriterion("dsutente is not null");
            return this;
        }

        public Criteria andDsutenteEqualTo(String value) {
            addCriterion("dsutente =", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteNotEqualTo(String value) {
            addCriterion("dsutente <>", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteGreaterThan(String value) {
            addCriterion("dsutente >", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteGreaterThanOrEqualTo(String value) {
            addCriterion("dsutente >=", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteLessThan(String value) {
            addCriterion("dsutente <", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteLessThanOrEqualTo(String value) {
            addCriterion("dsutente <=", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteLike(String value) {
            addCriterion("dsutente like", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteNotLike(String value) {
            addCriterion("dsutente not like", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteIn(List<String> values) {
            addCriterion("dsutente in", values, "dsutente");
            return this;
        }

        public Criteria andDsutenteNotIn(List<String> values) {
            addCriterion("dsutente not in", values, "dsutente");
            return this;
        }

        public Criteria andDsutenteBetween(String value1, String value2) {
            addCriterion("dsutente between", value1, value2, "dsutente");
            return this;
        }

        public Criteria andDsutenteNotBetween(String value1, String value2) {
            addCriterion("dsutente not between", value1, value2, "dsutente");
            return this;
        }

        public Criteria andTkclieIsNull() {
            addCriterion("tkclie is null");
            return this;
        }

        public Criteria andTkclieIsNotNull() {
            addCriterion("tkclie is not null");
            return this;
        }

        public Criteria andTkclieEqualTo(String value) {
            addCriterion("tkclie =", value, "tkclie");
            return this;
        }

        public Criteria andTkclieNotEqualTo(String value) {
            addCriterion("tkclie <>", value, "tkclie");
            return this;
        }

        public Criteria andTkclieGreaterThan(String value) {
            addCriterion("tkclie >", value, "tkclie");
            return this;
        }

        public Criteria andTkclieGreaterThanOrEqualTo(String value) {
            addCriterion("tkclie >=", value, "tkclie");
            return this;
        }

        public Criteria andTkclieLessThan(String value) {
            addCriterion("tkclie <", value, "tkclie");
            return this;
        }

        public Criteria andTkclieLessThanOrEqualTo(String value) {
            addCriterion("tkclie <=", value, "tkclie");
            return this;
        }

        public Criteria andTkclieLike(String value) {
            addCriterion("tkclie like", value, "tkclie");
            return this;
        }

        public Criteria andTkclieNotLike(String value) {
            addCriterion("tkclie not like", value, "tkclie");
            return this;
        }

        public Criteria andTkclieIn(List<String> values) {
            addCriterion("tkclie in", values, "tkclie");
            return this;
        }

        public Criteria andTkclieNotIn(List<String> values) {
            addCriterion("tkclie not in", values, "tkclie");
            return this;
        }

        public Criteria andTkclieBetween(String value1, String value2) {
            addCriterion("tkclie between", value1, value2, "tkclie");
            return this;
        }

        public Criteria andTkclieNotBetween(String value1, String value2) {
            addCriterion("tkclie not between", value1, value2, "tkclie");
            return this;
        }

        public Criteria andTkfornIsNull() {
            addCriterion("tkforn is null");
            return this;
        }

        public Criteria andTkfornIsNotNull() {
            addCriterion("tkforn is not null");
            return this;
        }

        public Criteria andTkfornEqualTo(String value) {
            addCriterion("tkforn =", value, "tkforn");
            return this;
        }

        public Criteria andTkfornNotEqualTo(String value) {
            addCriterion("tkforn <>", value, "tkforn");
            return this;
        }

        public Criteria andTkfornGreaterThan(String value) {
            addCriterion("tkforn >", value, "tkforn");
            return this;
        }

        public Criteria andTkfornGreaterThanOrEqualTo(String value) {
            addCriterion("tkforn >=", value, "tkforn");
            return this;
        }

        public Criteria andTkfornLessThan(String value) {
            addCriterion("tkforn <", value, "tkforn");
            return this;
        }

        public Criteria andTkfornLessThanOrEqualTo(String value) {
            addCriterion("tkforn <=", value, "tkforn");
            return this;
        }

        public Criteria andTkfornLike(String value) {
            addCriterion("tkforn like", value, "tkforn");
            return this;
        }

        public Criteria andTkfornNotLike(String value) {
            addCriterion("tkforn not like", value, "tkforn");
            return this;
        }

        public Criteria andTkfornIn(List<String> values) {
            addCriterion("tkforn in", values, "tkforn");
            return this;
        }

        public Criteria andTkfornNotIn(List<String> values) {
            addCriterion("tkforn not in", values, "tkforn");
            return this;
        }

        public Criteria andTkfornBetween(String value1, String value2) {
            addCriterion("tkforn between", value1, value2, "tkforn");
            return this;
        }

        public Criteria andTkfornNotBetween(String value1, String value2) {
            addCriterion("tkforn not between", value1, value2, "tkforn");
            return this;
        }

        public Criteria andCdenteIsNull() {
            addCriterion("cdente is null");
            return this;
        }

        public Criteria andCdenteIsNotNull() {
            addCriterion("cdente is not null");
            return this;
        }

        public Criteria andCdenteEqualTo(String value) {
            addCriterion("cdente =", value, "cdente");
            return this;
        }

        public Criteria andCdenteNotEqualTo(String value) {
            addCriterion("cdente <>", value, "cdente");
            return this;
        }

        public Criteria andCdenteGreaterThan(String value) {
            addCriterion("cdente >", value, "cdente");
            return this;
        }

        public Criteria andCdenteGreaterThanOrEqualTo(String value) {
            addCriterion("cdente >=", value, "cdente");
            return this;
        }

        public Criteria andCdenteLessThan(String value) {
            addCriterion("cdente <", value, "cdente");
            return this;
        }

        public Criteria andCdenteLessThanOrEqualTo(String value) {
            addCriterion("cdente <=", value, "cdente");
            return this;
        }

        public Criteria andCdenteLike(String value) {
            addCriterion("cdente like", value, "cdente");
            return this;
        }

        public Criteria andCdenteNotLike(String value) {
            addCriterion("cdente not like", value, "cdente");
            return this;
        }

        public Criteria andCdenteIn(List<String> values) {
            addCriterion("cdente in", values, "cdente");
            return this;
        }

        public Criteria andCdenteNotIn(List<String> values) {
            addCriterion("cdente not in", values, "cdente");
            return this;
        }

        public Criteria andCdenteBetween(String value1, String value2) {
            addCriterion("cdente between", value1, value2, "cdente");
            return this;
        }

        public Criteria andCdenteNotBetween(String value1, String value2) {
            addCriterion("cdente not between", value1, value2, "cdente");
            return this;
        }

        public Criteria andCdagenIsNull() {
            addCriterion("cdagen is null");
            return this;
        }

        public Criteria andCdagenIsNotNull() {
            addCriterion("cdagen is not null");
            return this;
        }

        public Criteria andCdagenEqualTo(String value) {
            addCriterion("cdagen =", value, "cdagen");
            return this;
        }

        public Criteria andCdagenNotEqualTo(String value) {
            addCriterion("cdagen <>", value, "cdagen");
            return this;
        }

        public Criteria andCdagenGreaterThan(String value) {
            addCriterion("cdagen >", value, "cdagen");
            return this;
        }

        public Criteria andCdagenGreaterThanOrEqualTo(String value) {
            addCriterion("cdagen >=", value, "cdagen");
            return this;
        }

        public Criteria andCdagenLessThan(String value) {
            addCriterion("cdagen <", value, "cdagen");
            return this;
        }

        public Criteria andCdagenLessThanOrEqualTo(String value) {
            addCriterion("cdagen <=", value, "cdagen");
            return this;
        }

        public Criteria andCdagenLike(String value) {
            addCriterion("cdagen like", value, "cdagen");
            return this;
        }

        public Criteria andCdagenNotLike(String value) {
            addCriterion("cdagen not like", value, "cdagen");
            return this;
        }

        public Criteria andCdagenIn(List<String> values) {
            addCriterion("cdagen in", values, "cdagen");
            return this;
        }

        public Criteria andCdagenNotIn(List<String> values) {
            addCriterion("cdagen not in", values, "cdagen");
            return this;
        }

        public Criteria andCdagenBetween(String value1, String value2) {
            addCriterion("cdagen between", value1, value2, "cdagen");
            return this;
        }

        public Criteria andCdagenNotBetween(String value1, String value2) {
            addCriterion("cdagen not between", value1, value2, "cdagen");
            return this;
        }

        public Criteria andCdutenteIsNull() {
            addCriterion("cdutente is null");
            return this;
        }

        public Criteria andCdutenteIsNotNull() {
            addCriterion("cdutente is not null");
            return this;
        }

        public Criteria andCdutenteEqualTo(String value) {
            addCriterion("cdutente =", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteNotEqualTo(String value) {
            addCriterion("cdutente <>", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteGreaterThan(String value) {
            addCriterion("cdutente >", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteGreaterThanOrEqualTo(String value) {
            addCriterion("cdutente >=", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteLessThan(String value) {
            addCriterion("cdutente <", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteLessThanOrEqualTo(String value) {
            addCriterion("cdutente <=", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteLike(String value) {
            addCriterion("cdutente like", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteNotLike(String value) {
            addCriterion("cdutente not like", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteIn(List<String> values) {
            addCriterion("cdutente in", values, "cdutente");
            return this;
        }

        public Criteria andCdutenteNotIn(List<String> values) {
            addCriterion("cdutente not in", values, "cdutente");
            return this;
        }

        public Criteria andCdutenteBetween(String value1, String value2) {
            addCriterion("cdutente between", value1, value2, "cdutente");
            return this;
        }

        public Criteria andCdutenteNotBetween(String value1, String value2) {
            addCriterion("cdutente not between", value1, value2, "cdutente");
            return this;
        }

        public Criteria andFgadminIsNull() {
            addCriterion("fgadmin is null");
            return this;
        }

        public Criteria andFgadminIsNotNull() {
            addCriterion("fgadmin is not null");
            return this;
        }

        public Criteria andFgadminEqualTo(String value) {
            addCriterion("fgadmin =", value, "fgadmin");
            return this;
        }

        public Criteria andFgadminNotEqualTo(String value) {
            addCriterion("fgadmin <>", value, "fgadmin");
            return this;
        }

        public Criteria andFgadminGreaterThan(String value) {
            addCriterion("fgadmin >", value, "fgadmin");
            return this;
        }

        public Criteria andFgadminGreaterThanOrEqualTo(String value) {
            addCriterion("fgadmin >=", value, "fgadmin");
            return this;
        }

        public Criteria andFgadminLessThan(String value) {
            addCriterion("fgadmin <", value, "fgadmin");
            return this;
        }

        public Criteria andFgadminLessThanOrEqualTo(String value) {
            addCriterion("fgadmin <=", value, "fgadmin");
            return this;
        }

        public Criteria andFgadminLike(String value) {
            addCriterion("fgadmin like", value, "fgadmin");
            return this;
        }

        public Criteria andFgadminNotLike(String value) {
            addCriterion("fgadmin not like", value, "fgadmin");
            return this;
        }

        public Criteria andFgadminIn(List<String> values) {
            addCriterion("fgadmin in", values, "fgadmin");
            return this;
        }

        public Criteria andFgadminNotIn(List<String> values) {
            addCriterion("fgadmin not in", values, "fgadmin");
            return this;
        }

        public Criteria andFgadminBetween(String value1, String value2) {
            addCriterion("fgadmin between", value1, value2, "fgadmin");
            return this;
        }

        public Criteria andFgadminNotBetween(String value1, String value2) {
            addCriterion("fgadmin not between", value1, value2, "fgadmin");
            return this;
        }

        public Criteria andCdazieIsNull() {
            addCriterion("cdazie is null");
            return this;
        }

        public Criteria andCdazieIsNotNull() {
            addCriterion("cdazie is not null");
            return this;
        }

        public Criteria andCdazieEqualTo(String value) {
            addCriterion("cdazie =", value, "cdazie");
            return this;
        }

        public Criteria andCdazieNotEqualTo(String value) {
            addCriterion("cdazie <>", value, "cdazie");
            return this;
        }

        public Criteria andCdazieGreaterThan(String value) {
            addCriterion("cdazie >", value, "cdazie");
            return this;
        }

        public Criteria andCdazieGreaterThanOrEqualTo(String value) {
            addCriterion("cdazie >=", value, "cdazie");
            return this;
        }

        public Criteria andCdazieLessThan(String value) {
            addCriterion("cdazie <", value, "cdazie");
            return this;
        }

        public Criteria andCdazieLessThanOrEqualTo(String value) {
            addCriterion("cdazie <=", value, "cdazie");
            return this;
        }

        public Criteria andCdazieLike(String value) {
            addCriterion("cdazie like", value, "cdazie");
            return this;
        }

        public Criteria andCdazieNotLike(String value) {
            addCriterion("cdazie not like", value, "cdazie");
            return this;
        }

        public Criteria andCdazieIn(List<String> values) {
            addCriterion("cdazie in", values, "cdazie");
            return this;
        }

        public Criteria andCdazieNotIn(List<String> values) {
            addCriterion("cdazie not in", values, "cdazie");
            return this;
        }

        public Criteria andCdazieBetween(String value1, String value2) {
            addCriterion("cdazie between", value1, value2, "cdazie");
            return this;
        }

        public Criteria andCdazieNotBetween(String value1, String value2) {
            addCriterion("cdazie not between", value1, value2, "cdazie");
            return this;
        }

        public Criteria andCddipaIsNull() {
            addCriterion("cddipa is null");
            return this;
        }

        public Criteria andCddipaIsNotNull() {
            addCriterion("cddipa is not null");
            return this;
        }

        public Criteria andCddipaEqualTo(String value) {
            addCriterion("cddipa =", value, "cddipa");
            return this;
        }

        public Criteria andCddipaNotEqualTo(String value) {
            addCriterion("cddipa <>", value, "cddipa");
            return this;
        }

        public Criteria andCddipaGreaterThan(String value) {
            addCriterion("cddipa >", value, "cddipa");
            return this;
        }

        public Criteria andCddipaGreaterThanOrEqualTo(String value) {
            addCriterion("cddipa >=", value, "cddipa");
            return this;
        }

        public Criteria andCddipaLessThan(String value) {
            addCriterion("cddipa <", value, "cddipa");
            return this;
        }

        public Criteria andCddipaLessThanOrEqualTo(String value) {
            addCriterion("cddipa <=", value, "cddipa");
            return this;
        }

        public Criteria andCddipaLike(String value) {
            addCriterion("cddipa like", value, "cddipa");
            return this;
        }

        public Criteria andCddipaNotLike(String value) {
            addCriterion("cddipa not like", value, "cddipa");
            return this;
        }

        public Criteria andCddipaIn(List<String> values) {
            addCriterion("cddipa in", values, "cddipa");
            return this;
        }

        public Criteria andCddipaNotIn(List<String> values) {
            addCriterion("cddipa not in", values, "cddipa");
            return this;
        }

        public Criteria andCddipaBetween(String value1, String value2) {
            addCriterion("cddipa between", value1, value2, "cddipa");
            return this;
        }

        public Criteria andCddipaNotBetween(String value1, String value2) {
            addCriterion("cddipa not between", value1, value2, "cddipa");
            return this;
        }

        public Criteria andProfilIsNull() {
            addCriterion("profil is null");
            return this;
        }

        public Criteria andProfilIsNotNull() {
            addCriterion("profil is not null");
            return this;
        }

        public Criteria andProfilEqualTo(String value) {
            addCriterion("profil =", value, "profil");
            return this;
        }

        public Criteria andProfilNotEqualTo(String value) {
            addCriterion("profil <>", value, "profil");
            return this;
        }

        public Criteria andProfilGreaterThan(String value) {
            addCriterion("profil >", value, "profil");
            return this;
        }

        public Criteria andProfilGreaterThanOrEqualTo(String value) {
            addCriterion("profil >=", value, "profil");
            return this;
        }

        public Criteria andProfilLessThan(String value) {
            addCriterion("profil <", value, "profil");
            return this;
        }

        public Criteria andProfilLessThanOrEqualTo(String value) {
            addCriterion("profil <=", value, "profil");
            return this;
        }

        public Criteria andProfilLike(String value) {
            addCriterion("profil like", value, "profil");
            return this;
        }

        public Criteria andProfilNotLike(String value) {
            addCriterion("profil not like", value, "profil");
            return this;
        }

        public Criteria andProfilIn(List<String> values) {
            addCriterion("profil in", values, "profil");
            return this;
        }

        public Criteria andProfilNotIn(List<String> values) {
            addCriterion("profil not in", values, "profil");
            return this;
        }

        public Criteria andProfilBetween(String value1, String value2) {
            addCriterion("profil between", value1, value2, "profil");
            return this;
        }

        public Criteria andProfilNotBetween(String value1, String value2) {
            addCriterion("profil not between", value1, value2, "profil");
            return this;
        }

        public Criteria andDtinseIsNull() {
            addCriterion("dtinse is null");
            return this;
        }

        public Criteria andDtinseIsNotNull() {
            addCriterion("dtinse is not null");
            return this;
        }

        public Criteria andDtinseEqualTo(Date value) {
            addCriterion("dtinse =", value, "dtinse");
            return this;
        }

        public Criteria andDtinseNotEqualTo(Date value) {
            addCriterion("dtinse <>", value, "dtinse");
            return this;
        }

        public Criteria andDtinseGreaterThan(Date value) {
            addCriterion("dtinse >", value, "dtinse");
            return this;
        }

        public Criteria andDtinseGreaterThanOrEqualTo(Date value) {
            addCriterion("dtinse >=", value, "dtinse");
            return this;
        }

        public Criteria andDtinseLessThan(Date value) {
            addCriterion("dtinse <", value, "dtinse");
            return this;
        }

        public Criteria andDtinseLessThanOrEqualTo(Date value) {
            addCriterion("dtinse <=", value, "dtinse");
            return this;
        }

        public Criteria andDtinseIn(List<Date> values) {
            addCriterion("dtinse in", values, "dtinse");
            return this;
        }

        public Criteria andDtinseNotIn(List<Date> values) {
            addCriterion("dtinse not in", values, "dtinse");
            return this;
        }

        public Criteria andDtinseBetween(Date value1, Date value2) {
            addCriterion("dtinse between", value1, value2, "dtinse");
            return this;
        }

        public Criteria andDtinseNotBetween(Date value1, Date value2) {
            addCriterion("dtinse not between", value1, value2, "dtinse");
            return this;
        }

        public Criteria andDtulagIsNull() {
            addCriterion("dtulag is null");
            return this;
        }

        public Criteria andDtulagIsNotNull() {
            addCriterion("dtulag is not null");
            return this;
        }

        public Criteria andDtulagEqualTo(Date value) {
            addCriterion("dtulag =", value, "dtulag");
            return this;
        }

        public Criteria andDtulagNotEqualTo(Date value) {
            addCriterion("dtulag <>", value, "dtulag");
            return this;
        }

        public Criteria andDtulagGreaterThan(Date value) {
            addCriterion("dtulag >", value, "dtulag");
            return this;
        }

        public Criteria andDtulagGreaterThanOrEqualTo(Date value) {
            addCriterion("dtulag >=", value, "dtulag");
            return this;
        }

        public Criteria andDtulagLessThan(Date value) {
            addCriterion("dtulag <", value, "dtulag");
            return this;
        }

        public Criteria andDtulagLessThanOrEqualTo(Date value) {
            addCriterion("dtulag <=", value, "dtulag");
            return this;
        }

        public Criteria andDtulagIn(List<Date> values) {
            addCriterion("dtulag in", values, "dtulag");
            return this;
        }

        public Criteria andDtulagNotIn(List<Date> values) {
            addCriterion("dtulag not in", values, "dtulag");
            return this;
        }

        public Criteria andDtulagBetween(Date value1, Date value2) {
            addCriterion("dtulag between", value1, value2, "dtulag");
            return this;
        }

        public Criteria andDtulagNotBetween(Date value1, Date value2) {
            addCriterion("dtulag not between", value1, value2, "dtulag");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return this;
        }

        public Criteria andCdispeIsNull() {
            addCriterion("cdispe is null");
            return this;
        }

        public Criteria andCdispeIsNotNull() {
            addCriterion("cdispe is not null");
            return this;
        }

        public Criteria andCdispeEqualTo(String value) {
            addCriterion("cdispe =", value, "cdispe");
            return this;
        }

        public Criteria andCdispeNotEqualTo(String value) {
            addCriterion("cdispe <>", value, "cdispe");
            return this;
        }

        public Criteria andCdispeGreaterThan(String value) {
            addCriterion("cdispe >", value, "cdispe");
            return this;
        }

        public Criteria andCdispeGreaterThanOrEqualTo(String value) {
            addCriterion("cdispe >=", value, "cdispe");
            return this;
        }

        public Criteria andCdispeLessThan(String value) {
            addCriterion("cdispe <", value, "cdispe");
            return this;
        }

        public Criteria andCdispeLessThanOrEqualTo(String value) {
            addCriterion("cdispe <=", value, "cdispe");
            return this;
        }

        public Criteria andCdispeLike(String value) {
            addCriterion("cdispe like", value, "cdispe");
            return this;
        }

        public Criteria andCdispeNotLike(String value) {
            addCriterion("cdispe not like", value, "cdispe");
            return this;
        }

        public Criteria andCdispeIn(List<String> values) {
            addCriterion("cdispe in", values, "cdispe");
            return this;
        }

        public Criteria andCdispeNotIn(List<String> values) {
            addCriterion("cdispe not in", values, "cdispe");
            return this;
        }

        public Criteria andCdispeBetween(String value1, String value2) {
            addCriterion("cdispe between", value1, value2, "cdispe");
            return this;
        }

        public Criteria andCdispeNotBetween(String value1, String value2) {
            addCriterion("cdispe not between", value1, value2, "cdispe");
            return this;
        }

        public Criteria andCdlingIsNull() {
            addCriterion("cdling is null");
            return this;
        }

        public Criteria andCdlingIsNotNull() {
            addCriterion("cdling is not null");
            return this;
        }

        public Criteria andCdlingEqualTo(String value) {
            addCriterion("cdling =", value, "cdling");
            return this;
        }

        public Criteria andCdlingNotEqualTo(String value) {
            addCriterion("cdling <>", value, "cdling");
            return this;
        }

        public Criteria andCdlingGreaterThan(String value) {
            addCriterion("cdling >", value, "cdling");
            return this;
        }

        public Criteria andCdlingGreaterThanOrEqualTo(String value) {
            addCriterion("cdling >=", value, "cdling");
            return this;
        }

        public Criteria andCdlingLessThan(String value) {
            addCriterion("cdling <", value, "cdling");
            return this;
        }

        public Criteria andCdlingLessThanOrEqualTo(String value) {
            addCriterion("cdling <=", value, "cdling");
            return this;
        }

        public Criteria andCdlingLike(String value) {
            addCriterion("cdling like", value, "cdling");
            return this;
        }

        public Criteria andCdlingNotLike(String value) {
            addCriterion("cdling not like", value, "cdling");
            return this;
        }

        public Criteria andCdlingIn(List<String> values) {
            addCriterion("cdling in", values, "cdling");
            return this;
        }

        public Criteria andCdlingNotIn(List<String> values) {
            addCriterion("cdling not in", values, "cdling");
            return this;
        }

        public Criteria andCdlingBetween(String value1, String value2) {
            addCriterion("cdling between", value1, value2, "cdling");
            return this;
        }

        public Criteria andCdlingNotBetween(String value1, String value2) {
            addCriterion("cdling not between", value1, value2, "cdling");
            return this;
        }

        public Criteria andCellulareIsNull() {
            addCriterion("cellulare is null");
            return this;
        }

        public Criteria andCellulareIsNotNull() {
            addCriterion("cellulare is not null");
            return this;
        }

        public Criteria andCellulareEqualTo(String value) {
            addCriterion("cellulare =", value, "cellulare");
            return this;
        }

        public Criteria andCellulareNotEqualTo(String value) {
            addCriterion("cellulare <>", value, "cellulare");
            return this;
        }

        public Criteria andCellulareGreaterThan(String value) {
            addCriterion("cellulare >", value, "cellulare");
            return this;
        }

        public Criteria andCellulareGreaterThanOrEqualTo(String value) {
            addCriterion("cellulare >=", value, "cellulare");
            return this;
        }

        public Criteria andCellulareLessThan(String value) {
            addCriterion("cellulare <", value, "cellulare");
            return this;
        }

        public Criteria andCellulareLessThanOrEqualTo(String value) {
            addCriterion("cellulare <=", value, "cellulare");
            return this;
        }

        public Criteria andCellulareLike(String value) {
            addCriterion("cellulare like", value, "cellulare");
            return this;
        }

        public Criteria andCellulareNotLike(String value) {
            addCriterion("cellulare not like", value, "cellulare");
            return this;
        }

        public Criteria andCellulareIn(List<String> values) {
            addCriterion("cellulare in", values, "cellulare");
            return this;
        }

        public Criteria andCellulareNotIn(List<String> values) {
            addCriterion("cellulare not in", values, "cellulare");
            return this;
        }

        public Criteria andCellulareBetween(String value1, String value2) {
            addCriterion("cellulare between", value1, value2, "cellulare");
            return this;
        }

        public Criteria andCellulareNotBetween(String value1, String value2) {
            addCriterion("cellulare not between", value1, value2, "cellulare");
            return this;
        }

        public Criteria andNfaxsiIsNull() {
            addCriterion("nfaxsi is null");
            return this;
        }

        public Criteria andNfaxsiIsNotNull() {
            addCriterion("nfaxsi is not null");
            return this;
        }

        public Criteria andNfaxsiEqualTo(String value) {
            addCriterion("nfaxsi =", value, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiNotEqualTo(String value) {
            addCriterion("nfaxsi <>", value, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiGreaterThan(String value) {
            addCriterion("nfaxsi >", value, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiGreaterThanOrEqualTo(String value) {
            addCriterion("nfaxsi >=", value, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiLessThan(String value) {
            addCriterion("nfaxsi <", value, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiLessThanOrEqualTo(String value) {
            addCriterion("nfaxsi <=", value, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiLike(String value) {
            addCriterion("nfaxsi like", value, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiNotLike(String value) {
            addCriterion("nfaxsi not like", value, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiIn(List<String> values) {
            addCriterion("nfaxsi in", values, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiNotIn(List<String> values) {
            addCriterion("nfaxsi not in", values, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiBetween(String value1, String value2) {
            addCriterion("nfaxsi between", value1, value2, "nfaxsi");
            return this;
        }

        public Criteria andNfaxsiNotBetween(String value1, String value2) {
            addCriterion("nfaxsi not between", value1, value2, "nfaxsi");
            return this;
        }

        public Criteria andFtp_user_nameIsNull() {
            addCriterion("ftp_user_name is null");
            return this;
        }

        public Criteria andFtp_user_nameIsNotNull() {
            addCriterion("ftp_user_name is not null");
            return this;
        }

        public Criteria andFtp_user_nameEqualTo(String value) {
            addCriterion("ftp_user_name =", value, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameNotEqualTo(String value) {
            addCriterion("ftp_user_name <>", value, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameGreaterThan(String value) {
            addCriterion("ftp_user_name >", value, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameGreaterThanOrEqualTo(String value) {
            addCriterion("ftp_user_name >=", value, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameLessThan(String value) {
            addCriterion("ftp_user_name <", value, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameLessThanOrEqualTo(String value) {
            addCriterion("ftp_user_name <=", value, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameLike(String value) {
            addCriterion("ftp_user_name like", value, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameNotLike(String value) {
            addCriterion("ftp_user_name not like", value, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameIn(List<String> values) {
            addCriterion("ftp_user_name in", values, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameNotIn(List<String> values) {
            addCriterion("ftp_user_name not in", values, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameBetween(String value1, String value2) {
            addCriterion("ftp_user_name between", value1, value2, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_user_nameNotBetween(String value1, String value2) {
            addCriterion("ftp_user_name not between", value1, value2, "ftp_user_name");
            return this;
        }

        public Criteria andFtp_passwordIsNull() {
            addCriterion("ftp_password is null");
            return this;
        }

        public Criteria andFtp_passwordIsNotNull() {
            addCriterion("ftp_password is not null");
            return this;
        }

        public Criteria andFtp_passwordEqualTo(String value) {
            addCriterion("ftp_password =", value, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordNotEqualTo(String value) {
            addCriterion("ftp_password <>", value, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordGreaterThan(String value) {
            addCriterion("ftp_password >", value, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordGreaterThanOrEqualTo(String value) {
            addCriterion("ftp_password >=", value, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordLessThan(String value) {
            addCriterion("ftp_password <", value, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordLessThanOrEqualTo(String value) {
            addCriterion("ftp_password <=", value, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordLike(String value) {
            addCriterion("ftp_password like", value, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordNotLike(String value) {
            addCriterion("ftp_password not like", value, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordIn(List<String> values) {
            addCriterion("ftp_password in", values, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordNotIn(List<String> values) {
            addCriterion("ftp_password not in", values, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordBetween(String value1, String value2) {
            addCriterion("ftp_password between", value1, value2, "ftp_password");
            return this;
        }

        public Criteria andFtp_passwordNotBetween(String value1, String value2) {
            addCriterion("ftp_password not between", value1, value2, "ftp_password");
            return this;
        }

        public Criteria andFtp_password_backIsNull() {
            addCriterion("ftp_password_back is null");
            return this;
        }

        public Criteria andFtp_password_backIsNotNull() {
            addCriterion("ftp_password_back is not null");
            return this;
        }

        public Criteria andFtp_password_backEqualTo(String value) {
            addCriterion("ftp_password_back =", value, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backNotEqualTo(String value) {
            addCriterion("ftp_password_back <>", value, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backGreaterThan(String value) {
            addCriterion("ftp_password_back >", value, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backGreaterThanOrEqualTo(String value) {
            addCriterion("ftp_password_back >=", value, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backLessThan(String value) {
            addCriterion("ftp_password_back <", value, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backLessThanOrEqualTo(String value) {
            addCriterion("ftp_password_back <=", value, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backLike(String value) {
            addCriterion("ftp_password_back like", value, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backNotLike(String value) {
            addCriterion("ftp_password_back not like", value, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backIn(List<String> values) {
            addCriterion("ftp_password_back in", values, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backNotIn(List<String> values) {
            addCriterion("ftp_password_back not in", values, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backBetween(String value1, String value2) {
            addCriterion("ftp_password_back between", value1, value2, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_password_backNotBetween(String value1, String value2) {
            addCriterion("ftp_password_back not between", value1, value2, "ftp_password_back");
            return this;
        }

        public Criteria andFtp_fgabilIsNull() {
            addCriterion("ftp_fgabil is null");
            return this;
        }

        public Criteria andFtp_fgabilIsNotNull() {
            addCriterion("ftp_fgabil is not null");
            return this;
        }

        public Criteria andFtp_fgabilEqualTo(String value) {
            addCriterion("ftp_fgabil =", value, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilNotEqualTo(String value) {
            addCriterion("ftp_fgabil <>", value, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilGreaterThan(String value) {
            addCriterion("ftp_fgabil >", value, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilGreaterThanOrEqualTo(String value) {
            addCriterion("ftp_fgabil >=", value, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilLessThan(String value) {
            addCriterion("ftp_fgabil <", value, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilLessThanOrEqualTo(String value) {
            addCriterion("ftp_fgabil <=", value, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilLike(String value) {
            addCriterion("ftp_fgabil like", value, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilNotLike(String value) {
            addCriterion("ftp_fgabil not like", value, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilIn(List<String> values) {
            addCriterion("ftp_fgabil in", values, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilNotIn(List<String> values) {
            addCriterion("ftp_fgabil not in", values, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilBetween(String value1, String value2) {
            addCriterion("ftp_fgabil between", value1, value2, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabilNotBetween(String value1, String value2) {
            addCriterion("ftp_fgabil not between", value1, value2, "ftp_fgabil");
            return this;
        }

        public Criteria andFtp_fgabil_backIsNull() {
            addCriterion("ftp_fgabil_back is null");
            return this;
        }

        public Criteria andFtp_fgabil_backIsNotNull() {
            addCriterion("ftp_fgabil_back is not null");
            return this;
        }

        public Criteria andFtp_fgabil_backEqualTo(String value) {
            addCriterion("ftp_fgabil_back =", value, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backNotEqualTo(String value) {
            addCriterion("ftp_fgabil_back <>", value, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backGreaterThan(String value) {
            addCriterion("ftp_fgabil_back >", value, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backGreaterThanOrEqualTo(String value) {
            addCriterion("ftp_fgabil_back >=", value, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backLessThan(String value) {
            addCriterion("ftp_fgabil_back <", value, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backLessThanOrEqualTo(String value) {
            addCriterion("ftp_fgabil_back <=", value, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backLike(String value) {
            addCriterion("ftp_fgabil_back like", value, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backNotLike(String value) {
            addCriterion("ftp_fgabil_back not like", value, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backIn(List<String> values) {
            addCriterion("ftp_fgabil_back in", values, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backNotIn(List<String> values) {
            addCriterion("ftp_fgabil_back not in", values, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backBetween(String value1, String value2) {
            addCriterion("ftp_fgabil_back between", value1, value2, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFtp_fgabil_backNotBetween(String value1, String value2) {
            addCriterion("ftp_fgabil_back not between", value1, value2, "ftp_fgabil_back");
            return this;
        }

        public Criteria andFgabilIsNull() {
            addCriterion("fgabil is null");
            return this;
        }

        public Criteria andFgabilIsNotNull() {
            addCriterion("fgabil is not null");
            return this;
        }

        public Criteria andFgabilEqualTo(String value) {
            addCriterion("fgabil =", value, "fgabil");
            return this;
        }

        public Criteria andFgabilNotEqualTo(String value) {
            addCriterion("fgabil <>", value, "fgabil");
            return this;
        }

        public Criteria andFgabilGreaterThan(String value) {
            addCriterion("fgabil >", value, "fgabil");
            return this;
        }

        public Criteria andFgabilGreaterThanOrEqualTo(String value) {
            addCriterion("fgabil >=", value, "fgabil");
            return this;
        }

        public Criteria andFgabilLessThan(String value) {
            addCriterion("fgabil <", value, "fgabil");
            return this;
        }

        public Criteria andFgabilLessThanOrEqualTo(String value) {
            addCriterion("fgabil <=", value, "fgabil");
            return this;
        }

        public Criteria andFgabilLike(String value) {
            addCriterion("fgabil like", value, "fgabil");
            return this;
        }

        public Criteria andFgabilNotLike(String value) {
            addCriterion("fgabil not like", value, "fgabil");
            return this;
        }

        public Criteria andFgabilIn(List<String> values) {
            addCriterion("fgabil in", values, "fgabil");
            return this;
        }

        public Criteria andFgabilNotIn(List<String> values) {
            addCriterion("fgabil not in", values, "fgabil");
            return this;
        }

        public Criteria andFgabilBetween(String value1, String value2) {
            addCriterion("fgabil between", value1, value2, "fgabil");
            return this;
        }

        public Criteria andFgabilNotBetween(String value1, String value2) {
            addCriterion("fgabil not between", value1, value2, "fgabil");
            return this;
        }

        public Criteria andTktputenteIsNull() {
            addCriterion("tktputente is null");
            return this;
        }

        public Criteria andTktputenteIsNotNull() {
            addCriterion("tktputente is not null");
            return this;
        }

        public Criteria andTktputenteEqualTo(Long value) {
            addCriterion("tktputente =", value, "tktputente");
            return this;
        }

        public Criteria andTktputenteNotEqualTo(Long value) {
            addCriterion("tktputente <>", value, "tktputente");
            return this;
        }

        public Criteria andTktputenteGreaterThan(Long value) {
            addCriterion("tktputente >", value, "tktputente");
            return this;
        }

        public Criteria andTktputenteGreaterThanOrEqualTo(Long value) {
            addCriterion("tktputente >=", value, "tktputente");
            return this;
        }

        public Criteria andTktputenteLessThan(Long value) {
            addCriterion("tktputente <", value, "tktputente");
            return this;
        }

        public Criteria andTktputenteLessThanOrEqualTo(Long value) {
            addCriterion("tktputente <=", value, "tktputente");
            return this;
        }

        public Criteria andTktputenteIn(List<Long> values) {
            addCriterion("tktputente in", values, "tktputente");
            return this;
        }

        public Criteria andTktputenteNotIn(List<Long> values) {
            addCriterion("tktputente not in", values, "tktputente");
            return this;
        }

        public Criteria andTktputenteBetween(Long value1, Long value2) {
            addCriterion("tktputente between", value1, value2, "tktputente");
            return this;
        }

        public Criteria andTktputenteNotBetween(Long value1, Long value2) {
            addCriterion("tktputente not between", value1, value2, "tktputente");
            return this;
        }

        public Criteria andLivelloIsNull() {
            addCriterion("livello is null");
            return this;
        }

        public Criteria andLivelloIsNotNull() {
            addCriterion("livello is not null");
            return this;
        }

        public Criteria andLivelloEqualTo(Long value) {
            addCriterion("livello =", value, "livello");
            return this;
        }

        public Criteria andLivelloNotEqualTo(Long value) {
            addCriterion("livello <>", value, "livello");
            return this;
        }

        public Criteria andLivelloGreaterThan(Long value) {
            addCriterion("livello >", value, "livello");
            return this;
        }

        public Criteria andLivelloGreaterThanOrEqualTo(Long value) {
            addCriterion("livello >=", value, "livello");
            return this;
        }

        public Criteria andLivelloLessThan(Long value) {
            addCriterion("livello <", value, "livello");
            return this;
        }

        public Criteria andLivelloLessThanOrEqualTo(Long value) {
            addCriterion("livello <=", value, "livello");
            return this;
        }

        public Criteria andLivelloIn(List<Long> values) {
            addCriterion("livello in", values, "livello");
            return this;
        }

        public Criteria andLivelloNotIn(List<Long> values) {
            addCriterion("livello not in", values, "livello");
            return this;
        }

        public Criteria andLivelloBetween(Long value1, Long value2) {
            addCriterion("livello between", value1, value2, "livello");
            return this;
        }

        public Criteria andLivelloNotBetween(Long value1, Long value2) {
            addCriterion("livello not between", value1, value2, "livello");
            return this;
        }

        public Criteria andTksubutenteIsNull() {
            addCriterion("tksubutente is null");
            return this;
        }

        public Criteria andTksubutenteIsNotNull() {
            addCriterion("tksubutente is not null");
            return this;
        }

        public Criteria andTksubutenteEqualTo(Long value) {
            addCriterion("tksubutente =", value, "tksubutente");
            return this;
        }

        public Criteria andTksubutenteNotEqualTo(Long value) {
            addCriterion("tksubutente <>", value, "tksubutente");
            return this;
        }

        public Criteria andTksubutenteGreaterThan(Long value) {
            addCriterion("tksubutente >", value, "tksubutente");
            return this;
        }

        public Criteria andTksubutenteGreaterThanOrEqualTo(Long value) {
            addCriterion("tksubutente >=", value, "tksubutente");
            return this;
        }

        public Criteria andTksubutenteLessThan(Long value) {
            addCriterion("tksubutente <", value, "tksubutente");
            return this;
        }

        public Criteria andTksubutenteLessThanOrEqualTo(Long value) {
            addCriterion("tksubutente <=", value, "tksubutente");
            return this;
        }

        public Criteria andTksubutenteIn(List<Long> values) {
            addCriterion("tksubutente in", values, "tksubutente");
            return this;
        }

        public Criteria andTksubutenteNotIn(List<Long> values) {
            addCriterion("tksubutente not in", values, "tksubutente");
            return this;
        }

        public Criteria andTksubutenteBetween(Long value1, Long value2) {
            addCriterion("tksubutente between", value1, value2, "tksubutente");
            return this;
        }

        public Criteria andTksubutenteNotBetween(Long value1, Long value2) {
            addCriterion("tksubutente not between", value1, value2, "tksubutente");
            return this;
        }
    }
}