package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;

public class Mrp_arch_stato extends BaseTableBean {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.cdstato
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdstato;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.cdstato_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdstato_m;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.dsstato
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsstato;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.fesclu
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String fesclu;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.dsstatoweb
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsstatoweb;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String fg_agg;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.vist_fgrgb
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String vist_fgrgb;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.vist_rgb_r
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private Short vist_rgb_r;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.vist_rgb_g
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private Short vist_rgb_g;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.vist_rgb_b
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private Short vist_rgb_b;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.dsstato_en
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsstato_en;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.dsstato_de
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsstato_de;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.dsstato_fr
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsstato_fr;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.dsstato_es
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsstato_es;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.fgweb
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String fgweb;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.mrp_arch_stato.dsstato_ru
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsstato_ru;
    
    public Mrp_arch_stato() {
    }     
    
    public Mrp_arch_stato(int vist_rgb_r, int vist_rgb_g, int vist_rgb_b) {
        this.vist_rgb_r = (short)vist_rgb_r;
        this.vist_rgb_g = (short)vist_rgb_g;
        this.vist_rgb_b = (short)vist_rgb_b;
    }    

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.cdstato
     *
     * @return the value of pgmr.mrp_arch_stato.cdstato
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdstato() {
        return cdstato;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.cdstato
     *
     * @param cdstato the value for pgmr.mrp_arch_stato.cdstato
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdstato(String cdstato) {
        this.cdstato = cdstato == null ? null : cdstato.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.cdstato_m
     *
     * @return the value of pgmr.mrp_arch_stato.cdstato_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdstato_m() {
        return cdstato_m;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.cdstato_m
     *
     * @param cdstato_m the value for pgmr.mrp_arch_stato.cdstato_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdstato_m(String cdstato_m) {
        this.cdstato_m = cdstato_m == null ? null : cdstato_m.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.dsstato
     *
     * @return the value of pgmr.mrp_arch_stato.dsstato
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsstato() {
        return dsstato;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.dsstato
     *
     * @param dsstato the value for pgmr.mrp_arch_stato.dsstato
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsstato(String dsstato) {
        this.dsstato = dsstato == null ? null : dsstato.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.fesclu
     *
     * @return the value of pgmr.mrp_arch_stato.fesclu
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getFesclu() {
        return fesclu;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.fesclu
     *
     * @param fesclu the value for pgmr.mrp_arch_stato.fesclu
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setFesclu(String fesclu) {
        this.fesclu = fesclu == null ? null : fesclu.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.dsstatoweb
     *
     * @return the value of pgmr.mrp_arch_stato.dsstatoweb
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsstatoweb() {
        return dsstatoweb;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.dsstatoweb
     *
     * @param dsstatoweb the value for pgmr.mrp_arch_stato.dsstatoweb
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsstatoweb(String dsstatoweb) {
        this.dsstatoweb = dsstatoweb == null ? null : dsstatoweb.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.fg_agg
     *
     * @return the value of pgmr.mrp_arch_stato.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getFg_agg() {
        return fg_agg;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.fg_agg
     *
     * @param fg_agg the value for pgmr.mrp_arch_stato.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setFg_agg(String fg_agg) {
        this.fg_agg = fg_agg == null ? null : fg_agg.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.vist_fgrgb
     *
     * @return the value of pgmr.mrp_arch_stato.vist_fgrgb
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getVist_fgrgb() {
        return vist_fgrgb;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.vist_fgrgb
     *
     * @param vist_fgrgb the value for pgmr.mrp_arch_stato.vist_fgrgb
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setVist_fgrgb(String vist_fgrgb) {
        this.vist_fgrgb = vist_fgrgb == null ? null : vist_fgrgb.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.vist_rgb_r
     *
     * @return the value of pgmr.mrp_arch_stato.vist_rgb_r
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public Short getVist_rgb_r() {
        return vist_rgb_r;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.vist_rgb_r
     *
     * @param vist_rgb_r the value for pgmr.mrp_arch_stato.vist_rgb_r
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setVist_rgb_r(Short vist_rgb_r) {
        this.vist_rgb_r = vist_rgb_r;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.vist_rgb_g
     *
     * @return the value of pgmr.mrp_arch_stato.vist_rgb_g
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public Short getVist_rgb_g() {
        return vist_rgb_g;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.vist_rgb_g
     *
     * @param vist_rgb_g the value for pgmr.mrp_arch_stato.vist_rgb_g
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setVist_rgb_g(Short vist_rgb_g) {
        this.vist_rgb_g = vist_rgb_g;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.vist_rgb_b
     *
     * @return the value of pgmr.mrp_arch_stato.vist_rgb_b
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public Short getVist_rgb_b() {
        return vist_rgb_b;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.vist_rgb_b
     *
     * @param vist_rgb_b the value for pgmr.mrp_arch_stato.vist_rgb_b
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setVist_rgb_b(Short vist_rgb_b) {
        this.vist_rgb_b = vist_rgb_b;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.dsstato_en
     *
     * @return the value of pgmr.mrp_arch_stato.dsstato_en
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsstato_en() {
        return dsstato_en;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.dsstato_en
     *
     * @param dsstato_en the value for pgmr.mrp_arch_stato.dsstato_en
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsstato_en(String dsstato_en) {
        this.dsstato_en = dsstato_en == null ? null : dsstato_en.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.dsstato_de
     *
     * @return the value of pgmr.mrp_arch_stato.dsstato_de
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsstato_de() {
        return dsstato_de;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.dsstato_de
     *
     * @param dsstato_de the value for pgmr.mrp_arch_stato.dsstato_de
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsstato_de(String dsstato_de) {
        this.dsstato_de = dsstato_de == null ? null : dsstato_de.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.dsstato_fr
     *
     * @return the value of pgmr.mrp_arch_stato.dsstato_fr
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsstato_fr() {
        return dsstato_fr;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.dsstato_fr
     *
     * @param dsstato_fr the value for pgmr.mrp_arch_stato.dsstato_fr
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsstato_fr(String dsstato_fr) {
        this.dsstato_fr = dsstato_fr == null ? null : dsstato_fr.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.dsstato_es
     *
     * @return the value of pgmr.mrp_arch_stato.dsstato_es
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsstato_es() {
        return dsstato_es;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.dsstato_es
     *
     * @param dsstato_es the value for pgmr.mrp_arch_stato.dsstato_es
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsstato_es(String dsstato_es) {
        this.dsstato_es = dsstato_es == null ? null : dsstato_es.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.fgweb
     *
     * @return the value of pgmr.mrp_arch_stato.fgweb
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getFgweb() {
        return fgweb;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.fgweb
     *
     * @param fgweb the value for pgmr.mrp_arch_stato.fgweb
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setFgweb(String fgweb) {
        this.fgweb = fgweb == null ? null : fgweb.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.mrp_arch_stato.dsstato_ru
     *
     * @return the value of pgmr.mrp_arch_stato.dsstato_ru
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsstato_ru() {
        return dsstato_ru;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.mrp_arch_stato.dsstato_ru
     *
     * @param dsstato_ru the value for pgmr.mrp_arch_stato.dsstato_ru
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsstato_ru(String dsstato_ru) {
        this.dsstato_ru = dsstato_ru == null ? null : dsstato_ru.trim();
    }
}