package com.ateikon.internet.eprogen.domain.pgmr;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Sottogruppo_tipologiaExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Sottogruppo_tipologiaExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    protected Sottogruppo_tipologiaExample(Sottogruppo_tipologiaExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andCdlinguaIsNull() {
            addCriterion("cdlingua is null");
            return this;
        }

        public Criteria andCdlinguaIsNotNull() {
            addCriterion("cdlingua is not null");
            return this;
        }

        public Criteria andCdlinguaEqualTo(Integer value) {
            addCriterion("cdlingua =", value, "cdlingua");
            return this;
        }

        public Criteria andCdlinguaNotEqualTo(Integer value) {
            addCriterion("cdlingua <>", value, "cdlingua");
            return this;
        }

        public Criteria andCdlinguaGreaterThan(Integer value) {
            addCriterion("cdlingua >", value, "cdlingua");
            return this;
        }

        public Criteria andCdlinguaGreaterThanOrEqualTo(Integer value) {
            addCriterion("cdlingua >=", value, "cdlingua");
            return this;
        }

        public Criteria andCdlinguaLessThan(Integer value) {
            addCriterion("cdlingua <", value, "cdlingua");
            return this;
        }

        public Criteria andCdlinguaLessThanOrEqualTo(Integer value) {
            addCriterion("cdlingua <=", value, "cdlingua");
            return this;
        }

        public Criteria andCdlinguaIn(List<Integer> values) {
            addCriterion("cdlingua in", values, "cdlingua");
            return this;
        }

        public Criteria andCdlinguaNotIn(List<Integer> values) {
            addCriterion("cdlingua not in", values, "cdlingua");
            return this;
        }

        public Criteria andCdlinguaBetween(Integer value1, Integer value2) {
            addCriterion("cdlingua between", value1, value2, "cdlingua");
            return this;
        }

        public Criteria andCdlinguaNotBetween(Integer value1, Integer value2) {
            addCriterion("cdlingua not between", value1, value2, "cdlingua");
            return this;
        }

        public Criteria andCdsottogruppoIsNull() {
            addCriterion("cdsottogruppo is null");
            return this;
        }

        public Criteria andCdsottogruppoIsNotNull() {
            addCriterion("cdsottogruppo is not null");
            return this;
        }

        public Criteria andCdsottogruppoEqualTo(Integer value) {
            addCriterion("cdsottogruppo =", value, "cdsottogruppo");
            return this;
        }

        public Criteria andCdsottogruppoNotEqualTo(Integer value) {
            addCriterion("cdsottogruppo <>", value, "cdsottogruppo");
            return this;
        }

        public Criteria andCdsottogruppoGreaterThan(Integer value) {
            addCriterion("cdsottogruppo >", value, "cdsottogruppo");
            return this;
        }

        public Criteria andCdsottogruppoGreaterThanOrEqualTo(Integer value) {
            addCriterion("cdsottogruppo >=", value, "cdsottogruppo");
            return this;
        }

        public Criteria andCdsottogruppoLessThan(Integer value) {
            addCriterion("cdsottogruppo <", value, "cdsottogruppo");
            return this;
        }

        public Criteria andCdsottogruppoLessThanOrEqualTo(Integer value) {
            addCriterion("cdsottogruppo <=", value, "cdsottogruppo");
            return this;
        }

        public Criteria andCdsottogruppoIn(List<Integer> values) {
            addCriterion("cdsottogruppo in", values, "cdsottogruppo");
            return this;
        }

        public Criteria andCdsottogruppoNotIn(List<Integer> values) {
            addCriterion("cdsottogruppo not in", values, "cdsottogruppo");
            return this;
        }

        public Criteria andCdsottogruppoBetween(Integer value1, Integer value2) {
            addCriterion("cdsottogruppo between", value1, value2, "cdsottogruppo");
            return this;
        }

        public Criteria andCdsottogruppoNotBetween(Integer value1, Integer value2) {
            addCriterion("cdsottogruppo not between", value1, value2, "cdsottogruppo");
            return this;
        }

        public Criteria andDssottogruppoIsNull() {
            addCriterion("dssottogruppo is null");
            return this;
        }

        public Criteria andDssottogruppoIsNotNull() {
            addCriterion("dssottogruppo is not null");
            return this;
        }

        public Criteria andDssottogruppoEqualTo(String value) {
            addCriterion("dssottogruppo =", value, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoNotEqualTo(String value) {
            addCriterion("dssottogruppo <>", value, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoGreaterThan(String value) {
            addCriterion("dssottogruppo >", value, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoGreaterThanOrEqualTo(String value) {
            addCriterion("dssottogruppo >=", value, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoLessThan(String value) {
            addCriterion("dssottogruppo <", value, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoLessThanOrEqualTo(String value) {
            addCriterion("dssottogruppo <=", value, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoLike(String value) {
            addCriterion("dssottogruppo like", value, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoNotLike(String value) {
            addCriterion("dssottogruppo not like", value, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoIn(List<String> values) {
            addCriterion("dssottogruppo in", values, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoNotIn(List<String> values) {
            addCriterion("dssottogruppo not in", values, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoBetween(String value1, String value2) {
            addCriterion("dssottogruppo between", value1, value2, "dssottogruppo");
            return this;
        }

        public Criteria andDssottogruppoNotBetween(String value1, String value2) {
            addCriterion("dssottogruppo not between", value1, value2, "dssottogruppo");
            return this;
        }

        public Criteria andCdgruppoIsNull() {
            addCriterion("cdgruppo is null");
            return this;
        }

        public Criteria andCdgruppoIsNotNull() {
            addCriterion("cdgruppo is not null");
            return this;
        }

        public Criteria andCdgruppoEqualTo(Integer value) {
            addCriterion("cdgruppo =", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoNotEqualTo(Integer value) {
            addCriterion("cdgruppo <>", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoGreaterThan(Integer value) {
            addCriterion("cdgruppo >", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoGreaterThanOrEqualTo(Integer value) {
            addCriterion("cdgruppo >=", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoLessThan(Integer value) {
            addCriterion("cdgruppo <", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoLessThanOrEqualTo(Integer value) {
            addCriterion("cdgruppo <=", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoIn(List<Integer> values) {
            addCriterion("cdgruppo in", values, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoNotIn(List<Integer> values) {
            addCriterion("cdgruppo not in", values, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoBetween(Integer value1, Integer value2) {
            addCriterion("cdgruppo between", value1, value2, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoNotBetween(Integer value1, Integer value2) {
            addCriterion("cdgruppo not between", value1, value2, "cdgruppo");
            return this;
        }

        public Criteria andNrposiIsNull() {
            addCriterion("nrposi is null");
            return this;
        }

        public Criteria andNrposiIsNotNull() {
            addCriterion("nrposi is not null");
            return this;
        }

        public Criteria andNrposiEqualTo(Integer value) {
            addCriterion("nrposi =", value, "nrposi");
            return this;
        }

        public Criteria andNrposiNotEqualTo(Integer value) {
            addCriterion("nrposi <>", value, "nrposi");
            return this;
        }

        public Criteria andNrposiGreaterThan(Integer value) {
            addCriterion("nrposi >", value, "nrposi");
            return this;
        }

        public Criteria andNrposiGreaterThanOrEqualTo(Integer value) {
            addCriterion("nrposi >=", value, "nrposi");
            return this;
        }

        public Criteria andNrposiLessThan(Integer value) {
            addCriterion("nrposi <", value, "nrposi");
            return this;
        }

        public Criteria andNrposiLessThanOrEqualTo(Integer value) {
            addCriterion("nrposi <=", value, "nrposi");
            return this;
        }

        public Criteria andNrposiIn(List<Integer> values) {
            addCriterion("nrposi in", values, "nrposi");
            return this;
        }

        public Criteria andNrposiNotIn(List<Integer> values) {
            addCriterion("nrposi not in", values, "nrposi");
            return this;
        }

        public Criteria andNrposiBetween(Integer value1, Integer value2) {
            addCriterion("nrposi between", value1, value2, "nrposi");
            return this;
        }

        public Criteria andNrposiNotBetween(Integer value1, Integer value2) {
            addCriterion("nrposi not between", value1, value2, "nrposi");
            return this;
        }
    }
}