package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;

public class Tipi_prodottoKey extends BaseTableBean {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pgmr.tipi_prodotto.cdlingua
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    private Integer cdlingua;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column pgmr.tipi_prodotto.cdtipoprodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    private Integer cdtipoprodotto;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pgmr.tipi_prodotto.cdlingua
     *
     * @return the value of pgmr.tipi_prodotto.cdlingua
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Integer getCdlingua() {
        return cdlingua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pgmr.tipi_prodotto.cdlingua
     *
     * @param cdlingua the value for pgmr.tipi_prodotto.cdlingua
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void setCdlingua(Integer cdlingua) {
        this.cdlingua = cdlingua;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column pgmr.tipi_prodotto.cdtipoprodotto
     *
     * @return the value of pgmr.tipi_prodotto.cdtipoprodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Integer getCdtipoprodotto() {
        return cdtipoprodotto;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column pgmr.tipi_prodotto.cdtipoprodotto
     *
     * @param cdtipoprodotto the value for pgmr.tipi_prodotto.cdtipoprodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void setCdtipoprodotto(Integer cdtipoprodotto) {
        this.cdtipoprodotto = cdtipoprodotto;
    }
}