package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;
import java.util.Date;

public class Unitalocali extends BaseTableBean {


    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.cdunil
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String cdunil;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.cdunil_m
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String cdunil_m;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.dsunil
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String dsunil;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.dtfval
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private Date dtfval;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.indiri
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String indiri;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.cap
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String cap;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.comune
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String comune;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.cdprov
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String cdprov;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.cdnazi
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String cdnazi;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.ntelef
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String ntelef;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.nfaxsi
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String nfaxsi;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.email
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String email;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.wwwpage
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String wwwpage;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.cdzone
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String cdzone;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.cdagen
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String cdagen;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.cdzcom
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String cdzcom;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.codfao
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String codfao;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.qcodfao
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String qcodfao;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.cdtaut
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String cdtaut;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.unitalocali.fg_agg
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    private String fg_agg;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.cdunil
     *
     * @return the value of pgmr.unitalocali.cdunil
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCdunil() {
        return cdunil;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.cdunil
     *
     * @param cdunil the value for pgmr.unitalocali.cdunil
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCdunil(String cdunil) {
        this.cdunil = cdunil == null ? null : cdunil.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.cdunil_m
     *
     * @return the value of pgmr.unitalocali.cdunil_m
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCdunil_m() {
        return cdunil_m;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.cdunil_m
     *
     * @param cdunil_m the value for pgmr.unitalocali.cdunil_m
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCdunil_m(String cdunil_m) {
        this.cdunil_m = cdunil_m == null ? null : cdunil_m.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.dsunil
     *
     * @return the value of pgmr.unitalocali.dsunil
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getDsunil() {
        return dsunil;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.dsunil
     *
     * @param dsunil the value for pgmr.unitalocali.dsunil
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setDsunil(String dsunil) {
        this.dsunil = dsunil == null ? null : dsunil.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.dtfval
     *
     * @return the value of pgmr.unitalocali.dtfval
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public Date getDtfval() {
        return dtfval;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.dtfval
     *
     * @param dtfval the value for pgmr.unitalocali.dtfval
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setDtfval(Date dtfval) {
        this.dtfval = dtfval;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.indiri
     *
     * @return the value of pgmr.unitalocali.indiri
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getIndiri() {
        return indiri;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.indiri
     *
     * @param indiri the value for pgmr.unitalocali.indiri
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setIndiri(String indiri) {
        this.indiri = indiri == null ? null : indiri.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.cap
     *
     * @return the value of pgmr.unitalocali.cap
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCap() {
        return cap;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.cap
     *
     * @param cap the value for pgmr.unitalocali.cap
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCap(String cap) {
        this.cap = cap == null ? null : cap.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.comune
     *
     * @return the value of pgmr.unitalocali.comune
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getComune() {
        return comune;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.comune
     *
     * @param comune the value for pgmr.unitalocali.comune
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setComune(String comune) {
        this.comune = comune == null ? null : comune.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.cdprov
     *
     * @return the value of pgmr.unitalocali.cdprov
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCdprov() {
        return cdprov;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.cdprov
     *
     * @param cdprov the value for pgmr.unitalocali.cdprov
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCdprov(String cdprov) {
        this.cdprov = cdprov == null ? null : cdprov.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.cdnazi
     *
     * @return the value of pgmr.unitalocali.cdnazi
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCdnazi() {
        return cdnazi;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.cdnazi
     *
     * @param cdnazi the value for pgmr.unitalocali.cdnazi
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCdnazi(String cdnazi) {
        this.cdnazi = cdnazi == null ? null : cdnazi.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.ntelef
     *
     * @return the value of pgmr.unitalocali.ntelef
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getNtelef() {
        return ntelef;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.ntelef
     *
     * @param ntelef the value for pgmr.unitalocali.ntelef
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setNtelef(String ntelef) {
        this.ntelef = ntelef == null ? null : ntelef.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.nfaxsi
     *
     * @return the value of pgmr.unitalocali.nfaxsi
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getNfaxsi() {
        return nfaxsi;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.nfaxsi
     *
     * @param nfaxsi the value for pgmr.unitalocali.nfaxsi
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setNfaxsi(String nfaxsi) {
        this.nfaxsi = nfaxsi == null ? null : nfaxsi.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.email
     *
     * @return the value of pgmr.unitalocali.email
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.email
     *
     * @param email the value for pgmr.unitalocali.email
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.wwwpage
     *
     * @return the value of pgmr.unitalocali.wwwpage
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getWwwpage() {
        return wwwpage;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.wwwpage
     *
     * @param wwwpage the value for pgmr.unitalocali.wwwpage
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setWwwpage(String wwwpage) {
        this.wwwpage = wwwpage == null ? null : wwwpage.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.cdzone
     *
     * @return the value of pgmr.unitalocali.cdzone
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCdzone() {
        return cdzone;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.cdzone
     *
     * @param cdzone the value for pgmr.unitalocali.cdzone
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCdzone(String cdzone) {
        this.cdzone = cdzone == null ? null : cdzone.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.cdagen
     *
     * @return the value of pgmr.unitalocali.cdagen
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCdagen() {
        return cdagen;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.cdagen
     *
     * @param cdagen the value for pgmr.unitalocali.cdagen
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCdagen(String cdagen) {
        this.cdagen = cdagen == null ? null : cdagen.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.cdzcom
     *
     * @return the value of pgmr.unitalocali.cdzcom
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCdzcom() {
        return cdzcom;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.cdzcom
     *
     * @param cdzcom the value for pgmr.unitalocali.cdzcom
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCdzcom(String cdzcom) {
        this.cdzcom = cdzcom == null ? null : cdzcom.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.codfao
     *
     * @return the value of pgmr.unitalocali.codfao
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCodfao() {
        return codfao;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.codfao
     *
     * @param codfao the value for pgmr.unitalocali.codfao
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCodfao(String codfao) {
        this.codfao = codfao == null ? null : codfao.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.qcodfao
     *
     * @return the value of pgmr.unitalocali.qcodfao
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getQcodfao() {
        return qcodfao;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.qcodfao
     *
     * @param qcodfao the value for pgmr.unitalocali.qcodfao
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setQcodfao(String qcodfao) {
        this.qcodfao = qcodfao == null ? null : qcodfao.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.cdtaut
     *
     * @return the value of pgmr.unitalocali.cdtaut
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getCdtaut() {
        return cdtaut;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.cdtaut
     *
     * @param cdtaut the value for pgmr.unitalocali.cdtaut
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setCdtaut(String cdtaut) {
        this.cdtaut = cdtaut == null ? null : cdtaut.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.unitalocali.fg_agg
     *
     * @return the value of pgmr.unitalocali.fg_agg
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public String getFg_agg() {
        return fg_agg;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.unitalocali.fg_agg
     *
     * @param fg_agg the value for pgmr.unitalocali.fg_agg
     *
     * @ibatorgenerated Fri Jun 04 18:39:31 CEST 2010
     */
    public void setFg_agg(String fg_agg) {
        this.fg_agg = fg_agg == null ? null : fg_agg.trim();
    }
}