package com.ateikon.internet.eprogen.domain.pgmr;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UtentiExample {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    public UtentiExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    protected UtentiExample(UtentiExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.utenti
     *
     * @ibatorgenerated Wed May 27 11:42:59 CEST 2009
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andTkutenteIsNull() {
            addCriterion("tkutente is null");
            return this;
        }

        public Criteria andTkutenteIsNotNull() {
            addCriterion("tkutente is not null");
            return this;
        }

        public Criteria andTkutenteEqualTo(Long value) {
            addCriterion("tkutente =", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteNotEqualTo(Long value) {
            addCriterion("tkutente <>", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteGreaterThan(Long value) {
            addCriterion("tkutente >", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteGreaterThanOrEqualTo(Long value) {
            addCriterion("tkutente >=", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteLessThan(Long value) {
            addCriterion("tkutente <", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteLessThanOrEqualTo(Long value) {
            addCriterion("tkutente <=", value, "tkutente");
            return this;
        }

        public Criteria andTkutenteIn(List<Long> values) {
            addCriterion("tkutente in", values, "tkutente");
            return this;
        }

        public Criteria andTkutenteNotIn(List<Long> values) {
            addCriterion("tkutente not in", values, "tkutente");
            return this;
        }

        public Criteria andTkutenteBetween(Long value1, Long value2) {
            addCriterion("tkutente between", value1, value2, "tkutente");
            return this;
        }

        public Criteria andTkutenteNotBetween(Long value1, Long value2) {
            addCriterion("tkutente not between", value1, value2, "tkutente");
            return this;
        }

        public Criteria andCdutenteIsNull() {
            addCriterion("cdutente is null");
            return this;
        }

        public Criteria andCdutenteIsNotNull() {
            addCriterion("cdutente is not null");
            return this;
        }

        public Criteria andCdutenteEqualTo(Long value) {
            addCriterion("cdutente =", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteNotEqualTo(Long value) {
            addCriterion("cdutente <>", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteGreaterThan(Long value) {
            addCriterion("cdutente >", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteGreaterThanOrEqualTo(Long value) {
            addCriterion("cdutente >=", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteLessThan(Long value) {
            addCriterion("cdutente <", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteLessThanOrEqualTo(Long value) {
            addCriterion("cdutente <=", value, "cdutente");
            return this;
        }

        public Criteria andCdutenteIn(List<Long> values) {
            addCriterion("cdutente in", values, "cdutente");
            return this;
        }

        public Criteria andCdutenteNotIn(List<Long> values) {
            addCriterion("cdutente not in", values, "cdutente");
            return this;
        }

        public Criteria andCdutenteBetween(Long value1, Long value2) {
            addCriterion("cdutente between", value1, value2, "cdutente");
            return this;
        }

        public Criteria andCdutenteNotBetween(Long value1, Long value2) {
            addCriterion("cdutente not between", value1, value2, "cdutente");
            return this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return this;
        }

        public Criteria andCdagenteIsNull() {
            addCriterion("cdagente is null");
            return this;
        }

        public Criteria andCdagenteIsNotNull() {
            addCriterion("cdagente is not null");
            return this;
        }

        public Criteria andCdagenteEqualTo(String value) {
            addCriterion("cdagente =", value, "cdagente");
            return this;
        }

        public Criteria andCdagenteNotEqualTo(String value) {
            addCriterion("cdagente <>", value, "cdagente");
            return this;
        }

        public Criteria andCdagenteGreaterThan(String value) {
            addCriterion("cdagente >", value, "cdagente");
            return this;
        }

        public Criteria andCdagenteGreaterThanOrEqualTo(String value) {
            addCriterion("cdagente >=", value, "cdagente");
            return this;
        }

        public Criteria andCdagenteLessThan(String value) {
            addCriterion("cdagente <", value, "cdagente");
            return this;
        }

        public Criteria andCdagenteLessThanOrEqualTo(String value) {
            addCriterion("cdagente <=", value, "cdagente");
            return this;
        }

        public Criteria andCdagenteLike(String value) {
            addCriterion("cdagente like", value, "cdagente");
            return this;
        }

        public Criteria andCdagenteNotLike(String value) {
            addCriterion("cdagente not like", value, "cdagente");
            return this;
        }

        public Criteria andCdagenteIn(List<String> values) {
            addCriterion("cdagente in", values, "cdagente");
            return this;
        }

        public Criteria andCdagenteNotIn(List<String> values) {
            addCriterion("cdagente not in", values, "cdagente");
            return this;
        }

        public Criteria andCdagenteBetween(String value1, String value2) {
            addCriterion("cdagente between", value1, value2, "cdagente");
            return this;
        }

        public Criteria andCdagenteNotBetween(String value1, String value2) {
            addCriterion("cdagente not between", value1, value2, "cdagente");
            return this;
        }

        public Criteria andCdclienteIsNull() {
            addCriterion("cdcliente is null");
            return this;
        }

        public Criteria andCdclienteIsNotNull() {
            addCriterion("cdcliente is not null");
            return this;
        }

        public Criteria andCdclienteEqualTo(String value) {
            addCriterion("cdcliente =", value, "cdcliente");
            return this;
        }

        public Criteria andCdclienteNotEqualTo(String value) {
            addCriterion("cdcliente <>", value, "cdcliente");
            return this;
        }

        public Criteria andCdclienteGreaterThan(String value) {
            addCriterion("cdcliente >", value, "cdcliente");
            return this;
        }

        public Criteria andCdclienteGreaterThanOrEqualTo(String value) {
            addCriterion("cdcliente >=", value, "cdcliente");
            return this;
        }

        public Criteria andCdclienteLessThan(String value) {
            addCriterion("cdcliente <", value, "cdcliente");
            return this;
        }

        public Criteria andCdclienteLessThanOrEqualTo(String value) {
            addCriterion("cdcliente <=", value, "cdcliente");
            return this;
        }

        public Criteria andCdclienteLike(String value) {
            addCriterion("cdcliente like", value, "cdcliente");
            return this;
        }

        public Criteria andCdclienteNotLike(String value) {
            addCriterion("cdcliente not like", value, "cdcliente");
            return this;
        }

        public Criteria andCdclienteIn(List<String> values) {
            addCriterion("cdcliente in", values, "cdcliente");
            return this;
        }

        public Criteria andCdclienteNotIn(List<String> values) {
            addCriterion("cdcliente not in", values, "cdcliente");
            return this;
        }

        public Criteria andCdclienteBetween(String value1, String value2) {
            addCriterion("cdcliente between", value1, value2, "cdcliente");
            return this;
        }

        public Criteria andCdclienteNotBetween(String value1, String value2) {
            addCriterion("cdcliente not between", value1, value2, "cdcliente");
            return this;
        }

        public Criteria andDtbloccoIsNull() {
            addCriterion("dtblocco is null");
            return this;
        }

        public Criteria andDtbloccoIsNotNull() {
            addCriterion("dtblocco is not null");
            return this;
        }

        public Criteria andDtbloccoEqualTo(Date value) {
            addCriterion("dtblocco =", value, "dtblocco");
            return this;
        }

        public Criteria andDtbloccoNotEqualTo(Date value) {
            addCriterion("dtblocco <>", value, "dtblocco");
            return this;
        }

        public Criteria andDtbloccoGreaterThan(Date value) {
            addCriterion("dtblocco >", value, "dtblocco");
            return this;
        }

        public Criteria andDtbloccoGreaterThanOrEqualTo(Date value) {
            addCriterion("dtblocco >=", value, "dtblocco");
            return this;
        }

        public Criteria andDtbloccoLessThan(Date value) {
            addCriterion("dtblocco <", value, "dtblocco");
            return this;
        }

        public Criteria andDtbloccoLessThanOrEqualTo(Date value) {
            addCriterion("dtblocco <=", value, "dtblocco");
            return this;
        }

        public Criteria andDtbloccoIn(List<Date> values) {
            addCriterion("dtblocco in", values, "dtblocco");
            return this;
        }

        public Criteria andDtbloccoNotIn(List<Date> values) {
            addCriterion("dtblocco not in", values, "dtblocco");
            return this;
        }

        public Criteria andDtbloccoBetween(Date value1, Date value2) {
            addCriterion("dtblocco between", value1, value2, "dtblocco");
            return this;
        }

        public Criteria andDtbloccoNotBetween(Date value1, Date value2) {
            addCriterion("dtblocco not between", value1, value2, "dtblocco");
            return this;
        }

        public Criteria andFgbloccoIsNull() {
            addCriterion("fgblocco is null");
            return this;
        }

        public Criteria andFgbloccoIsNotNull() {
            addCriterion("fgblocco is not null");
            return this;
        }

        public Criteria andFgbloccoEqualTo(String value) {
            addCriterion("fgblocco =", value, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoNotEqualTo(String value) {
            addCriterion("fgblocco <>", value, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoGreaterThan(String value) {
            addCriterion("fgblocco >", value, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoGreaterThanOrEqualTo(String value) {
            addCriterion("fgblocco >=", value, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoLessThan(String value) {
            addCriterion("fgblocco <", value, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoLessThanOrEqualTo(String value) {
            addCriterion("fgblocco <=", value, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoLike(String value) {
            addCriterion("fgblocco like", value, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoNotLike(String value) {
            addCriterion("fgblocco not like", value, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoIn(List<String> values) {
            addCriterion("fgblocco in", values, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoNotIn(List<String> values) {
            addCriterion("fgblocco not in", values, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoBetween(String value1, String value2) {
            addCriterion("fgblocco between", value1, value2, "fgblocco");
            return this;
        }

        public Criteria andFgbloccoNotBetween(String value1, String value2) {
            addCriterion("fgblocco not between", value1, value2, "fgblocco");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return this;
        }

        public Criteria andIndirizzoIsNull() {
            addCriterion("indirizzo is null");
            return this;
        }

        public Criteria andIndirizzoIsNotNull() {
            addCriterion("indirizzo is not null");
            return this;
        }

        public Criteria andIndirizzoEqualTo(String value) {
            addCriterion("indirizzo =", value, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoNotEqualTo(String value) {
            addCriterion("indirizzo <>", value, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoGreaterThan(String value) {
            addCriterion("indirizzo >", value, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoGreaterThanOrEqualTo(String value) {
            addCriterion("indirizzo >=", value, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoLessThan(String value) {
            addCriterion("indirizzo <", value, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoLessThanOrEqualTo(String value) {
            addCriterion("indirizzo <=", value, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoLike(String value) {
            addCriterion("indirizzo like", value, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoNotLike(String value) {
            addCriterion("indirizzo not like", value, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoIn(List<String> values) {
            addCriterion("indirizzo in", values, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoNotIn(List<String> values) {
            addCriterion("indirizzo not in", values, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoBetween(String value1, String value2) {
            addCriterion("indirizzo between", value1, value2, "indirizzo");
            return this;
        }

        public Criteria andIndirizzoNotBetween(String value1, String value2) {
            addCriterion("indirizzo not between", value1, value2, "indirizzo");
            return this;
        }

        public Criteria andCapIsNull() {
            addCriterion("cap is null");
            return this;
        }

        public Criteria andCapIsNotNull() {
            addCriterion("cap is not null");
            return this;
        }

        public Criteria andCapEqualTo(String value) {
            addCriterion("cap =", value, "cap");
            return this;
        }

        public Criteria andCapNotEqualTo(String value) {
            addCriterion("cap <>", value, "cap");
            return this;
        }

        public Criteria andCapGreaterThan(String value) {
            addCriterion("cap >", value, "cap");
            return this;
        }

        public Criteria andCapGreaterThanOrEqualTo(String value) {
            addCriterion("cap >=", value, "cap");
            return this;
        }

        public Criteria andCapLessThan(String value) {
            addCriterion("cap <", value, "cap");
            return this;
        }

        public Criteria andCapLessThanOrEqualTo(String value) {
            addCriterion("cap <=", value, "cap");
            return this;
        }

        public Criteria andCapLike(String value) {
            addCriterion("cap like", value, "cap");
            return this;
        }

        public Criteria andCapNotLike(String value) {
            addCriterion("cap not like", value, "cap");
            return this;
        }

        public Criteria andCapIn(List<String> values) {
            addCriterion("cap in", values, "cap");
            return this;
        }

        public Criteria andCapNotIn(List<String> values) {
            addCriterion("cap not in", values, "cap");
            return this;
        }

        public Criteria andCapBetween(String value1, String value2) {
            addCriterion("cap between", value1, value2, "cap");
            return this;
        }

        public Criteria andCapNotBetween(String value1, String value2) {
            addCriterion("cap not between", value1, value2, "cap");
            return this;
        }

        public Criteria andComuneIsNull() {
            addCriterion("comune is null");
            return this;
        }

        public Criteria andComuneIsNotNull() {
            addCriterion("comune is not null");
            return this;
        }

        public Criteria andComuneEqualTo(String value) {
            addCriterion("comune =", value, "comune");
            return this;
        }

        public Criteria andComuneNotEqualTo(String value) {
            addCriterion("comune <>", value, "comune");
            return this;
        }

        public Criteria andComuneGreaterThan(String value) {
            addCriterion("comune >", value, "comune");
            return this;
        }

        public Criteria andComuneGreaterThanOrEqualTo(String value) {
            addCriterion("comune >=", value, "comune");
            return this;
        }

        public Criteria andComuneLessThan(String value) {
            addCriterion("comune <", value, "comune");
            return this;
        }

        public Criteria andComuneLessThanOrEqualTo(String value) {
            addCriterion("comune <=", value, "comune");
            return this;
        }

        public Criteria andComuneLike(String value) {
            addCriterion("comune like", value, "comune");
            return this;
        }

        public Criteria andComuneNotLike(String value) {
            addCriterion("comune not like", value, "comune");
            return this;
        }

        public Criteria andComuneIn(List<String> values) {
            addCriterion("comune in", values, "comune");
            return this;
        }

        public Criteria andComuneNotIn(List<String> values) {
            addCriterion("comune not in", values, "comune");
            return this;
        }

        public Criteria andComuneBetween(String value1, String value2) {
            addCriterion("comune between", value1, value2, "comune");
            return this;
        }

        public Criteria andComuneNotBetween(String value1, String value2) {
            addCriterion("comune not between", value1, value2, "comune");
            return this;
        }

        public Criteria andProvinciaIsNull() {
            addCriterion("provincia is null");
            return this;
        }

        public Criteria andProvinciaIsNotNull() {
            addCriterion("provincia is not null");
            return this;
        }

        public Criteria andProvinciaEqualTo(String value) {
            addCriterion("provincia =", value, "provincia");
            return this;
        }

        public Criteria andProvinciaNotEqualTo(String value) {
            addCriterion("provincia <>", value, "provincia");
            return this;
        }

        public Criteria andProvinciaGreaterThan(String value) {
            addCriterion("provincia >", value, "provincia");
            return this;
        }

        public Criteria andProvinciaGreaterThanOrEqualTo(String value) {
            addCriterion("provincia >=", value, "provincia");
            return this;
        }

        public Criteria andProvinciaLessThan(String value) {
            addCriterion("provincia <", value, "provincia");
            return this;
        }

        public Criteria andProvinciaLessThanOrEqualTo(String value) {
            addCriterion("provincia <=", value, "provincia");
            return this;
        }

        public Criteria andProvinciaLike(String value) {
            addCriterion("provincia like", value, "provincia");
            return this;
        }

        public Criteria andProvinciaNotLike(String value) {
            addCriterion("provincia not like", value, "provincia");
            return this;
        }

        public Criteria andProvinciaIn(List<String> values) {
            addCriterion("provincia in", values, "provincia");
            return this;
        }

        public Criteria andProvinciaNotIn(List<String> values) {
            addCriterion("provincia not in", values, "provincia");
            return this;
        }

        public Criteria andProvinciaBetween(String value1, String value2) {
            addCriterion("provincia between", value1, value2, "provincia");
            return this;
        }

        public Criteria andProvinciaNotBetween(String value1, String value2) {
            addCriterion("provincia not between", value1, value2, "provincia");
            return this;
        }

        public Criteria andNazioneIsNull() {
            addCriterion("nazione is null");
            return this;
        }

        public Criteria andNazioneIsNotNull() {
            addCriterion("nazione is not null");
            return this;
        }

        public Criteria andNazioneEqualTo(String value) {
            addCriterion("nazione =", value, "nazione");
            return this;
        }

        public Criteria andNazioneNotEqualTo(String value) {
            addCriterion("nazione <>", value, "nazione");
            return this;
        }

        public Criteria andNazioneGreaterThan(String value) {
            addCriterion("nazione >", value, "nazione");
            return this;
        }

        public Criteria andNazioneGreaterThanOrEqualTo(String value) {
            addCriterion("nazione >=", value, "nazione");
            return this;
        }

        public Criteria andNazioneLessThan(String value) {
            addCriterion("nazione <", value, "nazione");
            return this;
        }

        public Criteria andNazioneLessThanOrEqualTo(String value) {
            addCriterion("nazione <=", value, "nazione");
            return this;
        }

        public Criteria andNazioneLike(String value) {
            addCriterion("nazione like", value, "nazione");
            return this;
        }

        public Criteria andNazioneNotLike(String value) {
            addCriterion("nazione not like", value, "nazione");
            return this;
        }

        public Criteria andNazioneIn(List<String> values) {
            addCriterion("nazione in", values, "nazione");
            return this;
        }

        public Criteria andNazioneNotIn(List<String> values) {
            addCriterion("nazione not in", values, "nazione");
            return this;
        }

        public Criteria andNazioneBetween(String value1, String value2) {
            addCriterion("nazione between", value1, value2, "nazione");
            return this;
        }

        public Criteria andNazioneNotBetween(String value1, String value2) {
            addCriterion("nazione not between", value1, value2, "nazione");
            return this;
        }

        public Criteria andTelefonoIsNull() {
            addCriterion("telefono is null");
            return this;
        }

        public Criteria andTelefonoIsNotNull() {
            addCriterion("telefono is not null");
            return this;
        }

        public Criteria andTelefonoEqualTo(String value) {
            addCriterion("telefono =", value, "telefono");
            return this;
        }

        public Criteria andTelefonoNotEqualTo(String value) {
            addCriterion("telefono <>", value, "telefono");
            return this;
        }

        public Criteria andTelefonoGreaterThan(String value) {
            addCriterion("telefono >", value, "telefono");
            return this;
        }

        public Criteria andTelefonoGreaterThanOrEqualTo(String value) {
            addCriterion("telefono >=", value, "telefono");
            return this;
        }

        public Criteria andTelefonoLessThan(String value) {
            addCriterion("telefono <", value, "telefono");
            return this;
        }

        public Criteria andTelefonoLessThanOrEqualTo(String value) {
            addCriterion("telefono <=", value, "telefono");
            return this;
        }

        public Criteria andTelefonoLike(String value) {
            addCriterion("telefono like", value, "telefono");
            return this;
        }

        public Criteria andTelefonoNotLike(String value) {
            addCriterion("telefono not like", value, "telefono");
            return this;
        }

        public Criteria andTelefonoIn(List<String> values) {
            addCriterion("telefono in", values, "telefono");
            return this;
        }

        public Criteria andTelefonoNotIn(List<String> values) {
            addCriterion("telefono not in", values, "telefono");
            return this;
        }

        public Criteria andTelefonoBetween(String value1, String value2) {
            addCriterion("telefono between", value1, value2, "telefono");
            return this;
        }

        public Criteria andTelefonoNotBetween(String value1, String value2) {
            addCriterion("telefono not between", value1, value2, "telefono");
            return this;
        }

        public Criteria andFaxIsNull() {
            addCriterion("fax is null");
            return this;
        }

        public Criteria andFaxIsNotNull() {
            addCriterion("fax is not null");
            return this;
        }

        public Criteria andFaxEqualTo(String value) {
            addCriterion("fax =", value, "fax");
            return this;
        }

        public Criteria andFaxNotEqualTo(String value) {
            addCriterion("fax <>", value, "fax");
            return this;
        }

        public Criteria andFaxGreaterThan(String value) {
            addCriterion("fax >", value, "fax");
            return this;
        }

        public Criteria andFaxGreaterThanOrEqualTo(String value) {
            addCriterion("fax >=", value, "fax");
            return this;
        }

        public Criteria andFaxLessThan(String value) {
            addCriterion("fax <", value, "fax");
            return this;
        }

        public Criteria andFaxLessThanOrEqualTo(String value) {
            addCriterion("fax <=", value, "fax");
            return this;
        }

        public Criteria andFaxLike(String value) {
            addCriterion("fax like", value, "fax");
            return this;
        }

        public Criteria andFaxNotLike(String value) {
            addCriterion("fax not like", value, "fax");
            return this;
        }

        public Criteria andFaxIn(List<String> values) {
            addCriterion("fax in", values, "fax");
            return this;
        }

        public Criteria andFaxNotIn(List<String> values) {
            addCriterion("fax not in", values, "fax");
            return this;
        }

        public Criteria andFaxBetween(String value1, String value2) {
            addCriterion("fax between", value1, value2, "fax");
            return this;
        }

        public Criteria andFaxNotBetween(String value1, String value2) {
            addCriterion("fax not between", value1, value2, "fax");
            return this;
        }

        public Criteria andCellulareIsNull() {
            addCriterion("cellulare is null");
            return this;
        }

        public Criteria andCellulareIsNotNull() {
            addCriterion("cellulare is not null");
            return this;
        }

        public Criteria andCellulareEqualTo(String value) {
            addCriterion("cellulare =", value, "cellulare");
            return this;
        }

        public Criteria andCellulareNotEqualTo(String value) {
            addCriterion("cellulare <>", value, "cellulare");
            return this;
        }

        public Criteria andCellulareGreaterThan(String value) {
            addCriterion("cellulare >", value, "cellulare");
            return this;
        }

        public Criteria andCellulareGreaterThanOrEqualTo(String value) {
            addCriterion("cellulare >=", value, "cellulare");
            return this;
        }

        public Criteria andCellulareLessThan(String value) {
            addCriterion("cellulare <", value, "cellulare");
            return this;
        }

        public Criteria andCellulareLessThanOrEqualTo(String value) {
            addCriterion("cellulare <=", value, "cellulare");
            return this;
        }

        public Criteria andCellulareLike(String value) {
            addCriterion("cellulare like", value, "cellulare");
            return this;
        }

        public Criteria andCellulareNotLike(String value) {
            addCriterion("cellulare not like", value, "cellulare");
            return this;
        }

        public Criteria andCellulareIn(List<String> values) {
            addCriterion("cellulare in", values, "cellulare");
            return this;
        }

        public Criteria andCellulareNotIn(List<String> values) {
            addCriterion("cellulare not in", values, "cellulare");
            return this;
        }

        public Criteria andCellulareBetween(String value1, String value2) {
            addCriterion("cellulare between", value1, value2, "cellulare");
            return this;
        }

        public Criteria andCellulareNotBetween(String value1, String value2) {
            addCriterion("cellulare not between", value1, value2, "cellulare");
            return this;
        }

        public Criteria andSkypeidIsNull() {
            addCriterion("skypeid is null");
            return this;
        }

        public Criteria andSkypeidIsNotNull() {
            addCriterion("skypeid is not null");
            return this;
        }

        public Criteria andSkypeidEqualTo(String value) {
            addCriterion("skypeid =", value, "skypeid");
            return this;
        }

        public Criteria andSkypeidNotEqualTo(String value) {
            addCriterion("skypeid <>", value, "skypeid");
            return this;
        }

        public Criteria andSkypeidGreaterThan(String value) {
            addCriterion("skypeid >", value, "skypeid");
            return this;
        }

        public Criteria andSkypeidGreaterThanOrEqualTo(String value) {
            addCriterion("skypeid >=", value, "skypeid");
            return this;
        }

        public Criteria andSkypeidLessThan(String value) {
            addCriterion("skypeid <", value, "skypeid");
            return this;
        }

        public Criteria andSkypeidLessThanOrEqualTo(String value) {
            addCriterion("skypeid <=", value, "skypeid");
            return this;
        }

        public Criteria andSkypeidLike(String value) {
            addCriterion("skypeid like", value, "skypeid");
            return this;
        }

        public Criteria andSkypeidNotLike(String value) {
            addCriterion("skypeid not like", value, "skypeid");
            return this;
        }

        public Criteria andSkypeidIn(List<String> values) {
            addCriterion("skypeid in", values, "skypeid");
            return this;
        }

        public Criteria andSkypeidNotIn(List<String> values) {
            addCriterion("skypeid not in", values, "skypeid");
            return this;
        }

        public Criteria andSkypeidBetween(String value1, String value2) {
            addCriterion("skypeid between", value1, value2, "skypeid");
            return this;
        }

        public Criteria andSkypeidNotBetween(String value1, String value2) {
            addCriterion("skypeid not between", value1, value2, "skypeid");
            return this;
        }

        public Criteria andCdgruppoIsNull() {
            addCriterion("cdgruppo is null");
            return this;
        }

        public Criteria andCdgruppoIsNotNull() {
            addCriterion("cdgruppo is not null");
            return this;
        }

        public Criteria andCdgruppoEqualTo(String value) {
            addCriterion("cdgruppo =", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoNotEqualTo(String value) {
            addCriterion("cdgruppo <>", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoGreaterThan(String value) {
            addCriterion("cdgruppo >", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoGreaterThanOrEqualTo(String value) {
            addCriterion("cdgruppo >=", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoLessThan(String value) {
            addCriterion("cdgruppo <", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoLessThanOrEqualTo(String value) {
            addCriterion("cdgruppo <=", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoLike(String value) {
            addCriterion("cdgruppo like", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoNotLike(String value) {
            addCriterion("cdgruppo not like", value, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoIn(List<String> values) {
            addCriterion("cdgruppo in", values, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoNotIn(List<String> values) {
            addCriterion("cdgruppo not in", values, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoBetween(String value1, String value2) {
            addCriterion("cdgruppo between", value1, value2, "cdgruppo");
            return this;
        }

        public Criteria andCdgruppoNotBetween(String value1, String value2) {
            addCriterion("cdgruppo not between", value1, value2, "cdgruppo");
            return this;
        }

        public Criteria andDsutenteIsNull() {
            addCriterion("dsutente is null");
            return this;
        }

        public Criteria andDsutenteIsNotNull() {
            addCriterion("dsutente is not null");
            return this;
        }

        public Criteria andDsutenteEqualTo(String value) {
            addCriterion("dsutente =", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteNotEqualTo(String value) {
            addCriterion("dsutente <>", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteGreaterThan(String value) {
            addCriterion("dsutente >", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteGreaterThanOrEqualTo(String value) {
            addCriterion("dsutente >=", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteLessThan(String value) {
            addCriterion("dsutente <", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteLessThanOrEqualTo(String value) {
            addCriterion("dsutente <=", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteLike(String value) {
            addCriterion("dsutente like", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteNotLike(String value) {
            addCriterion("dsutente not like", value, "dsutente");
            return this;
        }

        public Criteria andDsutenteIn(List<String> values) {
            addCriterion("dsutente in", values, "dsutente");
            return this;
        }

        public Criteria andDsutenteNotIn(List<String> values) {
            addCriterion("dsutente not in", values, "dsutente");
            return this;
        }

        public Criteria andDsutenteBetween(String value1, String value2) {
            addCriterion("dsutente between", value1, value2, "dsutente");
            return this;
        }

        public Criteria andDsutenteNotBetween(String value1, String value2) {
            addCriterion("dsutente not between", value1, value2, "dsutente");
            return this;
        }

        public Criteria andRagsocIsNull() {
            addCriterion("ragsoc is null");
            return this;
        }

        public Criteria andRagsocIsNotNull() {
            addCriterion("ragsoc is not null");
            return this;
        }

        public Criteria andRagsocEqualTo(String value) {
            addCriterion("ragsoc =", value, "ragsoc");
            return this;
        }

        public Criteria andRagsocNotEqualTo(String value) {
            addCriterion("ragsoc <>", value, "ragsoc");
            return this;
        }

        public Criteria andRagsocGreaterThan(String value) {
            addCriterion("ragsoc >", value, "ragsoc");
            return this;
        }

        public Criteria andRagsocGreaterThanOrEqualTo(String value) {
            addCriterion("ragsoc >=", value, "ragsoc");
            return this;
        }

        public Criteria andRagsocLessThan(String value) {
            addCriterion("ragsoc <", value, "ragsoc");
            return this;
        }

        public Criteria andRagsocLessThanOrEqualTo(String value) {
            addCriterion("ragsoc <=", value, "ragsoc");
            return this;
        }

        public Criteria andRagsocLike(String value) {
            addCriterion("ragsoc like", value, "ragsoc");
            return this;
        }

        public Criteria andRagsocNotLike(String value) {
            addCriterion("ragsoc not like", value, "ragsoc");
            return this;
        }

        public Criteria andRagsocIn(List<String> values) {
            addCriterion("ragsoc in", values, "ragsoc");
            return this;
        }

        public Criteria andRagsocNotIn(List<String> values) {
            addCriterion("ragsoc not in", values, "ragsoc");
            return this;
        }

        public Criteria andRagsocBetween(String value1, String value2) {
            addCriterion("ragsoc between", value1, value2, "ragsoc");
            return this;
        }

        public Criteria andRagsocNotBetween(String value1, String value2) {
            addCriterion("ragsoc not between", value1, value2, "ragsoc");
            return this;
        }

        public Criteria andDtultsyncIsNull() {
            addCriterion("dtultsync is null");
            return this;
        }

        public Criteria andDtultsyncIsNotNull() {
            addCriterion("dtultsync is not null");
            return this;
        }

        public Criteria andDtultsyncEqualTo(Date value) {
            addCriterion("dtultsync =", value, "dtultsync");
            return this;
        }

        public Criteria andDtultsyncNotEqualTo(Date value) {
            addCriterion("dtultsync <>", value, "dtultsync");
            return this;
        }

        public Criteria andDtultsyncGreaterThan(Date value) {
            addCriterion("dtultsync >", value, "dtultsync");
            return this;
        }

        public Criteria andDtultsyncGreaterThanOrEqualTo(Date value) {
            addCriterion("dtultsync >=", value, "dtultsync");
            return this;
        }

        public Criteria andDtultsyncLessThan(Date value) {
            addCriterion("dtultsync <", value, "dtultsync");
            return this;
        }

        public Criteria andDtultsyncLessThanOrEqualTo(Date value) {
            addCriterion("dtultsync <=", value, "dtultsync");
            return this;
        }

        public Criteria andDtultsyncIn(List<Date> values) {
            addCriterion("dtultsync in", values, "dtultsync");
            return this;
        }

        public Criteria andDtultsyncNotIn(List<Date> values) {
            addCriterion("dtultsync not in", values, "dtultsync");
            return this;
        }

        public Criteria andDtultsyncBetween(Date value1, Date value2) {
            addCriterion("dtultsync between", value1, value2, "dtultsync");
            return this;
        }

        public Criteria andDtultsyncNotBetween(Date value1, Date value2) {
            addCriterion("dtultsync not between", value1, value2, "dtultsync");
            return this;
        }

        public Criteria andCdprofiloIsNull() {
            addCriterion("cdprofilo is null");
            return this;
        }

        public Criteria andCdprofiloIsNotNull() {
            addCriterion("cdprofilo is not null");
            return this;
        }

        public Criteria andCdprofiloEqualTo(Long value) {
            addCriterion("cdprofilo =", value, "cdprofilo");
            return this;
        }

        public Criteria andCdprofiloNotEqualTo(Long value) {
            addCriterion("cdprofilo <>", value, "cdprofilo");
            return this;
        }

        public Criteria andCdprofiloGreaterThan(Long value) {
            addCriterion("cdprofilo >", value, "cdprofilo");
            return this;
        }

        public Criteria andCdprofiloGreaterThanOrEqualTo(Long value) {
            addCriterion("cdprofilo >=", value, "cdprofilo");
            return this;
        }

        public Criteria andCdprofiloLessThan(Long value) {
            addCriterion("cdprofilo <", value, "cdprofilo");
            return this;
        }

        public Criteria andCdprofiloLessThanOrEqualTo(Long value) {
            addCriterion("cdprofilo <=", value, "cdprofilo");
            return this;
        }

        public Criteria andCdprofiloIn(List<Long> values) {
            addCriterion("cdprofilo in", values, "cdprofilo");
            return this;
        }

        public Criteria andCdprofiloNotIn(List<Long> values) {
            addCriterion("cdprofilo not in", values, "cdprofilo");
            return this;
        }

        public Criteria andCdprofiloBetween(Long value1, Long value2) {
            addCriterion("cdprofilo between", value1, value2, "cdprofilo");
            return this;
        }

        public Criteria andCdprofiloNotBetween(Long value1, Long value2) {
            addCriterion("cdprofilo not between", value1, value2, "cdprofilo");
            return this;
        }

        public Criteria andFg_pubIsNull() {
            addCriterion("fg_pub is null");
            return this;
        }

        public Criteria andFg_pubIsNotNull() {
            addCriterion("fg_pub is not null");
            return this;
        }

        public Criteria andFg_pubEqualTo(String value) {
            addCriterion("fg_pub =", value, "fg_pub");
            return this;
        }

        public Criteria andFg_pubNotEqualTo(String value) {
            addCriterion("fg_pub <>", value, "fg_pub");
            return this;
        }

        public Criteria andFg_pubGreaterThan(String value) {
            addCriterion("fg_pub >", value, "fg_pub");
            return this;
        }

        public Criteria andFg_pubGreaterThanOrEqualTo(String value) {
            addCriterion("fg_pub >=", value, "fg_pub");
            return this;
        }

        public Criteria andFg_pubLessThan(String value) {
            addCriterion("fg_pub <", value, "fg_pub");
            return this;
        }

        public Criteria andFg_pubLessThanOrEqualTo(String value) {
            addCriterion("fg_pub <=", value, "fg_pub");
            return this;
        }

        public Criteria andFg_pubLike(String value) {
            addCriterion("fg_pub like", value, "fg_pub");
            return this;
        }

        public Criteria andFg_pubNotLike(String value) {
            addCriterion("fg_pub not like", value, "fg_pub");
            return this;
        }

        public Criteria andFg_pubIn(List<String> values) {
            addCriterion("fg_pub in", values, "fg_pub");
            return this;
        }

        public Criteria andFg_pubNotIn(List<String> values) {
            addCriterion("fg_pub not in", values, "fg_pub");
            return this;
        }

        public Criteria andFg_pubBetween(String value1, String value2) {
            addCriterion("fg_pub between", value1, value2, "fg_pub");
            return this;
        }

        public Criteria andFg_pubNotBetween(String value1, String value2) {
            addCriterion("fg_pub not between", value1, value2, "fg_pub");
            return this;
        }
    }
}