package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;

public class Vist_etichette extends BaseTableBean {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.cdvistet
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdvistet;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.cdvistet_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdvistet_m;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.dsvistet
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistet;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.potenza
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String potenza;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.potenza1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String potenza1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.potenza2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String potenza2;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.potenza3
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String potenza3;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.potenza4
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String potenza4;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo1_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo1_1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo2_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo2_1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo3_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo3_1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo4_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo4_1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo5_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo5_1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo6_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo6_1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo1_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo1_2;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo2_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo2_2;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo3_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo3_2;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo4_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo4_2;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo5_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo5_2;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.simbolo6_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String simbolo6_2;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String fg_agg;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.dsvistet_en
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistet_en;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.dsvistet_de
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistet_de;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.dsvistet_fr
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistet_fr;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.dsvistet_es
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistet_es;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_etichette.dsvistet_ru
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistet_ru;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.cdvistet
     *
     * @return the value of pgmr.vist_etichette.cdvistet
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdvistet() {
        return cdvistet;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.cdvistet
     *
     * @param cdvistet the value for pgmr.vist_etichette.cdvistet
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdvistet(String cdvistet) {
        this.cdvistet = cdvistet == null ? null : cdvistet.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.cdvistet_m
     *
     * @return the value of pgmr.vist_etichette.cdvistet_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdvistet_m() {
        return cdvistet_m;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.cdvistet_m
     *
     * @param cdvistet_m the value for pgmr.vist_etichette.cdvistet_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdvistet_m(String cdvistet_m) {
        this.cdvistet_m = cdvistet_m == null ? null : cdvistet_m.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.dsvistet
     *
     * @return the value of pgmr.vist_etichette.dsvistet
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistet() {
        return dsvistet;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.dsvistet
     *
     * @param dsvistet the value for pgmr.vist_etichette.dsvistet
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistet(String dsvistet) {
        this.dsvistet = dsvistet == null ? null : dsvistet.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.potenza
     *
     * @return the value of pgmr.vist_etichette.potenza
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getPotenza() {
        return potenza;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.potenza
     *
     * @param potenza the value for pgmr.vist_etichette.potenza
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setPotenza(String potenza) {
        this.potenza = potenza == null ? null : potenza.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.potenza1
     *
     * @return the value of pgmr.vist_etichette.potenza1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getPotenza1() {
        return potenza1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.potenza1
     *
     * @param potenza1 the value for pgmr.vist_etichette.potenza1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setPotenza1(String potenza1) {
        this.potenza1 = potenza1 == null ? null : potenza1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.potenza2
     *
     * @return the value of pgmr.vist_etichette.potenza2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getPotenza2() {
        return potenza2;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.potenza2
     *
     * @param potenza2 the value for pgmr.vist_etichette.potenza2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setPotenza2(String potenza2) {
        this.potenza2 = potenza2 == null ? null : potenza2.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.potenza3
     *
     * @return the value of pgmr.vist_etichette.potenza3
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getPotenza3() {
        return potenza3;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.potenza3
     *
     * @param potenza3 the value for pgmr.vist_etichette.potenza3
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setPotenza3(String potenza3) {
        this.potenza3 = potenza3 == null ? null : potenza3.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.potenza4
     *
     * @return the value of pgmr.vist_etichette.potenza4
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getPotenza4() {
        return potenza4;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.potenza4
     *
     * @param potenza4 the value for pgmr.vist_etichette.potenza4
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setPotenza4(String potenza4) {
        this.potenza4 = potenza4 == null ? null : potenza4.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo1_1
     *
     * @return the value of pgmr.vist_etichette.simbolo1_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo1_1() {
        return simbolo1_1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo1_1
     *
     * @param simbolo1_1 the value for pgmr.vist_etichette.simbolo1_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo1_1(String simbolo1_1) {
        this.simbolo1_1 = simbolo1_1 == null ? null : simbolo1_1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo2_1
     *
     * @return the value of pgmr.vist_etichette.simbolo2_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo2_1() {
        return simbolo2_1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo2_1
     *
     * @param simbolo2_1 the value for pgmr.vist_etichette.simbolo2_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo2_1(String simbolo2_1) {
        this.simbolo2_1 = simbolo2_1 == null ? null : simbolo2_1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo3_1
     *
     * @return the value of pgmr.vist_etichette.simbolo3_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo3_1() {
        return simbolo3_1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo3_1
     *
     * @param simbolo3_1 the value for pgmr.vist_etichette.simbolo3_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo3_1(String simbolo3_1) {
        this.simbolo3_1 = simbolo3_1 == null ? null : simbolo3_1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo4_1
     *
     * @return the value of pgmr.vist_etichette.simbolo4_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo4_1() {
        return simbolo4_1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo4_1
     *
     * @param simbolo4_1 the value for pgmr.vist_etichette.simbolo4_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo4_1(String simbolo4_1) {
        this.simbolo4_1 = simbolo4_1 == null ? null : simbolo4_1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo5_1
     *
     * @return the value of pgmr.vist_etichette.simbolo5_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo5_1() {
        return simbolo5_1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo5_1
     *
     * @param simbolo5_1 the value for pgmr.vist_etichette.simbolo5_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo5_1(String simbolo5_1) {
        this.simbolo5_1 = simbolo5_1 == null ? null : simbolo5_1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo6_1
     *
     * @return the value of pgmr.vist_etichette.simbolo6_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo6_1() {
        return simbolo6_1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo6_1
     *
     * @param simbolo6_1 the value for pgmr.vist_etichette.simbolo6_1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo6_1(String simbolo6_1) {
        this.simbolo6_1 = simbolo6_1 == null ? null : simbolo6_1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo1_2
     *
     * @return the value of pgmr.vist_etichette.simbolo1_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo1_2() {
        return simbolo1_2;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo1_2
     *
     * @param simbolo1_2 the value for pgmr.vist_etichette.simbolo1_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo1_2(String simbolo1_2) {
        this.simbolo1_2 = simbolo1_2 == null ? null : simbolo1_2.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo2_2
     *
     * @return the value of pgmr.vist_etichette.simbolo2_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo2_2() {
        return simbolo2_2;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo2_2
     *
     * @param simbolo2_2 the value for pgmr.vist_etichette.simbolo2_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo2_2(String simbolo2_2) {
        this.simbolo2_2 = simbolo2_2 == null ? null : simbolo2_2.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo3_2
     *
     * @return the value of pgmr.vist_etichette.simbolo3_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo3_2() {
        return simbolo3_2;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo3_2
     *
     * @param simbolo3_2 the value for pgmr.vist_etichette.simbolo3_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo3_2(String simbolo3_2) {
        this.simbolo3_2 = simbolo3_2 == null ? null : simbolo3_2.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo4_2
     *
     * @return the value of pgmr.vist_etichette.simbolo4_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo4_2() {
        return simbolo4_2;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo4_2
     *
     * @param simbolo4_2 the value for pgmr.vist_etichette.simbolo4_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo4_2(String simbolo4_2) {
        this.simbolo4_2 = simbolo4_2 == null ? null : simbolo4_2.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo5_2
     *
     * @return the value of pgmr.vist_etichette.simbolo5_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo5_2() {
        return simbolo5_2;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo5_2
     *
     * @param simbolo5_2 the value for pgmr.vist_etichette.simbolo5_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo5_2(String simbolo5_2) {
        this.simbolo5_2 = simbolo5_2 == null ? null : simbolo5_2.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.simbolo6_2
     *
     * @return the value of pgmr.vist_etichette.simbolo6_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getSimbolo6_2() {
        return simbolo6_2;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.simbolo6_2
     *
     * @param simbolo6_2 the value for pgmr.vist_etichette.simbolo6_2
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setSimbolo6_2(String simbolo6_2) {
        this.simbolo6_2 = simbolo6_2 == null ? null : simbolo6_2.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.fg_agg
     *
     * @return the value of pgmr.vist_etichette.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getFg_agg() {
        return fg_agg;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.fg_agg
     *
     * @param fg_agg the value for pgmr.vist_etichette.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setFg_agg(String fg_agg) {
        this.fg_agg = fg_agg == null ? null : fg_agg.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.dsvistet_en
     *
     * @return the value of pgmr.vist_etichette.dsvistet_en
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistet_en() {
        return dsvistet_en;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.dsvistet_en
     *
     * @param dsvistet_en the value for pgmr.vist_etichette.dsvistet_en
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistet_en(String dsvistet_en) {
        this.dsvistet_en = dsvistet_en == null ? null : dsvistet_en.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.dsvistet_de
     *
     * @return the value of pgmr.vist_etichette.dsvistet_de
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistet_de() {
        return dsvistet_de;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.dsvistet_de
     *
     * @param dsvistet_de the value for pgmr.vist_etichette.dsvistet_de
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistet_de(String dsvistet_de) {
        this.dsvistet_de = dsvistet_de == null ? null : dsvistet_de.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.dsvistet_fr
     *
     * @return the value of pgmr.vist_etichette.dsvistet_fr
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistet_fr() {
        return dsvistet_fr;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.dsvistet_fr
     *
     * @param dsvistet_fr the value for pgmr.vist_etichette.dsvistet_fr
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistet_fr(String dsvistet_fr) {
        this.dsvistet_fr = dsvistet_fr == null ? null : dsvistet_fr.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.dsvistet_es
     *
     * @return the value of pgmr.vist_etichette.dsvistet_es
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistet_es() {
        return dsvistet_es;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.dsvistet_es
     *
     * @param dsvistet_es the value for pgmr.vist_etichette.dsvistet_es
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistet_es(String dsvistet_es) {
        this.dsvistet_es = dsvistet_es == null ? null : dsvistet_es.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_etichette.dsvistet_ru
     *
     * @return the value of pgmr.vist_etichette.dsvistet_ru
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistet_ru() {
        return dsvistet_ru;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_etichette.dsvistet_ru
     *
     * @param dsvistet_ru the value for pgmr.vist_etichette.dsvistet_ru
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistet_ru(String dsvistet_ru) {
        this.dsvistet_ru = dsvistet_ru == null ? null : dsvistet_ru.trim();
    }
}