package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;

public class Vist_semilavorati extends BaseTableBean {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.cdvistseml
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdvistseml;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.cdvistseml_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdvistseml_m;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsvistseml
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistseml;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsvistseml_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistseml_eng;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsvistseml_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistseml_ted;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsvistseml_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistseml_fra;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsvistseml_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistseml_spa;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String fg_agg;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsextvistseml
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistseml;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsextvistseml_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistseml_eng;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsextvistseml_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistseml_ted;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsextvistseml_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistseml_fra;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsextvistseml_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistseml_spa;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsvistseml_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistseml_rus;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_semilavorati.dsextvistseml_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistseml_rus;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.cdvistseml
     *
     * @return the value of pgmr.vist_semilavorati.cdvistseml
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdvistseml() {
        return cdvistseml;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.cdvistseml
     *
     * @param cdvistseml the value for pgmr.vist_semilavorati.cdvistseml
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdvistseml(String cdvistseml) {
        this.cdvistseml = cdvistseml == null ? null : cdvistseml.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.cdvistseml_m
     *
     * @return the value of pgmr.vist_semilavorati.cdvistseml_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdvistseml_m() {
        return cdvistseml_m;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.cdvistseml_m
     *
     * @param cdvistseml_m the value for pgmr.vist_semilavorati.cdvistseml_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdvistseml_m(String cdvistseml_m) {
        this.cdvistseml_m = cdvistseml_m == null ? null : cdvistseml_m.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsvistseml
     *
     * @return the value of pgmr.vist_semilavorati.dsvistseml
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistseml() {
        return dsvistseml;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsvistseml
     *
     * @param dsvistseml the value for pgmr.vist_semilavorati.dsvistseml
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistseml(String dsvistseml) {
        this.dsvistseml = dsvistseml == null ? null : dsvistseml.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsvistseml_eng
     *
     * @return the value of pgmr.vist_semilavorati.dsvistseml_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistseml_eng() {
        return dsvistseml_eng;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsvistseml_eng
     *
     * @param dsvistseml_eng the value for pgmr.vist_semilavorati.dsvistseml_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistseml_eng(String dsvistseml_eng) {
        this.dsvistseml_eng = dsvistseml_eng == null ? null : dsvistseml_eng.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsvistseml_ted
     *
     * @return the value of pgmr.vist_semilavorati.dsvistseml_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistseml_ted() {
        return dsvistseml_ted;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsvistseml_ted
     *
     * @param dsvistseml_ted the value for pgmr.vist_semilavorati.dsvistseml_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistseml_ted(String dsvistseml_ted) {
        this.dsvistseml_ted = dsvistseml_ted == null ? null : dsvistseml_ted.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsvistseml_fra
     *
     * @return the value of pgmr.vist_semilavorati.dsvistseml_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistseml_fra() {
        return dsvistseml_fra;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsvistseml_fra
     *
     * @param dsvistseml_fra the value for pgmr.vist_semilavorati.dsvistseml_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistseml_fra(String dsvistseml_fra) {
        this.dsvistseml_fra = dsvistseml_fra == null ? null : dsvistseml_fra.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsvistseml_spa
     *
     * @return the value of pgmr.vist_semilavorati.dsvistseml_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistseml_spa() {
        return dsvistseml_spa;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsvistseml_spa
     *
     * @param dsvistseml_spa the value for pgmr.vist_semilavorati.dsvistseml_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistseml_spa(String dsvistseml_spa) {
        this.dsvistseml_spa = dsvistseml_spa == null ? null : dsvistseml_spa.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.fg_agg
     *
     * @return the value of pgmr.vist_semilavorati.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getFg_agg() {
        return fg_agg;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.fg_agg
     *
     * @param fg_agg the value for pgmr.vist_semilavorati.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setFg_agg(String fg_agg) {
        this.fg_agg = fg_agg == null ? null : fg_agg.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsextvistseml
     *
     * @return the value of pgmr.vist_semilavorati.dsextvistseml
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistseml() {
        return dsextvistseml;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsextvistseml
     *
     * @param dsextvistseml the value for pgmr.vist_semilavorati.dsextvistseml
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistseml(String dsextvistseml) {
        this.dsextvistseml = dsextvistseml == null ? null : dsextvistseml.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsextvistseml_eng
     *
     * @return the value of pgmr.vist_semilavorati.dsextvistseml_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistseml_eng() {
        return dsextvistseml_eng;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsextvistseml_eng
     *
     * @param dsextvistseml_eng the value for pgmr.vist_semilavorati.dsextvistseml_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistseml_eng(String dsextvistseml_eng) {
        this.dsextvistseml_eng = dsextvistseml_eng == null ? null : dsextvistseml_eng.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsextvistseml_ted
     *
     * @return the value of pgmr.vist_semilavorati.dsextvistseml_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistseml_ted() {
        return dsextvistseml_ted;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsextvistseml_ted
     *
     * @param dsextvistseml_ted the value for pgmr.vist_semilavorati.dsextvistseml_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistseml_ted(String dsextvistseml_ted) {
        this.dsextvistseml_ted = dsextvistseml_ted == null ? null : dsextvistseml_ted.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsextvistseml_fra
     *
     * @return the value of pgmr.vist_semilavorati.dsextvistseml_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistseml_fra() {
        return dsextvistseml_fra;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsextvistseml_fra
     *
     * @param dsextvistseml_fra the value for pgmr.vist_semilavorati.dsextvistseml_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistseml_fra(String dsextvistseml_fra) {
        this.dsextvistseml_fra = dsextvistseml_fra == null ? null : dsextvistseml_fra.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsextvistseml_spa
     *
     * @return the value of pgmr.vist_semilavorati.dsextvistseml_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistseml_spa() {
        return dsextvistseml_spa;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsextvistseml_spa
     *
     * @param dsextvistseml_spa the value for pgmr.vist_semilavorati.dsextvistseml_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistseml_spa(String dsextvistseml_spa) {
        this.dsextvistseml_spa = dsextvistseml_spa == null ? null : dsextvistseml_spa.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsvistseml_rus
     *
     * @return the value of pgmr.vist_semilavorati.dsvistseml_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistseml_rus() {
        return dsvistseml_rus;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsvistseml_rus
     *
     * @param dsvistseml_rus the value for pgmr.vist_semilavorati.dsvistseml_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistseml_rus(String dsvistseml_rus) {
        this.dsvistseml_rus = dsvistseml_rus == null ? null : dsvistseml_rus.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_semilavorati.dsextvistseml_rus
     *
     * @return the value of pgmr.vist_semilavorati.dsextvistseml_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistseml_rus() {
        return dsextvistseml_rus;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_semilavorati.dsextvistseml_rus
     *
     * @param dsextvistseml_rus the value for pgmr.vist_semilavorati.dsextvistseml_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistseml_rus(String dsextvistseml_rus) {
        this.dsextvistseml_rus = dsextvistseml_rus == null ? null : dsextvistseml_rus.trim();
    }
}