package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;
import org.apache.commons.lang.StringUtils;

public class Vist_var1 extends BaseTableBean {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.cdvistv1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdvistv1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.cdvistv1_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdvistv1_m;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsvistv1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistv1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsvistv1_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistv1_eng;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsvistv1_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistv1_ted;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsvistv1_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistv1_fra;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsvistv1_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistv1_spa;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String fg_agg;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsextvistv1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistv1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsextvistv1_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistv1_eng;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsextvistv1_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistv1_ted;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsextvistv1_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistv1_fra;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsextvistv1_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistv1_spa;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsextvistv1_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvistv1_rus;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_var1.dsvistv1_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvistv1_rus;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.cdvistv1
     *
     * @return the value of pgmr.vist_var1.cdvistv1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdvistv1() {
        return cdvistv1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.cdvistv1
     *
     * @param cdvistv1 the value for pgmr.vist_var1.cdvistv1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdvistv1(String cdvistv1) {
        this.cdvistv1 = cdvistv1 == null ? null : cdvistv1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.cdvistv1_m
     *
     * @return the value of pgmr.vist_var1.cdvistv1_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdvistv1_m() {
        return cdvistv1_m;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.cdvistv1_m
     *
     * @param cdvistv1_m the value for pgmr.vist_var1.cdvistv1_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdvistv1_m(String cdvistv1_m) {
        this.cdvistv1_m = cdvistv1_m == null ? null : cdvistv1_m.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsvistv1
     *
     * @return the value of pgmr.vist_var1.dsvistv1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistv1() {
        return dsvistv1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsvistv1
     *
     * @param dsvistv1 the value for pgmr.vist_var1.dsvistv1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistv1(String dsvistv1) {
        this.dsvistv1 = dsvistv1 == null ? null : dsvistv1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsvistv1_eng
     *
     * @return the value of pgmr.vist_var1.dsvistv1_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistv1_eng() {
        return dsvistv1_eng;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsvistv1_eng
     *
     * @param dsvistv1_eng the value for pgmr.vist_var1.dsvistv1_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistv1_eng(String dsvistv1_eng) {
        this.dsvistv1_eng = dsvistv1_eng == null ? null : dsvistv1_eng.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsvistv1_ted
     *
     * @return the value of pgmr.vist_var1.dsvistv1_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistv1_ted() {
        return dsvistv1_ted;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsvistv1_ted
     *
     * @param dsvistv1_ted the value for pgmr.vist_var1.dsvistv1_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistv1_ted(String dsvistv1_ted) {
        this.dsvistv1_ted = dsvistv1_ted == null ? null : dsvistv1_ted.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsvistv1_fra
     *
     * @return the value of pgmr.vist_var1.dsvistv1_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistv1_fra() {
        return dsvistv1_fra;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsvistv1_fra
     *
     * @param dsvistv1_fra the value for pgmr.vist_var1.dsvistv1_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistv1_fra(String dsvistv1_fra) {
        this.dsvistv1_fra = dsvistv1_fra == null ? null : dsvistv1_fra.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsvistv1_spa
     *
     * @return the value of pgmr.vist_var1.dsvistv1_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistv1_spa() {
        return dsvistv1_spa;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsvistv1_spa
     *
     * @param dsvistv1_spa the value for pgmr.vist_var1.dsvistv1_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistv1_spa(String dsvistv1_spa) {
        this.dsvistv1_spa = dsvistv1_spa == null ? null : dsvistv1_spa.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.fg_agg
     *
     * @return the value of pgmr.vist_var1.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getFg_agg() {
        return fg_agg;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.fg_agg
     *
     * @param fg_agg the value for pgmr.vist_var1.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setFg_agg(String fg_agg) {
        this.fg_agg = fg_agg == null ? null : fg_agg.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsextvistv1
     *
     * @return the value of pgmr.vist_var1.dsextvistv1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistv1() {
        return dsextvistv1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsextvistv1
     *
     * @param dsextvistv1 the value for pgmr.vist_var1.dsextvistv1
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistv1(String dsextvistv1) {
        this.dsextvistv1 = dsextvistv1 == null ? null : dsextvistv1.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsextvistv1_eng
     *
     * @return the value of pgmr.vist_var1.dsextvistv1_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistv1_eng() {
        return dsextvistv1_eng;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsextvistv1_eng
     *
     * @param dsextvistv1_eng the value for pgmr.vist_var1.dsextvistv1_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistv1_eng(String dsextvistv1_eng) {
        this.dsextvistv1_eng = dsextvistv1_eng == null ? null : dsextvistv1_eng.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsextvistv1_ted
     *
     * @return the value of pgmr.vist_var1.dsextvistv1_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistv1_ted() {
        return dsextvistv1_ted;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsextvistv1_ted
     *
     * @param dsextvistv1_ted the value for pgmr.vist_var1.dsextvistv1_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistv1_ted(String dsextvistv1_ted) {
        this.dsextvistv1_ted = dsextvistv1_ted == null ? null : dsextvistv1_ted.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsextvistv1_fra
     *
     * @return the value of pgmr.vist_var1.dsextvistv1_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistv1_fra() {
        return dsextvistv1_fra;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsextvistv1_fra
     *
     * @param dsextvistv1_fra the value for pgmr.vist_var1.dsextvistv1_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistv1_fra(String dsextvistv1_fra) {
        this.dsextvistv1_fra = dsextvistv1_fra == null ? null : dsextvistv1_fra.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsextvistv1_spa
     *
     * @return the value of pgmr.vist_var1.dsextvistv1_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistv1_spa() {
        return dsextvistv1_spa;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsextvistv1_spa
     *
     * @param dsextvistv1_spa the value for pgmr.vist_var1.dsextvistv1_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistv1_spa(String dsextvistv1_spa) {
        this.dsextvistv1_spa = dsextvistv1_spa == null ? null : dsextvistv1_spa.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsextvistv1_rus
     *
     * @return the value of pgmr.vist_var1.dsextvistv1_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvistv1_rus() {
        return StringUtils.isNotBlank(dsextvistv1_rus) ? dsextvistv1_rus : getDsextvistv1_eng();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsextvistv1_rus
     *
     * @param dsextvistv1_rus the value for pgmr.vist_var1.dsextvistv1_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvistv1_rus(String dsextvistv1_rus) {
        this.dsextvistv1_rus = dsextvistv1_rus == null ? null : dsextvistv1_rus.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_var1.dsvistv1_rus
     *
     * @return the value of pgmr.vist_var1.dsvistv1_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvistv1_rus() {
        if(StringUtils.isNotBlank(dsvistv1_rus)){
            return dsvistv1_rus;
        }else{
            return getDsvistv1_eng();
        }
        
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_var1.dsvistv1_rus
     *
     * @param dsvistv1_rus the value for pgmr.vist_var1.dsvistv1_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvistv1_rus(String dsvistv1_rus) {
        this.dsvistv1_rus = dsvistv1_rus == null ? null : dsvistv1_rus.trim();
    }
}