package com.ateikon.internet.eprogen.domain.pgmr;

import com.ateikon.internet.generic.domain.BaseTableBean;
import java.math.BigDecimal;

public class Vist_condc_atti extends BaseTableBean {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.cdatti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String cdatti;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.scrap1
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private BigDecimal scrap1;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.scrap2
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private BigDecimal scrap2;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.fattanno_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String fattanno_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.fattannonewc_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String fattannonewc_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.ordnewc_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String ordnewc_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.ordingr_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String ordingr_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.ordtraspfree_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String ordtraspfree_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.ordtraspfreea1_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String ordtraspfreea1_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.ordtraspfreem1_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String ordtraspfreem1_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.ordtraspfreem2_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String ordtraspfreem2_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.imptrasp
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String imptrasp;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.dspagame
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String dspagame;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.valproget_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String valproget_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.provv
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String provv;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.fido
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private BigDecimal fido;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.ord_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String ord_min;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_atti.fgabil
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private String fgabil;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.cdatti
     *
     * @return the value of pgmr.vist_condc_atti.cdatti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getCdatti() {
        return cdatti;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.cdatti
     *
     * @param cdatti the value for pgmr.vist_condc_atti.cdatti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setCdatti(String cdatti) {
        this.cdatti = cdatti == null ? null : cdatti.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.scrap1
     *
     * @return the value of pgmr.vist_condc_atti.scrap1
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public BigDecimal getScrap1() {
        return scrap1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.scrap1
     *
     * @param scrap1 the value for pgmr.vist_condc_atti.scrap1
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setScrap1(BigDecimal scrap1) {
        this.scrap1 = scrap1;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.scrap2
     *
     * @return the value of pgmr.vist_condc_atti.scrap2
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public BigDecimal getScrap2() {
        return scrap2;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.scrap2
     *
     * @param scrap2 the value for pgmr.vist_condc_atti.scrap2
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setScrap2(BigDecimal scrap2) {
        this.scrap2 = scrap2;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.fattanno_min
     *
     * @return the value of pgmr.vist_condc_atti.fattanno_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getFattanno_min() {
        return fattanno_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.fattanno_min
     *
     * @param fattanno_min the value for pgmr.vist_condc_atti.fattanno_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setFattanno_min(String fattanno_min) {
        this.fattanno_min = fattanno_min == null ? null : fattanno_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.fattannonewc_min
     *
     * @return the value of pgmr.vist_condc_atti.fattannonewc_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getFattannonewc_min() {
        return fattannonewc_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.fattannonewc_min
     *
     * @param fattannonewc_min the value for pgmr.vist_condc_atti.fattannonewc_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setFattannonewc_min(String fattannonewc_min) {
        this.fattannonewc_min = fattannonewc_min == null ? null : fattannonewc_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.ordnewc_min
     *
     * @return the value of pgmr.vist_condc_atti.ordnewc_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getOrdnewc_min() {
        return ordnewc_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.ordnewc_min
     *
     * @param ordnewc_min the value for pgmr.vist_condc_atti.ordnewc_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setOrdnewc_min(String ordnewc_min) {
        this.ordnewc_min = ordnewc_min == null ? null : ordnewc_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.ordingr_min
     *
     * @return the value of pgmr.vist_condc_atti.ordingr_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getOrdingr_min() {
        return ordingr_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.ordingr_min
     *
     * @param ordingr_min the value for pgmr.vist_condc_atti.ordingr_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setOrdingr_min(String ordingr_min) {
        this.ordingr_min = ordingr_min == null ? null : ordingr_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.ordtraspfree_min
     *
     * @return the value of pgmr.vist_condc_atti.ordtraspfree_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getOrdtraspfree_min() {
        return ordtraspfree_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.ordtraspfree_min
     *
     * @param ordtraspfree_min the value for pgmr.vist_condc_atti.ordtraspfree_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setOrdtraspfree_min(String ordtraspfree_min) {
        this.ordtraspfree_min = ordtraspfree_min == null ? null : ordtraspfree_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.ordtraspfreea1_min
     *
     * @return the value of pgmr.vist_condc_atti.ordtraspfreea1_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getOrdtraspfreea1_min() {
        return ordtraspfreea1_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.ordtraspfreea1_min
     *
     * @param ordtraspfreea1_min the value for pgmr.vist_condc_atti.ordtraspfreea1_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setOrdtraspfreea1_min(String ordtraspfreea1_min) {
        this.ordtraspfreea1_min = ordtraspfreea1_min == null ? null : ordtraspfreea1_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.ordtraspfreem1_min
     *
     * @return the value of pgmr.vist_condc_atti.ordtraspfreem1_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getOrdtraspfreem1_min() {
        return ordtraspfreem1_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.ordtraspfreem1_min
     *
     * @param ordtraspfreem1_min the value for pgmr.vist_condc_atti.ordtraspfreem1_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setOrdtraspfreem1_min(String ordtraspfreem1_min) {
        this.ordtraspfreem1_min = ordtraspfreem1_min == null ? null : ordtraspfreem1_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.ordtraspfreem2_min
     *
     * @return the value of pgmr.vist_condc_atti.ordtraspfreem2_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getOrdtraspfreem2_min() {
        return ordtraspfreem2_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.ordtraspfreem2_min
     *
     * @param ordtraspfreem2_min the value for pgmr.vist_condc_atti.ordtraspfreem2_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setOrdtraspfreem2_min(String ordtraspfreem2_min) {
        this.ordtraspfreem2_min = ordtraspfreem2_min == null ? null : ordtraspfreem2_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.imptrasp
     *
     * @return the value of pgmr.vist_condc_atti.imptrasp
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getImptrasp() {
        return imptrasp;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.imptrasp
     *
     * @param imptrasp the value for pgmr.vist_condc_atti.imptrasp
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setImptrasp(String imptrasp) {
        this.imptrasp = imptrasp == null ? null : imptrasp.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.dspagame
     *
     * @return the value of pgmr.vist_condc_atti.dspagame
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getDspagame() {
        return dspagame;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.dspagame
     *
     * @param dspagame the value for pgmr.vist_condc_atti.dspagame
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setDspagame(String dspagame) {
        this.dspagame = dspagame == null ? null : dspagame.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.valproget_min
     *
     * @return the value of pgmr.vist_condc_atti.valproget_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getValproget_min() {
        return valproget_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.valproget_min
     *
     * @param valproget_min the value for pgmr.vist_condc_atti.valproget_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setValproget_min(String valproget_min) {
        this.valproget_min = valproget_min == null ? null : valproget_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.provv
     *
     * @return the value of pgmr.vist_condc_atti.provv
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getProvv() {
        return provv;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.provv
     *
     * @param provv the value for pgmr.vist_condc_atti.provv
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setProvv(String provv) {
        this.provv = provv == null ? null : provv.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.fido
     *
     * @return the value of pgmr.vist_condc_atti.fido
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public BigDecimal getFido() {
        return fido;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.fido
     *
     * @param fido the value for pgmr.vist_condc_atti.fido
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setFido(BigDecimal fido) {
        this.fido = fido;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.ord_min
     *
     * @return the value of pgmr.vist_condc_atti.ord_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getOrd_min() {
        return ord_min;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.ord_min
     *
     * @param ord_min the value for pgmr.vist_condc_atti.ord_min
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setOrd_min(String ord_min) {
        this.ord_min = ord_min == null ? null : ord_min.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_atti.fgabil
     *
     * @return the value of pgmr.vist_condc_atti.fgabil
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public String getFgabil() {
        return fgabil;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_atti.fgabil
     *
     * @param fgabil the value for pgmr.vist_condc_atti.fgabil
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void setFgabil(String fgabil) {
        this.fgabil = fgabil == null ? null : fgabil.trim();
    }
}