package com.ateikon.internet.eprogen.domain.pgmr;

public class Vist_condc_grpatti_note extends BaseCondcNote {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.tkcondc_grpa_n
     *
     * @ibatorgenerated Mon Dec 16 10:14:20 CET 2013
     */
    private Long tkcondc_grpa_n;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_condc_grpatti_note.cdgrpatti
     *
     * @ibatorgenerated Mon Dec 16 10:14:20 CET 2013
     */
    private String cdgrpatti;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.tkcondc_grpa_n
     *
     * @return the value of pgmr.vist_condc_grpatti_note.tkcondc_grpa_n
     *
     * @ibatorgenerated Mon Dec 16 10:14:20 CET 2013
     */
    public Long getTkcondc_grpa_n() {
        return tkcondc_grpa_n;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.tkcondc_grpa_n
     *
     * @param tkcondc_grpa_n the value for pgmr.vist_condc_grpatti_note.tkcondc_grpa_n
     *
     * @ibatorgenerated Mon Dec 16 10:14:20 CET 2013
     */
    public void setTkcondc_grpa_n(Long tkcondc_grpa_n) {
        this.tkcondc_grpa_n = tkcondc_grpa_n;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_condc_grpatti_note.cdgrpatti
     *
     * @return the value of pgmr.vist_condc_grpatti_note.cdgrpatti
     *
     * @ibatorgenerated Mon Dec 16 10:14:20 CET 2013
     */
    public String getCdgrpatti() {
        return cdgrpatti;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_condc_grpatti_note.cdgrpatti
     *
     * @param cdgrpatti the value for pgmr.vist_condc_grpatti_note.cdgrpatti
     *
     * @ibatorgenerated Mon Dec 16 10:14:20 CET 2013
     */
    public void setCdgrpatti(String cdgrpatti) {
        this.cdgrpatti = cdgrpatti == null ? null : cdgrpatti.trim();
    }


}