package com.ateikon.internet.eprogen.domain.pgmr;

import org.apache.commons.lang.StringUtils;
import sun.swing.StringUIClientPropertyKey;

public class Vist_tipi extends BaseVist_tipi {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.cdvisttp
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdvisttp;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.cdvisttp_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String cdvisttp_m;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsvisttp
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvisttp;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsvisttp_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvisttp_eng;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsvisttp_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvisttp_ted;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsvisttp_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvisttp_fra;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsvisttp_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvisttp_spa;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String fg_agg;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsextvisttp
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvisttp;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsextvisttp_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvisttp_eng;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsextvisttp_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvisttp_ted;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsextvisttp_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvisttp_fra;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsextvisttp_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvisttp_spa;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.nrposi
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private Integer nrposi;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsextvisttp_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsextvisttp_rus;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column pgmr.vist_tipi.dsvisttp_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    private String dsvisttp_rus;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.cdvisttp
     *
     * @return the value of pgmr.vist_tipi.cdvisttp
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdvisttp() {
        return cdvisttp;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.cdvisttp
     *
     * @param cdvisttp the value for pgmr.vist_tipi.cdvisttp
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdvisttp(String cdvisttp) {
        this.cdvisttp = cdvisttp == null ? null : cdvisttp.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.cdvisttp_m
     *
     * @return the value of pgmr.vist_tipi.cdvisttp_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getCdvisttp_m() {
        return cdvisttp_m;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.cdvisttp_m
     *
     * @param cdvisttp_m the value for pgmr.vist_tipi.cdvisttp_m
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setCdvisttp_m(String cdvisttp_m) {
        this.cdvisttp_m = cdvisttp_m == null ? null : cdvisttp_m.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsvisttp
     *
     * @return the value of pgmr.vist_tipi.dsvisttp
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvisttp() {
        return dsvisttp;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsvisttp
     *
     * @param dsvisttp the value for pgmr.vist_tipi.dsvisttp
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvisttp(String dsvisttp) {
        this.dsvisttp = dsvisttp == null ? null : dsvisttp.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsvisttp_eng
     *
     * @return the value of pgmr.vist_tipi.dsvisttp_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvisttp_eng() {
        return dsvisttp_eng;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsvisttp_eng
     *
     * @param dsvisttp_eng the value for pgmr.vist_tipi.dsvisttp_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvisttp_eng(String dsvisttp_eng) {
        this.dsvisttp_eng = dsvisttp_eng == null ? null : dsvisttp_eng.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsvisttp_ted
     *
     * @return the value of pgmr.vist_tipi.dsvisttp_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvisttp_ted() {
        return dsvisttp_ted;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsvisttp_ted
     *
     * @param dsvisttp_ted the value for pgmr.vist_tipi.dsvisttp_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvisttp_ted(String dsvisttp_ted) {
        this.dsvisttp_ted = dsvisttp_ted == null ? null : dsvisttp_ted.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsvisttp_fra
     *
     * @return the value of pgmr.vist_tipi.dsvisttp_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvisttp_fra() {
        return dsvisttp_fra;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsvisttp_fra
     *
     * @param dsvisttp_fra the value for pgmr.vist_tipi.dsvisttp_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvisttp_fra(String dsvisttp_fra) {
        this.dsvisttp_fra = dsvisttp_fra == null ? null : dsvisttp_fra.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsvisttp_spa
     *
     * @return the value of pgmr.vist_tipi.dsvisttp_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvisttp_spa() {
        return dsvisttp_spa;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsvisttp_spa
     *
     * @param dsvisttp_spa the value for pgmr.vist_tipi.dsvisttp_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvisttp_spa(String dsvisttp_spa) {
        this.dsvisttp_spa = dsvisttp_spa == null ? null : dsvisttp_spa.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.fg_agg
     *
     * @return the value of pgmr.vist_tipi.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getFg_agg() {
        return fg_agg;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.fg_agg
     *
     * @param fg_agg the value for pgmr.vist_tipi.fg_agg
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setFg_agg(String fg_agg) {
        this.fg_agg = fg_agg == null ? null : fg_agg.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsextvisttp
     *
     * @return the value of pgmr.vist_tipi.dsextvisttp
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvisttp() {
        return dsextvisttp;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsextvisttp
     *
     * @param dsextvisttp the value for pgmr.vist_tipi.dsextvisttp
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvisttp(String dsextvisttp) {
        this.dsextvisttp = dsextvisttp == null ? null : dsextvisttp.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsextvisttp_eng
     *
     * @return the value of pgmr.vist_tipi.dsextvisttp_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvisttp_eng() {
        return dsextvisttp_eng;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsextvisttp_eng
     *
     * @param dsextvisttp_eng the value for pgmr.vist_tipi.dsextvisttp_eng
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvisttp_eng(String dsextvisttp_eng) {
        this.dsextvisttp_eng = dsextvisttp_eng == null ? null : dsextvisttp_eng.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsextvisttp_ted
     *
     * @return the value of pgmr.vist_tipi.dsextvisttp_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvisttp_ted() {
        return dsextvisttp_ted;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsextvisttp_ted
     *
     * @param dsextvisttp_ted the value for pgmr.vist_tipi.dsextvisttp_ted
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvisttp_ted(String dsextvisttp_ted) {
        this.dsextvisttp_ted = dsextvisttp_ted == null ? null : dsextvisttp_ted.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsextvisttp_fra
     *
     * @return the value of pgmr.vist_tipi.dsextvisttp_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvisttp_fra() {
        return dsextvisttp_fra;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsextvisttp_fra
     *
     * @param dsextvisttp_fra the value for pgmr.vist_tipi.dsextvisttp_fra
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvisttp_fra(String dsextvisttp_fra) {
        this.dsextvisttp_fra = dsextvisttp_fra == null ? null : dsextvisttp_fra.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsextvisttp_spa
     *
     * @return the value of pgmr.vist_tipi.dsextvisttp_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvisttp_spa() {
        return dsextvisttp_spa;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsextvisttp_spa
     *
     * @param dsextvisttp_spa the value for pgmr.vist_tipi.dsextvisttp_spa
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvisttp_spa(String dsextvisttp_spa) {
        this.dsextvisttp_spa = dsextvisttp_spa == null ? null : dsextvisttp_spa.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.nrposi
     *
     * @return the value of pgmr.vist_tipi.nrposi
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public Integer getNrposi() {
        return nrposi;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.nrposi
     *
     * @param nrposi the value for pgmr.vist_tipi.nrposi
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setNrposi(Integer nrposi) {
        this.nrposi = nrposi;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsextvisttp_rus
     *
     * @return the value of pgmr.vist_tipi.dsextvisttp_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsextvisttp_rus() {
        return StringUtils.isNotBlank(dsextvisttp_rus) ? dsextvisttp_rus : getDsextvisttp_eng();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsextvisttp_rus
     *
     * @param dsextvisttp_rus the value for pgmr.vist_tipi.dsextvisttp_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsextvisttp_rus(String dsextvisttp_rus) {
        this.dsextvisttp_rus = dsextvisttp_rus == null ? null : dsextvisttp_rus.trim();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column pgmr.vist_tipi.dsvisttp_rus
     *
     * @return the value of pgmr.vist_tipi.dsvisttp_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public String getDsvisttp_rus() {
        return StringUtils.isNotBlank(dsvisttp_rus) ? dsvisttp_rus : getDsvisttp_eng();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column pgmr.vist_tipi.dsvisttp_rus
     *
     * @param dsvisttp_rus the value for pgmr.vist_tipi.dsvisttp_rus
     *
     * @ibatorgenerated Mon Dec 16 10:33:54 CET 2013
     */
    public void setDsvisttp_rus(String dsvisttp_rus) {
        this.dsvisttp_rus = dsvisttp_rus == null ? null : dsvisttp_rus.trim();
    }
}