package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Archagen;
import com.ateikon.internet.eprogen.domain.pgmr.ArchagenExample;
import com.ateikon.internet.eprogen.domain.pgmr.ArchagenKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ArchagenDAOImpl extends SqlMapClientDaoSupport implements ArchagenDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public ArchagenDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public int countByExample(ArchagenExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_archagen.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public int deleteByExample(ArchagenExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_archagen.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public int deleteByPrimaryKey(ArchagenKey key) {
        int rows = getSqlMapClientTemplate().delete("pgmr_archagen.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public void insert(Archagen record) {
        getSqlMapClientTemplate().insert("pgmr_archagen.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public void insertSelective(Archagen record) {
        getSqlMapClientTemplate().insert("pgmr_archagen.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Archagen> selectByExample(ArchagenExample example) {
        List<Archagen> list = getSqlMapClientTemplate().queryForList("pgmr_archagen.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public Archagen selectByPrimaryKey(ArchagenKey key) {
        Archagen record = (Archagen) getSqlMapClientTemplate().queryForObject("pgmr_archagen.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public int updateByExampleSelective(Archagen record, ArchagenExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_archagen.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public int updateByExample(Archagen record, ArchagenExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_archagen.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public int updateByPrimaryKeySelective(Archagen record) {
        int rows = getSqlMapClientTemplate().update("pgmr_archagen.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    public int updateByPrimaryKey(Archagen record) {
        int rows = getSqlMapClientTemplate().update("pgmr_archagen.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    private static class UpdateByExampleParms extends ArchagenExample {
        private Object record;

        public UpdateByExampleParms(Object record, ArchagenExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}