package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Archenti;
import com.ateikon.internet.eprogen.domain.pgmr.ArchentiExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ArchentiDAOImpl extends SqlMapClientDaoSupport implements ArchentiDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public ArchentiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public int countByExample(ArchentiExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_archenti.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public int deleteByExample(ArchentiExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_archenti.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public int deleteByPrimaryKey(String cdente) {
        Archenti key = new Archenti();
        key.setCdente(cdente);
        int rows = getSqlMapClientTemplate().delete("pgmr_archenti.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public void insert(Archenti record) {
        getSqlMapClientTemplate().insert("pgmr_archenti.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public void insertSelective(Archenti record) {
        getSqlMapClientTemplate().insert("pgmr_archenti.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Archenti> selectByExample(ArchentiExample example) {
        List<Archenti> list = getSqlMapClientTemplate().queryForList("pgmr_archenti.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public Archenti selectByPrimaryKey(String cdente) {
        Archenti key = new Archenti();
        key.setCdente(cdente);
        Archenti record = (Archenti) getSqlMapClientTemplate().queryForObject("pgmr_archenti.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public int updateByExampleSelective(Archenti record, ArchentiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_archenti.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public int updateByExample(Archenti record, ArchentiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_archenti.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public int updateByPrimaryKeySelective(Archenti record) {
        int rows = getSqlMapClientTemplate().update("pgmr_archenti.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    public int updateByPrimaryKey(Archenti record) {
        int rows = getSqlMapClientTemplate().update("pgmr_archenti.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.archenti
     *
     * @ibatorgenerated Mon Jul 27 09:50:15 CEST 2009
     */
    private static class UpdateByExampleParms extends ArchentiExample {
        private Object record;

        public UpdateByExampleParms(Object record, ArchentiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}