package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Archagen;
import com.ateikon.internet.eprogen.domain.pgmr.ArchagenExample;
import com.ateikon.internet.eprogen.domain.pgmr.ArchagenKey;
import java.util.List;

public interface ArchagenDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    int countByExample(ArchagenExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    int deleteByExample(ArchagenExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    int deleteByPrimaryKey(ArchagenKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    void insert(Archagen record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    void insertSelective(Archagen record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    List<Archagen> selectByExample(ArchagenExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    Archagen selectByPrimaryKey(ArchagenKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    int updateByExampleSelective(Archagen record, ArchagenExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    int updateByExample(Archagen record, ArchagenExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    int updateByPrimaryKeySelective(Archagen record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.archagen
     *
     * @ibatorgenerated Tue Jun 22 16:11:23 CEST 2010
     */
    int updateByPrimaryKey(Archagen record);
}