package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseDao;
import com.ateikon.internet.eprogen.domain.pgmr.Articoli;
import com.ateikon.internet.eprogen.domain.pgmr.ArticoliExample;
import com.ateikon.internet.eprogen.domain.pgmr.ArticoliKey;
import java.util.List;
import java.util.Map;

public class ArticoliDAOImpl extends SqlMapBaseDao implements ArticoliDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public ArticoliDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int countByExample(ArticoliExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_articoli.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int deleteByExample(ArticoliExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_articoli.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int deleteByPrimaryKey(ArticoliKey key) {
        int rows = getSqlMapClientTemplate().delete("pgmr_articoli.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void insert(Articoli record) {
        getSqlMapClientTemplate().insert("pgmr_articoli.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void insertSelective(Articoli record) {
        getSqlMapClientTemplate().insert("pgmr_articoli.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    @SuppressWarnings("unchecked")
    public List<Articoli> selectByExample(ArticoliExample example) {
        List<Articoli> list = getSqlMapClientTemplate().queryForList("pgmr_articoli.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Articoli selectByPrimaryKey(ArticoliKey key) {
        Articoli record = (Articoli) getSqlMapClientTemplate().queryForObject("pgmr_articoli.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByExampleSelective(Articoli record, ArticoliExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_articoli.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByExample(Articoli record, ArticoliExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_articoli.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByPrimaryKeySelective(Articoli record) {
        int rows = getSqlMapClientTemplate().update("pgmr_articoli.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByPrimaryKey(Articoli record) {
        int rows = getSqlMapClientTemplate().update("pgmr_articoli.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public List<Articoli> getThumbScroller(Map pars) {
        List<Articoli> list = getSqlMapClientTemplate().queryForList("pgmr_articoli.getThumbList", pars);
        return list;
    }

    public List<Articoli> getSearchArt(Map pars) {
        List<Articoli> list = getSqlMapClientTemplate().queryForList("pgmr_articoli.searchArt", pars);
        return list;
    }




    



    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pgmr.articoli
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    private static class UpdateByExampleParms extends ArticoliExample {
        private Object record;

        public UpdateByExampleParms(Object record, ArticoliExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}