package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Articoli_abbinatiExample;
import com.ateikon.internet.eprogen.domain.pgmr.Articoli_abbinatiKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Articoli_abbinatiDAOImpl extends SqlMapClientDaoSupport implements Articoli_abbinatiDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Articoli_abbinatiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int countByExample(Articoli_abbinatiExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_articoli_abbinati.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int deleteByExample(Articoli_abbinatiExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_articoli_abbinati.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int deleteByPrimaryKey(Articoli_abbinatiKey key) {
        int rows = getSqlMapClientTemplate().delete("pgmr_articoli_abbinati.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void insert(Articoli_abbinatiKey record) {
        getSqlMapClientTemplate().insert("pgmr_articoli_abbinati.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void insertSelective(Articoli_abbinatiKey record) {
        getSqlMapClientTemplate().insert("pgmr_articoli_abbinati.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    @SuppressWarnings("unchecked")
    public List<Articoli_abbinatiKey> selectByExample(Articoli_abbinatiExample example) {
        List<Articoli_abbinatiKey> list = getSqlMapClientTemplate().queryForList("pgmr_articoli_abbinati.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByExampleSelective(Articoli_abbinatiKey record, Articoli_abbinatiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_articoli_abbinati.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByExample(Articoli_abbinatiKey record, Articoli_abbinatiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_articoli_abbinati.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pgmr.articoli_abbinati
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    private static class UpdateByExampleParms extends Articoli_abbinatiExample {
        private Object record;

        public UpdateByExampleParms(Object record, Articoli_abbinatiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}