package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Assofiscal;
import com.ateikon.internet.eprogen.domain.pgmr.AssofiscalExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class AssofiscalDAOImpl extends SqlMapClientDaoSupport implements AssofiscalDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public AssofiscalDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public int countByExample(AssofiscalExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_assofiscal.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public int deleteByExample(AssofiscalExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_assofiscal.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public int deleteByPrimaryKey(String cdfisc) {
        Assofiscal key = new Assofiscal();
        key.setCdfisc(cdfisc);
        int rows = getSqlMapClientTemplate().delete("pgmr_assofiscal.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public void insert(Assofiscal record) {
        getSqlMapClientTemplate().insert("pgmr_assofiscal.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public void insertSelective(Assofiscal record) {
        getSqlMapClientTemplate().insert("pgmr_assofiscal.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Assofiscal> selectByExample(AssofiscalExample example) {
        List<Assofiscal> list = getSqlMapClientTemplate().queryForList("pgmr_assofiscal.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public Assofiscal selectByPrimaryKey(String cdfisc) {
        Assofiscal key = new Assofiscal();
        key.setCdfisc(cdfisc);
        Assofiscal record = (Assofiscal) getSqlMapClientTemplate().queryForObject("pgmr_assofiscal.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public int updateByExampleSelective(Assofiscal record, AssofiscalExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_assofiscal.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public int updateByExample(Assofiscal record, AssofiscalExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_assofiscal.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public int updateByPrimaryKeySelective(Assofiscal record) {
        int rows = getSqlMapClientTemplate().update("pgmr_assofiscal.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    public int updateByPrimaryKey(Assofiscal record) {
        int rows = getSqlMapClientTemplate().update("pgmr_assofiscal.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.assofiscal
     *
     * @ibatorgenerated Mon Jul 27 09:43:37 CEST 2009
     */
    private static class UpdateByExampleParms extends AssofiscalExample {
        private Object record;

        public UpdateByExampleParms(Object record, AssofiscalExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}