package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseCRUDDao;
import com.ateikon.internet.eprogen.domain.pgmr.Atk_msgfile;
import com.ateikon.internet.eprogen.domain.pgmr.Atk_msgfileExample;
import com.ateikon.internet.eprogen.domain.pgmr.Atk_msgfileKey;
import java.util.Date;
import java.util.List;

public class Atk_msgfileDAOImpl extends SqlMapBaseCRUDDao implements Atk_msgfileDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public Atk_msgfileDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int countByExample(Atk_msgfileExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_atk_msgfile.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int deleteByExample(Atk_msgfileExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_atk_msgfile.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int deleteByPrimaryKey(Atk_msgfileKey key) {
        int rows = getSqlMapClientTemplate().delete("pgmr_atk_msgfile.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public void insert(Atk_msgfile record) {

        if(record.getProfil()==null){ record.setProfil(getProfil().getProfil()); }
        if(record.getCdazie()==null){ record.setCdazie(getProfil().getCdazie()); }
        if(record.getCddipa()==null){ record.setCddipa(getProfil().getCddipa()); }

        record.setDtinse(new Date());
        record.setDtulag(new Date());
        
        getSqlMapClientTemplate().insert("pgmr_atk_msgfile.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public void insertSelective(Atk_msgfile record) {
        getSqlMapClientTemplate().insert("pgmr_atk_msgfile.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Atk_msgfile> selectByExample(Atk_msgfileExample example) {
        List<Atk_msgfile> list = getSqlMapClientTemplate().queryForList("pgmr_atk_msgfile.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public Atk_msgfile selectByPrimaryKey(Atk_msgfileKey key) {
        Atk_msgfile record = (Atk_msgfile) getSqlMapClientTemplate().queryForObject("pgmr_atk_msgfile.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int updateByExampleSelective(Atk_msgfile record, Atk_msgfileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_atk_msgfile.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int updateByExample(Atk_msgfile record, Atk_msgfileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_atk_msgfile.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int updateByPrimaryKeySelective(Atk_msgfile record) {
        int rows = getSqlMapClientTemplate().update("pgmr_atk_msgfile.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int updateByPrimaryKey(Atk_msgfile record) {
        int rows = getSqlMapClientTemplate().update("pgmr_atk_msgfile.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.atk_msgfile
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    private static class UpdateByExampleParms extends Atk_msgfileExample {
        private Object record;

        public UpdateByExampleParms(Object record, Atk_msgfileExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}