package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Atk_msgdest;
import com.ateikon.internet.eprogen.domain.pgmr.Atk_msgdestExample;
import com.ateikon.internet.eprogen.domain.pgmr.Atk_msgdestKey;
import java.util.List;

public interface Atk_msgdestDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    int countByExample(Atk_msgdestExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    int deleteByExample(Atk_msgdestExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    int deleteByPrimaryKey(Atk_msgdestKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    void insert(Atk_msgdest record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    void insertSelective(Atk_msgdest record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    List<Atk_msgdest> selectByExample(Atk_msgdestExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    Atk_msgdest selectByPrimaryKey(Atk_msgdestKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    int updateByExampleSelective(Atk_msgdest record, Atk_msgdestExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    int updateByExample(Atk_msgdest record, Atk_msgdestExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    int updateByPrimaryKeySelective(Atk_msgdest record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    int updateByPrimaryKey(Atk_msgdest record);
}