package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseCRUDDao;
import com.ateikon.internet.eprogen.domain.pgmr.Atk_msgdest;
import com.ateikon.internet.eprogen.domain.pgmr.Atk_msgdestExample;
import com.ateikon.internet.eprogen.domain.pgmr.Atk_msgdestKey;
import java.util.Date;
import java.util.List;

public class Atk_msgdestDAOImpl extends SqlMapBaseCRUDDao implements Atk_msgdestDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public Atk_msgdestDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int countByExample(Atk_msgdestExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_atk_msgdest.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int deleteByExample(Atk_msgdestExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_atk_msgdest.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int deleteByPrimaryKey(Atk_msgdestKey key) {
        int rows = getSqlMapClientTemplate().delete("pgmr_atk_msgdest.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public void insert(Atk_msgdest record) {
        if(record.getProfil()==null){ record.setProfil(getProfil().getProfil()); }
        if(record.getCdazie()==null){ record.setCdazie(getProfil().getCdazie()); }
        if(record.getCddipa()==null){ record.setCddipa(getProfil().getCddipa()); }

        record.setDtinse(new Date());
        record.setDtulag(new Date());
        getSqlMapClientTemplate().insert("pgmr_atk_msgdest.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public void insertSelective(Atk_msgdest record) {
        getSqlMapClientTemplate().insert("pgmr_atk_msgdest.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Atk_msgdest> selectByExample(Atk_msgdestExample example) {
        List<Atk_msgdest> list = getSqlMapClientTemplate().queryForList("pgmr_atk_msgdest.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public Atk_msgdest selectByPrimaryKey(Atk_msgdestKey key) {
        Atk_msgdest record = (Atk_msgdest) getSqlMapClientTemplate().queryForObject("pgmr_atk_msgdest.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int updateByExampleSelective(Atk_msgdest record, Atk_msgdestExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_atk_msgdest.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int updateByExample(Atk_msgdest record, Atk_msgdestExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_atk_msgdest.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int updateByPrimaryKeySelective(Atk_msgdest record) {
        int rows = getSqlMapClientTemplate().update("pgmr_atk_msgdest.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    public int updateByPrimaryKey(Atk_msgdest record) {
        int rows = getSqlMapClientTemplate().update("pgmr_atk_msgdest.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.atk_msgdest
     *
     * @ibatorgenerated Mon May 25 15:41:28 CEST 2009
     */
    private static class UpdateByExampleParms extends Atk_msgdestExample {
        private Object record;

        public UpdateByExampleParms(Object record, Atk_msgdestExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}