package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Cliegrpatti;
import com.ateikon.internet.eprogen.domain.pgmr.CliegrpattiExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CliegrpattiDAOImpl extends SqlMapClientDaoSupport implements CliegrpattiDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public CliegrpattiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public int countByExample(CliegrpattiExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_cliegrpatti.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public int deleteByExample(CliegrpattiExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_cliegrpatti.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public int deleteByPrimaryKey(String cdgrpatti) {
        Cliegrpatti key = new Cliegrpatti();
        key.setCdgrpatti(cdgrpatti);
        int rows = getSqlMapClientTemplate().delete("pgmr_cliegrpatti.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public void insert(Cliegrpatti record) {
        getSqlMapClientTemplate().insert("pgmr_cliegrpatti.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public void insertSelective(Cliegrpatti record) {
        getSqlMapClientTemplate().insert("pgmr_cliegrpatti.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Cliegrpatti> selectByExample(CliegrpattiExample example) {
        List<Cliegrpatti> list = getSqlMapClientTemplate().queryForList("pgmr_cliegrpatti.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public Cliegrpatti selectByPrimaryKey(String cdgrpatti) {
        Cliegrpatti key = new Cliegrpatti();
        key.setCdgrpatti(cdgrpatti);
        Cliegrpatti record = (Cliegrpatti) getSqlMapClientTemplate().queryForObject("pgmr_cliegrpatti.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public int updateByExampleSelective(Cliegrpatti record, CliegrpattiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_cliegrpatti.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public int updateByExample(Cliegrpatti record, CliegrpattiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_cliegrpatti.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public int updateByPrimaryKeySelective(Cliegrpatti record) {
        int rows = getSqlMapClientTemplate().update("pgmr_cliegrpatti.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    public int updateByPrimaryKey(Cliegrpatti record) {
        int rows = getSqlMapClientTemplate().update("pgmr_cliegrpatti.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.cliegrpatti
     *
     * @ibatorgenerated Mon Jul 22 10:44:59 CEST 2013
     */
    private static class UpdateByExampleParms extends CliegrpattiExample {
        private Object record;

        public UpdateByExampleParms(Object record, CliegrpattiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}