package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Cms_promozioni_cliente;
import com.ateikon.internet.eprogen.domain.pgmr.Cms_promozioni_clienteExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Cms_promozioni_clienteDAOImpl extends SqlMapClientDaoSupport implements Cms_promozioni_clienteDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public Cms_promozioni_clienteDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public int countByExample(Cms_promozioni_clienteExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_cms_promozioni_cliente.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public int deleteByExample(Cms_promozioni_clienteExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_cms_promozioni_cliente.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public int deleteByPrimaryKey(Long tkpromo) {
        Cms_promozioni_cliente key = new Cms_promozioni_cliente();
        key.setTkpromo(tkpromo);
        int rows = getSqlMapClientTemplate().delete("pgmr_cms_promozioni_cliente.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public void insert(Cms_promozioni_cliente record) {
        getSqlMapClientTemplate().insert("pgmr_cms_promozioni_cliente.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public void insertSelective(Cms_promozioni_cliente record) {
        getSqlMapClientTemplate().insert("pgmr_cms_promozioni_cliente.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Cms_promozioni_cliente> selectByExample(Cms_promozioni_clienteExample example) {
        List<Cms_promozioni_cliente> list = getSqlMapClientTemplate().queryForList("pgmr_cms_promozioni_cliente.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public Cms_promozioni_cliente selectByPrimaryKey(Long tkpromo) {
        Cms_promozioni_cliente key = new Cms_promozioni_cliente();
        key.setTkpromo(tkpromo);
        Cms_promozioni_cliente record = (Cms_promozioni_cliente) getSqlMapClientTemplate().queryForObject("pgmr_cms_promozioni_cliente.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public int updateByExampleSelective(Cms_promozioni_cliente record, Cms_promozioni_clienteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_cms_promozioni_cliente.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public int updateByExample(Cms_promozioni_cliente record, Cms_promozioni_clienteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_cms_promozioni_cliente.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public int updateByPrimaryKeySelective(Cms_promozioni_cliente record) {
        int rows = getSqlMapClientTemplate().update("pgmr_cms_promozioni_cliente.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    public int updateByPrimaryKey(Cms_promozioni_cliente record) {
        int rows = getSqlMapClientTemplate().update("pgmr_cms_promozioni_cliente.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    private static class UpdateByExampleParms extends Cms_promozioni_clienteExample {
        private Object record;

        public UpdateByExampleParms(Object record, Cms_promozioni_clienteExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}