package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Cms_promozioni_cliente;
import com.ateikon.internet.eprogen.domain.pgmr.Cms_promozioni_clienteExample;
import java.util.List;

public interface Cms_promozioni_clienteDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    int countByExample(Cms_promozioni_clienteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    int deleteByExample(Cms_promozioni_clienteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    int deleteByPrimaryKey(Long tkpromo);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    void insert(Cms_promozioni_cliente record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    void insertSelective(Cms_promozioni_cliente record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    List<Cms_promozioni_cliente> selectByExample(Cms_promozioni_clienteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    Cms_promozioni_cliente selectByPrimaryKey(Long tkpromo);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    int updateByExampleSelective(Cms_promozioni_cliente record, Cms_promozioni_clienteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    int updateByExample(Cms_promozioni_cliente record, Cms_promozioni_clienteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    int updateByPrimaryKeySelective(Cms_promozioni_cliente record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.cms_promozioni_cliente
     *
     * @ibatorgenerated Tue Sep 29 18:12:49 CEST 2009
     */
    int updateByPrimaryKey(Cms_promozioni_cliente record);
}