package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Componenti_commerciali;
import com.ateikon.internet.eprogen.domain.pgmr.Componenti_commercialiExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Componenti_commercialiDAOImpl extends SqlMapClientDaoSupport implements Componenti_commercialiDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Componenti_commercialiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int countByExample(Componenti_commercialiExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_componenti_commerciali.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int deleteByExample(Componenti_commercialiExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_componenti_commerciali.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int deleteByPrimaryKey(Integer tkcomponente) {
        Componenti_commerciali key = new Componenti_commerciali();
        key.setTkcomponente(tkcomponente);
        int rows = getSqlMapClientTemplate().delete("pgmr_componenti_commerciali.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void insert(Componenti_commerciali record) {
        getSqlMapClientTemplate().insert("pgmr_componenti_commerciali.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void insertSelective(Componenti_commerciali record) {
        getSqlMapClientTemplate().insert("pgmr_componenti_commerciali.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    @SuppressWarnings("unchecked")
    public List<Componenti_commerciali> selectByExample(Componenti_commercialiExample example) {
        List<Componenti_commerciali> list = getSqlMapClientTemplate().queryForList("pgmr_componenti_commerciali.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Componenti_commerciali selectByPrimaryKey(Integer tkcomponente) {
        Componenti_commerciali key = new Componenti_commerciali();
        key.setTkcomponente(tkcomponente);
        Componenti_commerciali record = (Componenti_commerciali) getSqlMapClientTemplate().queryForObject("pgmr_componenti_commerciali.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByExampleSelective(Componenti_commerciali record, Componenti_commercialiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_componenti_commerciali.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByExample(Componenti_commerciali record, Componenti_commercialiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_componenti_commerciali.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByPrimaryKeySelective(Componenti_commerciali record) {
        int rows = getSqlMapClientTemplate().update("pgmr_componenti_commerciali.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByPrimaryKey(Componenti_commerciali record) {
        int rows = getSqlMapClientTemplate().update("pgmr_componenti_commerciali.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    private static class UpdateByExampleParms extends Componenti_commercialiExample {
        private Object record;

        public UpdateByExampleParms(Object record, Componenti_commercialiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}