package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Componenti_commerciali;
import com.ateikon.internet.eprogen.domain.pgmr.Componenti_commercialiExample;
import java.util.List;

public interface Componenti_commercialiDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int countByExample(Componenti_commercialiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int deleteByExample(Componenti_commercialiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int deleteByPrimaryKey(Integer tkcomponente);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    void insert(Componenti_commerciali record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    void insertSelective(Componenti_commerciali record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    List<Componenti_commerciali> selectByExample(Componenti_commercialiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    Componenti_commerciali selectByPrimaryKey(Integer tkcomponente);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByExampleSelective(Componenti_commerciali record, Componenti_commercialiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByExample(Componenti_commerciali record, Componenti_commercialiExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByPrimaryKeySelective(Componenti_commerciali record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.componenti_commerciali
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByPrimaryKey(Componenti_commerciali record);
}