package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseDao;
import com.ateikon.internet.eprogen.domain.pgmr.Costanti_comm;
import com.ateikon.internet.eprogen.domain.pgmr.Costanti_commExample;
import java.math.BigDecimal;
import java.util.List;

public class Costanti_commDAOImpl extends SqlMapBaseDao implements Costanti_commDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public Costanti_commDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public int countByExample(Costanti_commExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_costanti_comm.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public int deleteByExample(Costanti_commExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_costanti_comm.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public int deleteByPrimaryKey(BigDecimal tkcost) {
        Costanti_comm key = new Costanti_comm();
        key.setTkcost(tkcost);
        int rows = getSqlMapClientTemplate().delete("pgmr_costanti_comm.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public void insert(Costanti_comm record) {
        getSqlMapClientTemplate().insert("pgmr_costanti_comm.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public void insertSelective(Costanti_comm record) {
        getSqlMapClientTemplate().insert("pgmr_costanti_comm.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    @SuppressWarnings("unchecked")
    public List<Costanti_comm> selectByExample(Costanti_commExample example) {
        List<Costanti_comm> list = getSqlMapClientTemplate().queryForList("pgmr_costanti_comm.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public Costanti_comm selectByPrimaryKey(BigDecimal tkcost) {
        Costanti_comm key = new Costanti_comm();
        key.setTkcost(tkcost);
        Costanti_comm record = (Costanti_comm) getSqlMapClientTemplate().queryForObject("pgmr_costanti_comm.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public int updateByExampleSelective(Costanti_comm record, Costanti_commExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_costanti_comm.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public int updateByExample(Costanti_comm record, Costanti_commExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_costanti_comm.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public int updateByPrimaryKeySelective(Costanti_comm record) {
        int rows = getSqlMapClientTemplate().update("pgmr_costanti_comm.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    public int updateByPrimaryKey(Costanti_comm record) {
        int rows = getSqlMapClientTemplate().update("pgmr_costanti_comm.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.costanti_comm
     *
     * @ibatorgenerated Wed Dec 01 17:10:22 CET 2010
     */
    private static class UpdateByExampleParms extends Costanti_commExample {
        private Object record;

        public UpdateByExampleParms(Object record, Costanti_commExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }


    public String getCostante(String costname) {

        Costanti_commExample ex = new Costanti_commExample();
        ex.createCriteria().andCostnameEqualTo(costname);

        List<Costanti_comm> costs = selectByExample(ex);

        if(costs!=null && costs.size()==1){
            return costs.get(0).getCostvalue();
        }else{
            return null;
        }

    }

}