package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Ep_contator;
import com.ateikon.internet.eprogen.domain.pgmr.Ep_contatorExample;
import com.ateikon.internet.eprogen.domain.pgmr.Ep_contatorKey;
import java.util.List;
import org.springframework.dao.DataAccessException;

public interface Ep_contatorDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    int countByExample(Ep_contatorExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    int deleteByExample(Ep_contatorExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    int deleteByPrimaryKey(Ep_contatorKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    void insert(Ep_contator record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    void insertSelective(Ep_contator record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    List<Ep_contator> selectByExample(Ep_contatorExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    Ep_contator selectByPrimaryKey(Ep_contatorKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    int updateByExampleSelective(Ep_contator record, Ep_contatorExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    int updateByExample(Ep_contator record, Ep_contatorExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    int updateByPrimaryKeySelective(Ep_contator record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_contator
     *
     * @ibatorgenerated Mon Dec 13 18:01:25 CET 2010
     */
    int updateByPrimaryKey(Ep_contator record);

    Long getNprogr(String cdazie, String prname, String annoco) throws DataAccessException;

    
}