package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseDao;
import com.ateikon.internet.eprogen.domain.pgmr.Ep_log_tipo;
import com.ateikon.internet.eprogen.domain.pgmr.Ep_log_tipoExample;
import java.util.List;

public class Ep_log_tipoDAOImpl extends SqlMapBaseDao implements Ep_log_tipoDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Ep_log_tipoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int countByExample(Ep_log_tipoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_ep_log_tipo.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int deleteByExample(Ep_log_tipoExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_ep_log_tipo.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int deleteByPrimaryKey(Long tkeplog_tipo) {
        Ep_log_tipo key = new Ep_log_tipo();
        key.setTkeplog_tipo(tkeplog_tipo);
        int rows = getSqlMapClientTemplate().delete("pgmr_ep_log_tipo.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void insert(Ep_log_tipo record) {
        getSqlMapClientTemplate().insert("pgmr_ep_log_tipo.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void insertSelective(Ep_log_tipo record) {
        getSqlMapClientTemplate().insert("pgmr_ep_log_tipo.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    @SuppressWarnings("unchecked")
    public List<Ep_log_tipo> selectByExample(Ep_log_tipoExample example) {
        List<Ep_log_tipo> list = getSqlMapClientTemplate().queryForList("pgmr_ep_log_tipo.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Ep_log_tipo selectByPrimaryKey(Long tkeplog_tipo) {
        Ep_log_tipo key = new Ep_log_tipo();
        key.setTkeplog_tipo(tkeplog_tipo);
        Ep_log_tipo record = (Ep_log_tipo) getSqlMapClientTemplate().queryForObject("pgmr_ep_log_tipo.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int updateByExampleSelective(Ep_log_tipo record, Ep_log_tipoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_ep_log_tipo.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int updateByExample(Ep_log_tipo record, Ep_log_tipoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_ep_log_tipo.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int updateByPrimaryKeySelective(Ep_log_tipo record) {
        int rows = getSqlMapClientTemplate().update("pgmr_ep_log_tipo.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int updateByPrimaryKey(Ep_log_tipo record) {
        int rows = getSqlMapClientTemplate().update("pgmr_ep_log_tipo.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.ep_log_tipo
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private static class UpdateByExampleParms extends Ep_log_tipoExample {
        private Object record;

        public UpdateByExampleParms(Object record, Ep_log_tipoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}