package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseCRUDDao;
import com.ateikon.internet.eprogen.domain.pgmr.Ep_log;
import com.ateikon.internet.eprogen.domain.pgmr.Ep_logExample;
import java.util.Date;
import java.util.List;

public class Ep_logDAOImpl extends SqlMapBaseCRUDDao implements Ep_logDAO {


    private Ep_contatorDAO ep_contatorDAO;

    public Ep_contatorDAO getEp_contatorDAO() {
        return ep_contatorDAO;
    }

    public void setEp_contatorDAO(Ep_contatorDAO ep_contatorDAO) {
        this.ep_contatorDAO = ep_contatorDAO;
    }

    

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Ep_logDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int countByExample(Ep_logExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_ep_log.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int deleteByExample(Ep_logExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_ep_log.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int deleteByPrimaryKey(Long tkeplog) {
        Ep_log key = new Ep_log();
        key.setTkeplog(tkeplog);
        int rows = getSqlMapClientTemplate().delete("pgmr_ep_log.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void insert(Ep_log record) {

        record.setTkeplog(ep_contatorDAO.getNprogr("00", "EPLOG", "AAAA"));

        if(record.getProfil()==null){ record.setProfil(getProfil().getProfil()); }
        if(record.getCdazie()==null){ record.setCdazie(getProfil().getCdazie()); }
        if(record.getCddipa()==null){ record.setCddipa(getProfil().getCddipa()); }

        record.setDtinse(new Date());
        record.setDtulag(new Date());

        getSqlMapClientTemplate().insert("pgmr_ep_log.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public void insertSelective(Ep_log record) {
        record.setTkeplog(ep_contatorDAO.getNprogr("00", "EPLOG", "AAAA"));

        if(record.getProfil()==null){ record.setProfil(getProfil().getProfil()); }
        if(record.getCdazie()==null){ record.setCdazie(getProfil().getCdazie()); }
        if(record.getCddipa()==null){ record.setCddipa(getProfil().getCddipa()); }

        record.setDtinse(new Date());
        record.setDtulag(new Date());

        getSqlMapClientTemplate().insert("pgmr_ep_log.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    @SuppressWarnings("unchecked")
    public List<Ep_log> selectByExample(Ep_logExample example) {
        List<Ep_log> list = getSqlMapClientTemplate().queryForList("pgmr_ep_log.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public Ep_log selectByPrimaryKey(Long tkeplog) {
        Ep_log key = new Ep_log();
        key.setTkeplog(tkeplog);
        Ep_log record = (Ep_log) getSqlMapClientTemplate().queryForObject("pgmr_ep_log.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int updateByExampleSelective(Ep_log record, Ep_logExample example) {

        record.setDtulag(new Date());

        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_ep_log.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int updateByExample(Ep_log record, Ep_logExample example) {

        record.setDtulag(new Date());

        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_ep_log.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int updateByPrimaryKeySelective(Ep_log record) {

        record.setDtulag(new Date());

        int rows = getSqlMapClientTemplate().update("pgmr_ep_log.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    public int updateByPrimaryKey(Ep_log record) {

        record.setDtulag(new Date());
        
        int rows = getSqlMapClientTemplate().update("pgmr_ep_log.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.ep_log
     *
     * @ibatorgenerated Fri Dec 10 16:57:48 CET 2010
     */
    private static class UpdateByExampleParms extends Ep_logExample {
        private Object record;

        public UpdateByExampleParms(Object record, Ep_logExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}