package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Ep_utente;
import com.ateikon.internet.eprogen.domain.pgmr.Ep_utenteExample;
import java.util.List;

public interface Ep_utenteDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    int countByExample(Ep_utenteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    int deleteByExample(Ep_utenteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    int deleteByPrimaryKey(Long tkutente);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    void insert(Ep_utente record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    void insertSelective(Ep_utente record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    List<Ep_utente> selectByExample(Ep_utenteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    Ep_utente selectByPrimaryKey(Long tkutente);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    int updateByExampleSelective(Ep_utente record, Ep_utenteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    int updateByExample(Ep_utente record, Ep_utenteExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    int updateByPrimaryKeySelective(Ep_utente record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.ep_utente
     *
     * @ibatorgenerated Fri Jul 24 11:40:04 CEST 2009
     */
    int updateByPrimaryKey(Ep_utente record);
}