package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Collezioni;
import com.ateikon.internet.eprogen.domain.pgmr.Foto_sezioni;
import com.ateikon.internet.eprogen.domain.pgmr.Foto_sezioniExample;
import com.ateikon.internet.eprogen.domain.pgmr.Foto_sezioniKey;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Foto_sezioniDAOImpl extends SqlMapClientDaoSupport implements Foto_sezioniDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Foto_sezioniDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int countByExample(Foto_sezioniExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_foto_sezioni.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int deleteByExample(Foto_sezioniExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_foto_sezioni.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int deleteByPrimaryKey(Foto_sezioniKey key) {
        int rows = getSqlMapClientTemplate().delete("pgmr_foto_sezioni.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void insert(Foto_sezioni record) {
        getSqlMapClientTemplate().insert("pgmr_foto_sezioni.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public void insertSelective(Foto_sezioni record) {
        getSqlMapClientTemplate().insert("pgmr_foto_sezioni.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    @SuppressWarnings("unchecked")
    public List<Foto_sezioni> selectByExample(Foto_sezioniExample example) {
        List<Foto_sezioni> list = getSqlMapClientTemplate().queryForList("pgmr_foto_sezioni.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public Foto_sezioni selectByPrimaryKey(Foto_sezioniKey key) {
        Foto_sezioni record = (Foto_sezioni) getSqlMapClientTemplate().queryForObject("pgmr_foto_sezioni.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByExampleSelective(Foto_sezioni record, Foto_sezioniExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_foto_sezioni.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByExample(Foto_sezioni record, Foto_sezioniExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_foto_sezioni.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByPrimaryKeySelective(Foto_sezioni record) {
        int rows = getSqlMapClientTemplate().update("pgmr_foto_sezioni.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    public int updateByPrimaryKey(Foto_sezioni record) {
        int rows = getSqlMapClientTemplate().update("pgmr_foto_sezioni.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    public List<Collezioni> getCataloghi(Map pars) {
        List<Collezioni> list = getSqlMapClientTemplate().queryForList("pgmr_foto_sezioni.getCataloghi", pars);
        return list;
    }

    public List<Foto_sezioni> getFotoSezioneCat(Map pars) {
        List<Foto_sezioni> list = getSqlMapClientTemplate().queryForList("pgmr_foto_sezioni.getFotoSezioneCat", pars);
        return list;
    }

    public List<Foto_sezioni> getFotoSezioneByCdpadre(Map pars) {
        List<Foto_sezioni> list = getSqlMapClientTemplate().queryForList("pgmr_foto_sezioni.getFotoSezioneByCdpadre", pars);
        return list;
    }



    public List<Foto_sezioni> getFotoSezione(Map pars) {
        List<Foto_sezioni> list = getSqlMapClientTemplate().queryForList("pgmr_foto_sezioni.getFotoSezione", pars);
        return list;
    }




    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pgmr.foto_sezioni
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    private static class UpdateByExampleParms extends Foto_sezioniExample {
        private Object record;

        public UpdateByExampleParms(Object record, Foto_sezioniExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}