package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseDao;
import com.ateikon.internet.eprogen.domain.pgmr.Mrp_arch_articoli_ul;
import com.ateikon.internet.eprogen.domain.pgmr.Mrp_arch_articoli_ulExample;
import java.util.List;
import java.util.Map;

public class Mrp_arch_articoli_ulDAOImpl extends SqlMapBaseDao implements Mrp_arch_articoli_ulDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public Mrp_arch_articoli_ulDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public int countByExample(Mrp_arch_articoli_ulExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_mrp_arch_articoli_ul.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public int deleteByExample(Mrp_arch_articoli_ulExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_mrp_arch_articoli_ul.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public int deleteByPrimaryKey(String cdarti) {
        Mrp_arch_articoli_ul key = new Mrp_arch_articoli_ul();
        key.setCdarti(cdarti);
        int rows = getSqlMapClientTemplate().delete("pgmr_mrp_arch_articoli_ul.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public void insert(Mrp_arch_articoli_ul record) {
        getSqlMapClientTemplate().insert("pgmr_mrp_arch_articoli_ul.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public void insertSelective(Mrp_arch_articoli_ul record) {
        getSqlMapClientTemplate().insert("pgmr_mrp_arch_articoli_ul.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    @SuppressWarnings("unchecked")
    public List<Mrp_arch_articoli_ul> selectByExample(Mrp_arch_articoli_ulExample example) {
        List<Mrp_arch_articoli_ul> list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli_ul.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public Mrp_arch_articoli_ul selectByPrimaryKey(String cdarti) {
        Mrp_arch_articoli_ul key = new Mrp_arch_articoli_ul();
        key.setCdarti(cdarti);
        Mrp_arch_articoli_ul record = (Mrp_arch_articoli_ul) getSqlMapClientTemplate().queryForObject("pgmr_mrp_arch_articoli_ul.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public int updateByExampleSelective(Mrp_arch_articoli_ul record, Mrp_arch_articoli_ulExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_mrp_arch_articoli_ul.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public int updateByExample(Mrp_arch_articoli_ul record, Mrp_arch_articoli_ulExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_mrp_arch_articoli_ul.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public int updateByPrimaryKeySelective(Mrp_arch_articoli_ul record) {
        int rows = getSqlMapClientTemplate().update("pgmr_mrp_arch_articoli_ul.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    public int updateByPrimaryKey(Mrp_arch_articoli_ul record) {
        int rows = getSqlMapClientTemplate().update("pgmr_mrp_arch_articoli_ul.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    private static class UpdateByExampleParms extends Mrp_arch_articoli_ulExample {
        private Object record;

        public UpdateByExampleParms(Object record, Mrp_arch_articoli_ulExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
    
    
    public List<Mrp_arch_articoli_ul> searchByPars(Map pars) {

        List<Mrp_arch_articoli_ul> list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli_ul.searchArticoli", pars);
        return list;

    }

    public List<Mrp_arch_articoli_ul> searchByPars(Map pars, int pageNumber, int pagesize) {

        List<Mrp_arch_articoli_ul> list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli_ul.searchArticoli", pars, (pageNumber-1)*pagesize, pagesize);
        return list;

    }    

}