package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Mrp_arch_articoli_ul;
import com.ateikon.internet.eprogen.domain.pgmr.Mrp_arch_articoli_ulExample;
import java.util.List;
import java.util.Map;

public interface Mrp_arch_articoli_ulDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    int countByExample(Mrp_arch_articoli_ulExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    int deleteByExample(Mrp_arch_articoli_ulExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    int deleteByPrimaryKey(String cdarti);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    void insert(Mrp_arch_articoli_ul record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    void insertSelective(Mrp_arch_articoli_ul record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    List<Mrp_arch_articoli_ul> selectByExample(Mrp_arch_articoli_ulExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    Mrp_arch_articoli_ul selectByPrimaryKey(String cdarti);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    int updateByExampleSelective(Mrp_arch_articoli_ul record, Mrp_arch_articoli_ulExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    int updateByExample(Mrp_arch_articoli_ul record, Mrp_arch_articoli_ulExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    int updateByPrimaryKeySelective(Mrp_arch_articoli_ul record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli_ul
     *
     * @ibatorgenerated Fri Dec 02 15:12:46 CET 2011
     */
    int updateByPrimaryKey(Mrp_arch_articoli_ul record);

    List<Mrp_arch_articoli_ul> searchByPars(Map pars);

    List<Mrp_arch_articoli_ul> searchByPars(Map pars, int pageNumber, int pagesize);
}