package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseDao;
import com.ateikon.internet.eprogen.domain.Vist_vetro;
import com.ateikon.internet.eprogen.domain.pgmr.Mrp_arch_articoli;
import com.ateikon.internet.eprogen.domain.pgmr.Mrp_arch_articoliExample;
import java.util.List;
import java.util.Map;

public class Mrp_arch_articoliDAOImpl extends SqlMapBaseDao implements Mrp_arch_articoliDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public Mrp_arch_articoliDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public int countByExample(Mrp_arch_articoliExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_mrp_arch_articoli.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public int deleteByExample(Mrp_arch_articoliExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_mrp_arch_articoli.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public int deleteByPrimaryKey(String cdarti) {
        Mrp_arch_articoli key = new Mrp_arch_articoli();
        key.setCdarti(cdarti);
        int rows = getSqlMapClientTemplate().delete("pgmr_mrp_arch_articoli.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public void insert(Mrp_arch_articoli record) {
        getSqlMapClientTemplate().insert("pgmr_mrp_arch_articoli.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public void insertSelective(Mrp_arch_articoli record) {
        getSqlMapClientTemplate().insert("pgmr_mrp_arch_articoli.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Mrp_arch_articoli> selectByExample(Mrp_arch_articoliExample example) {
        List<Mrp_arch_articoli> list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public Mrp_arch_articoli selectByPrimaryKey(String cdarti) {
        Mrp_arch_articoli key = new Mrp_arch_articoli();
        key.setCdarti(cdarti);
        Mrp_arch_articoli record = (Mrp_arch_articoli) getSqlMapClientTemplate().queryForObject("pgmr_mrp_arch_articoli.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public int updateByExampleSelective(Mrp_arch_articoli record, Mrp_arch_articoliExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_mrp_arch_articoli.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public int updateByExample(Mrp_arch_articoli record, Mrp_arch_articoliExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_mrp_arch_articoli.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public int updateByPrimaryKeySelective(Mrp_arch_articoli record) {
        int rows = getSqlMapClientTemplate().update("pgmr_mrp_arch_articoli.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    public int updateByPrimaryKey(Mrp_arch_articoli record) {
        int rows = getSqlMapClientTemplate().update("pgmr_mrp_arch_articoli.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.mrp_arch_articoli
     *
     * @ibatorgenerated Wed Jun 24 17:47:23 CEST 2009
     */
    private static class UpdateByExampleParms extends Mrp_arch_articoliExample {
        private Object record;

        public UpdateByExampleParms(Object record, Mrp_arch_articoliExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    public List selectByExample(Mrp_arch_articoliExample example, String orderByClause, int pageNumber, int pagesize) {
        if(pagesize<0)
            return getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli.ibatorgenerated_selectByExample", example);
        else{
            List list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli.ibatorgenerated_selectByExample", example, (pageNumber-1)*pagesize, pagesize);

            return list;
        }
    }

    public List<Mrp_arch_articoli> getModelli(Map pars) {
        List<Mrp_arch_articoli> list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli.getModelli", pars);
        return list;
    }

    public List<Mrp_arch_articoli> getModelliDis(Map pars) {
        List<Mrp_arch_articoli> list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli.getModelliDis", pars);
        return list;
    }

    public List<Vist_vetro> findVetro(Map pars) {
        List<Vist_vetro> list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli.getVetri", pars);
        return list;
    }

    public List<Mrp_arch_articoli> searchByPars(Map pars) {

        List<Mrp_arch_articoli> list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli.searchArticoli", pars);
        return list;

    }

    public List<Mrp_arch_articoli> searchByPars(Map pars, int pageNumber, int pagesize) {

        List<Mrp_arch_articoli> list = getSqlMapClientTemplate().queryForList("pgmr_mrp_arch_articoli.searchArticoli", pars, (pageNumber-1)*pagesize, pagesize);
        return list;

    }

    
    public int countOfferta(Map pars) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_mrp_arch_articoli.countArticoliOff", pars);
        return count;
    }
}