package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Mrp_file_giacenza;
import com.ateikon.internet.eprogen.domain.pgmr.Mrp_file_giacenzaExample;
import com.ateikon.internet.eprogen.domain.pgmr.Mrp_file_giacenzaKey;
import java.util.List;

public interface Mrp_file_giacenzaDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    int countByExample(Mrp_file_giacenzaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    int deleteByExample(Mrp_file_giacenzaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    int deleteByPrimaryKey(Mrp_file_giacenzaKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    void insert(Mrp_file_giacenza record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    void insertSelective(Mrp_file_giacenza record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    List<Mrp_file_giacenza> selectByExample(Mrp_file_giacenzaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    Mrp_file_giacenza selectByPrimaryKey(Mrp_file_giacenzaKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    int updateByExampleSelective(Mrp_file_giacenza record, Mrp_file_giacenzaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    int updateByExample(Mrp_file_giacenza record, Mrp_file_giacenzaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    int updateByPrimaryKeySelective(Mrp_file_giacenza record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.mrp_file_giacenza
     *
     * @ibatorgenerated Wed Aug 26 16:08:21 CEST 2009
     */
    int updateByPrimaryKey(Mrp_file_giacenza record);
}