package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseDao;
import com.ateikon.internet.eprogen.domain.pgmr.Nazioni;
import com.ateikon.internet.eprogen.domain.pgmr.NazioniExample;
import java.util.List;

public class NazioniDAOImpl extends SqlMapBaseDao implements NazioniDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public NazioniDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public void insert(Nazioni record) {
        getSqlMapClientTemplate().insert("PGMR_NAZIONI.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public int updateByPrimaryKey(Nazioni record) {
        int rows = getSqlMapClientTemplate().update("PGMR_NAZIONI.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public int updateByPrimaryKeySelective(Nazioni record) {
        int rows = getSqlMapClientTemplate().update("PGMR_NAZIONI.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public List selectByExample(NazioniExample example) {
        List list = getSqlMapClientTemplate().queryForList("PGMR_NAZIONI.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public Nazioni selectByPrimaryKey(String cdnazi) {
        Nazioni key = new Nazioni();
        key.setCdnazi(cdnazi);
        Nazioni record = (Nazioni) getSqlMapClientTemplate().queryForObject("PGMR_NAZIONI.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public int deleteByExample(NazioniExample example) {
        int rows = getSqlMapClientTemplate().delete("PGMR_NAZIONI.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public int deleteByPrimaryKey(String cdnazi) {
        Nazioni key = new Nazioni();
        key.setCdnazi(cdnazi);
        int rows = getSqlMapClientTemplate().delete("PGMR_NAZIONI.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public int countByExample(NazioniExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("PGMR_NAZIONI.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public int updateByExampleSelective(Nazioni record, NazioniExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PGMR_NAZIONI.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    public int updateByExample(Nazioni record, NazioniExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PGMR_NAZIONI.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table PGMR.NAZIONI
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    private static class UpdateByExampleParms extends NazioniExample {
        private Object record;

        public UpdateByExampleParms(Object record, NazioniExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}