package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Province;
import com.ateikon.internet.eprogen.domain.pgmr.ProvinceExample;
import java.util.List;

public interface ProvinceDAO {
    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    void insert(Province record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    int updateByPrimaryKey(Province record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    List selectByExample(ProvinceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    Province selectByPrimaryKey(String cdprov);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    int deleteByExample(ProvinceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    int deleteByPrimaryKey(String cdprov);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    int countByExample(ProvinceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    int updateByExampleSelective(Province record, ProvinceExample example);

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.PROVINCE
     *
     * @abatorgenerated Thu Nov 13 18:29:58 CET 2008
     */
    int updateByExample(Province record, ProvinceExample example);
}