package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseDao;
import com.ateikon.internet.eprogen.domain.pgmr.Radiali_comuni;
import com.ateikon.internet.eprogen.domain.pgmr.Radiali_comuniExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Radiali_comuniDAOImpl extends SqlMapBaseDao implements Radiali_comuniDAO {

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public Radiali_comuniDAOImpl() {
        super();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public void insert(Radiali_comuni record) {
        getSqlMapClientTemplate().insert("PGMR_RADIALI_COMUNI.abatorgenerated_insert", record);
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public int updateByPrimaryKey(Radiali_comuni record) {
        int rows = getSqlMapClientTemplate().update("PGMR_RADIALI_COMUNI.abatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public int updateByPrimaryKeySelective(Radiali_comuni record) {
        int rows = getSqlMapClientTemplate().update("PGMR_RADIALI_COMUNI.abatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public List selectByExample(Radiali_comuniExample example) {
        List list = getSqlMapClientTemplate().queryForList("PGMR_RADIALI_COMUNI.abatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public Radiali_comuni selectByPrimaryKey(String cdradcom) {
        Radiali_comuni key = new Radiali_comuni();
        key.setCdradcom(cdradcom);
        Radiali_comuni record = (Radiali_comuni) getSqlMapClientTemplate().queryForObject("PGMR_RADIALI_COMUNI.abatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public int deleteByExample(Radiali_comuniExample example) {
        int rows = getSqlMapClientTemplate().delete("PGMR_RADIALI_COMUNI.abatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public int deleteByPrimaryKey(String cdradcom) {
        Radiali_comuni key = new Radiali_comuni();
        key.setCdradcom(cdradcom);
        int rows = getSqlMapClientTemplate().delete("PGMR_RADIALI_COMUNI.abatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public int countByExample(Radiali_comuniExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("PGMR_RADIALI_COMUNI.abatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public int updateByExampleSelective(Radiali_comuni record, Radiali_comuniExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PGMR_RADIALI_COMUNI.abatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    public int updateByExample(Radiali_comuni record, Radiali_comuniExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("PGMR_RADIALI_COMUNI.abatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Abator for iBATIS.
     * This class corresponds to the database table PGMR.RADIALI_COMUNI
     *
     * @abatorgenerated Wed Nov 26 12:23:24 CET 2008
     */
    private static class UpdateByExampleParms extends Radiali_comuniExample {
        private Object record;

        public UpdateByExampleParms(Object record, Radiali_comuniExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}