package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Sottogruppo_tipologia;
import com.ateikon.internet.eprogen.domain.pgmr.Sottogruppo_tipologiaExample;
import com.ateikon.internet.eprogen.domain.pgmr.Sottogruppo_tipologiaKey;
import java.util.List;

public interface Sottogruppo_tipologiaDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int countByExample(Sottogruppo_tipologiaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int deleteByExample(Sottogruppo_tipologiaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int deleteByPrimaryKey(Sottogruppo_tipologiaKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    void insert(Sottogruppo_tipologia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    void insertSelective(Sottogruppo_tipologia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    List<Sottogruppo_tipologia> selectByExample(Sottogruppo_tipologiaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    Sottogruppo_tipologia selectByPrimaryKey(Sottogruppo_tipologiaKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByExampleSelective(Sottogruppo_tipologia record, Sottogruppo_tipologiaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByExample(Sottogruppo_tipologia record, Sottogruppo_tipologiaExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByPrimaryKeySelective(Sottogruppo_tipologia record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.sottogruppo_tipologia
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByPrimaryKey(Sottogruppo_tipologia record);
}