package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Tipi_prodotto;
import com.ateikon.internet.eprogen.domain.pgmr.Tipi_prodottoExample;
import com.ateikon.internet.eprogen.domain.pgmr.Tipi_prodottoKey;
import java.util.List;

public interface Tipi_prodottoDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int countByExample(Tipi_prodottoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int deleteByExample(Tipi_prodottoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int deleteByPrimaryKey(Tipi_prodottoKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    void insert(Tipi_prodotto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    void insertSelective(Tipi_prodotto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    List<Tipi_prodotto> selectByExample(Tipi_prodottoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    Tipi_prodotto selectByPrimaryKey(Tipi_prodottoKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByExampleSelective(Tipi_prodotto record, Tipi_prodottoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByExample(Tipi_prodotto record, Tipi_prodottoExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByPrimaryKeySelective(Tipi_prodotto record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.tipi_prodotto
     *
     * @ibatorgenerated Mon Feb 23 19:20:39 CET 2009
     */
    int updateByPrimaryKey(Tipi_prodotto record);
}