package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Unitalocale;
import com.ateikon.internet.eprogen.domain.pgmr.Unitalocali;
import com.ateikon.internet.eprogen.domain.pgmr.UnitalocaliExample;
import java.util.List;
import java.util.Map;

public interface UnitalocaliDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:23 CET 2010
     */
    int countByExample(UnitalocaliExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:23 CET 2010
     */
    int deleteByExample(UnitalocaliExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:23 CET 2010
     */
    int deleteByPrimaryKey(String cdunil);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    void insert(Unitalocali record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    void insertSelective(Unitalocali record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    List<Unitalocali> selectByExample(UnitalocaliExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    Unitalocali selectByPrimaryKey(String cdunil);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    int updateByExampleSelective(Unitalocali record, UnitalocaliExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    int updateByExample(Unitalocali record, UnitalocaliExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    int updateByPrimaryKeySelective(Unitalocali record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    int updateByPrimaryKey(Unitalocali record);


    List<Unitalocale> searchUnitalocali(Map pars);
    Unitalocale searchUnitalocali(String cdunil);
    Unitalocale decodeUnitalocali(String cdunil);
}