package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseCRUDDao;
import com.ateikon.internet.eprogen.domain.pgmr.Unitalocale;
import com.ateikon.internet.eprogen.domain.pgmr.Unitalocali;
import com.ateikon.internet.eprogen.domain.pgmr.UnitalocaliExample;
import com.ateikon.internet.generic.domain.BaseTableBean;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.apache.commons.lang.StringUtils;

public class UnitalocaliDAOImpl extends SqlMapBaseCRUDDao implements UnitalocaliDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:23 CET 2010
     */
    public UnitalocaliDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:23 CET 2010
     */
    public int countByExample(UnitalocaliExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_unitalocali.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:23 CET 2010
     */
    public int deleteByExample(UnitalocaliExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_unitalocali.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:23 CET 2010
     */
    public int deleteByPrimaryKey(String cdunil) {
        Unitalocali key = new Unitalocali();
        key.setCdunil(cdunil);
        int rows = getSqlMapClientTemplate().delete("pgmr_unitalocali.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    public void insert(Unitalocali record) {

        if(record.getProfil()==null){ record.setProfil(getProfil().getProfil()); }
        if(record.getCdazie()==null){ record.setCdazie(getProfil().getCdazie()); }
        if(record.getCddipa()==null){ record.setCddipa(getProfil().getCddipa()); }

        record.setCdunil(StringUtils.leftPad(String.valueOf(getKeypoolsDao().getNextIdGest("UNITALOCALI", (BaseTableBean)record)), 10, "0"));
        record.setCdunil_m(record.getCdunil());

        record.setDtinse(new Date());
        record.setDtulag(new Date());


        getSqlMapClientTemplate().insert("pgmr_unitalocali.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    public void insertSelective(Unitalocali record) {

        if(record.getProfil()==null){ record.setProfil(getProfil().getProfil()); }
        if(record.getCdazie()==null){ record.setCdazie(getProfil().getCdazie()); }
        if(record.getCddipa()==null){ record.setCddipa(getProfil().getCddipa()); }

        record.setCdunil(StringUtils.leftPad(String.valueOf(getKeypoolsDao().getNextIdGest("UNITALOCALI", (BaseTableBean)record)), 10, "0"));
        record.setCdunil_m(record.getCdunil());

        record.setDtinse(new Date());
        record.setDtulag(new Date());

        getSqlMapClientTemplate().insert("pgmr_unitalocali.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    @SuppressWarnings("unchecked")
    public List<Unitalocali> selectByExample(UnitalocaliExample example) {
        List<Unitalocali> list = getSqlMapClientTemplate().queryForList("pgmr_unitalocali.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    public Unitalocali selectByPrimaryKey(String cdunil) {
        Unitalocali key = new Unitalocali();
        key.setCdunil(cdunil);
        Unitalocali record = (Unitalocali) getSqlMapClientTemplate().queryForObject("pgmr_unitalocali.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    public int updateByExampleSelective(Unitalocali record, UnitalocaliExample example) {

        record.setDtulag(new Date());

        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_unitalocali.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    public int updateByExample(Unitalocali record, UnitalocaliExample example) {

        record.setDtulag(new Date());

        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_unitalocali.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    public int updateByPrimaryKeySelective(Unitalocali record) {

        record.setDtulag(new Date());

        int rows = getSqlMapClientTemplate().update("pgmr_unitalocali.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    public int updateByPrimaryKey(Unitalocali record) {

        record.setDtulag(new Date());
        
        int rows = getSqlMapClientTemplate().update("pgmr_unitalocali.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table PGMR.UNITALOCALI
     *
     * @ibatorgenerated Mon Jan 25 14:50:25 CET 2010
     */
    private static class UpdateByExampleParms extends UnitalocaliExample {
        private Object record;

        public UpdateByExampleParms(Object record, UnitalocaliExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    public List<Unitalocale> searchUnitalocali(Map pars) {

        if(!pars.containsKey("cdazie")) pars.put("cdazie", getProfil().getCdazie());
        //pars.put("cddipa", getProfil().getCddipa());


        List list = getSqlMapClientTemplate().queryForList("pgmr_unitalocali.searchUnitalocali", pars);
        return list;
    }

    @Override
    public Unitalocale searchUnitalocali(String cdunil) {
        Map pars = new HashMap();
        pars.put("cdazie", getProfil().getCdazie());
        pars.put("cdunil", cdunil);

        Unitalocale uniloc = (Unitalocale)getSqlMapClientTemplate().queryForObject("pgmr_unitalocali.searchUnitalocali", pars);
        return  uniloc;
    }

    @Override
    public Unitalocale decodeUnitalocali(String cdunil) {
        Map pars = new HashMap();
        pars.put("cdazie", getProfil().getCdazie());
        pars.put("cdunil", cdunil);

        Unitalocale uniloc = (Unitalocale)getSqlMapClientTemplate().queryForObject("pgmr_unitalocali.decodeUnitalocali", pars);
        return  uniloc;
    }





}