package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Utente_cliente;
import com.ateikon.internet.eprogen.domain.pgmr.Utente_clienteExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Utente_clienteDAOImpl extends SqlMapClientDaoSupport implements Utente_clienteDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public Utente_clienteDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int countByExample(Utente_clienteExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_utente_cliente.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int deleteByExample(Utente_clienteExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_utente_cliente.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int deleteByPrimaryKey(Integer tk) {
        Utente_cliente key = new Utente_cliente();
        key.setTk(tk);
        int rows = getSqlMapClientTemplate().delete("pgmr_utente_cliente.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public void insert(Utente_cliente record) {
        getSqlMapClientTemplate().insert("pgmr_utente_cliente.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public void insertSelective(Utente_cliente record) {
        getSqlMapClientTemplate().insert("pgmr_utente_cliente.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    @SuppressWarnings("unchecked")
    public List<Utente_cliente> selectByExample(Utente_clienteExample example) {
        List<Utente_cliente> list = getSqlMapClientTemplate().queryForList("pgmr_utente_cliente.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public Utente_cliente selectByPrimaryKey(Integer tk) {
        Utente_cliente key = new Utente_cliente();
        key.setTk(tk);
        Utente_cliente record = (Utente_cliente) getSqlMapClientTemplate().queryForObject("pgmr_utente_cliente.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int updateByExampleSelective(Utente_cliente record, Utente_clienteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_utente_cliente.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int updateByExample(Utente_cliente record, Utente_clienteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_utente_cliente.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int updateByPrimaryKeySelective(Utente_cliente record) {
        int rows = getSqlMapClientTemplate().update("pgmr_utente_cliente.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int updateByPrimaryKey(Utente_cliente record) {
        int rows = getSqlMapClientTemplate().update("pgmr_utente_cliente.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pgmr.utente_cliente
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    private static class UpdateByExampleParms extends Utente_clienteExample {
        private Object record;

        public UpdateByExampleParms(Object record, Utente_clienteExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}