package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Valute;
import com.ateikon.internet.eprogen.domain.pgmr.ValuteExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ValuteDAOImpl extends SqlMapClientDaoSupport implements ValuteDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public ValuteDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int countByExample(ValuteExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_valute.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int deleteByExample(ValuteExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_valute.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int deleteByPrimaryKey(Integer cdvaluta) {
        Valute key = new Valute();
        key.setCdvaluta(cdvaluta);
        int rows = getSqlMapClientTemplate().delete("pgmr_valute.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public void insert(Valute record) {
        getSqlMapClientTemplate().insert("pgmr_valute.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public void insertSelective(Valute record) {
        getSqlMapClientTemplate().insert("pgmr_valute.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    @SuppressWarnings("unchecked")
    public List<Valute> selectByExample(ValuteExample example) {
        List<Valute> list = getSqlMapClientTemplate().queryForList("pgmr_valute.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public Valute selectByPrimaryKey(Integer cdvaluta) {
        Valute key = new Valute();
        key.setCdvaluta(cdvaluta);
        Valute record = (Valute) getSqlMapClientTemplate().queryForObject("pgmr_valute.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int updateByExampleSelective(Valute record, ValuteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_valute.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int updateByExample(Valute record, ValuteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_valute.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int updateByPrimaryKeySelective(Valute record) {
        int rows = getSqlMapClientTemplate().update("pgmr_valute.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    public int updateByPrimaryKey(Valute record) {
        int rows = getSqlMapClientTemplate().update("pgmr_valute.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table pgmr.valute
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    private static class UpdateByExampleParms extends ValuteExample {
        private Object record;

        public UpdateByExampleParms(Object record, ValuteExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}