package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Mrp_arch_articoli;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_famiglia;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_famigliaExample;
import java.util.List;
import java.util.Map;

public interface Vist_famigliaDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int countByExample(Vist_famigliaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int deleteByExample(Vist_famigliaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int deleteByPrimaryKey(String cdvistfam);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    void insert(Vist_famiglia record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    void insertSelective(Vist_famiglia record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    List<Vist_famiglia> selectByExample(Vist_famigliaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    Vist_famiglia selectByPrimaryKey(String cdvistfam);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int updateByExampleSelective(Vist_famiglia record, Vist_famigliaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int updateByExample(Vist_famiglia record, Vist_famigliaExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int updateByPrimaryKeySelective(Vist_famiglia record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_famiglia
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int updateByPrimaryKey(Vist_famiglia record);

    List<Vist_famiglia> find(Map pars);

    int countFind(Map pars);
    List<Vist_famiglia> find(Map pars, String orderByClause, int pageNumber, int pagesize);

    List<Mrp_arch_articoli> findColl(Map pars, String orderByClause, int pageNumber, int pagesize);
}