package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_articoli_ricambi;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_articoli_ricambiExample;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_articoli_ricambiKey;
import java.util.List;

public interface Vist_articoli_ricambiDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    int countByExample(Vist_articoli_ricambiExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    int deleteByExample(Vist_articoli_ricambiExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    int deleteByPrimaryKey(Vist_articoli_ricambiKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    void insert(Vist_articoli_ricambi record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    void insertSelective(Vist_articoli_ricambi record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    List<Vist_articoli_ricambi> selectByExample(Vist_articoli_ricambiExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    Vist_articoli_ricambi selectByPrimaryKey(Vist_articoli_ricambiKey key);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    int updateByExampleSelective(Vist_articoli_ricambi record, Vist_articoli_ricambiExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    int updateByExample(Vist_articoli_ricambi record, Vist_articoli_ricambiExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    int updateByPrimaryKeySelective(Vist_articoli_ricambi record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    int updateByPrimaryKey(Vist_articoli_ricambi record);

    int countByRic(Vist_articoli_ricambi record);
}