package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseDao;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_tipi;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_tipiExample;
import java.util.List;
import java.util.Map;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

public class Vist_tipiDAOImpl extends SqlMapBaseDao implements Vist_tipiDAO {

    private Log log = LogFactory.getLog(this.getClass());

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_tipiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int countByExample(Vist_tipiExample example) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("pgmr_vist_tipi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByExample(Vist_tipiExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_tipi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByPrimaryKey(String cdvisttp) {
        Vist_tipi key = new Vist_tipi();
        key.setCdvisttp(cdvisttp);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_tipi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insert(Vist_tipi record) {
        getSqlMapClientTemplate().insert("pgmr_vist_tipi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insertSelective(Vist_tipi record) {
        getSqlMapClientTemplate().insert("pgmr_vist_tipi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Vist_tipi> selectByExample(Vist_tipiExample example) {

        List<Vist_tipi> list = getSqlMapClientTemplate().queryForList("pgmr_vist_tipi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_tipi selectByPrimaryKey(String cdvisttp) {
        Vist_tipi key = new Vist_tipi();
        key.setCdvisttp(cdvisttp);
        Vist_tipi record = (Vist_tipi) getSqlMapClientTemplate().queryForObject("pgmr_vist_tipi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExampleSelective(Vist_tipi record, Vist_tipiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_tipi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExample(Vist_tipi record, Vist_tipiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_tipi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKeySelective(Vist_tipi record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_tipi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKey(Vist_tipi record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_tipi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_tipi
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    private static class UpdateByExampleParms extends Vist_tipiExample {

        private Object record;

        public UpdateByExampleParms(Object record, Vist_tipiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    public List<Vist_tipi> find(Map pars) {
        List<Vist_tipi> list = getSqlMapClientTemplate().queryForList("pgmr_vist_tipi.findTipi", pars);
        return list;
    }
    
    public List<Vist_tipi> getTipiAlt(Map pars) {
        List<Vist_tipi> list = getSqlMapClientTemplate().queryForList("pgmr_vist_tipi.getTipiAlt", pars);
        return list;
    }

    public int countFind(Map pars) {
        Integer count = (Integer) getSqlMapClientTemplate().queryForObject("pgmr_vist_tipi.countFindTipi", pars);
        return count;
    }

    public List<Vist_tipi> find(Map pars, String orderByClause, int pageNumber, int pagesize) {

        if (pagesize < 0) {
            return getSqlMapClientTemplate().queryForList("pgmr_vist_tipi.findTipi", pars);
        } else {
            List list = getSqlMapClientTemplate().queryForList("pgmr_vist_tipi.findTipi", pars, (pageNumber - 1) * pagesize, pagesize);

            return list;
        }
    }
}