package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_colori_vetro;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_colori_vetroExample;
import java.util.List;
import java.util.Map;

public interface Vist_colori_vetroDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int countByExample(Vist_colori_vetroExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int deleteByExample(Vist_colori_vetroExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int deleteByPrimaryKey(String cdvistcolv);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    void insert(Vist_colori_vetro record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    void insertSelective(Vist_colori_vetro record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    List<Vist_colori_vetro> selectByExample(Vist_colori_vetroExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    Vist_colori_vetro selectByPrimaryKey(String cdvistcolv);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int updateByExampleSelective(Vist_colori_vetro record, Vist_colori_vetroExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int updateByExample(Vist_colori_vetro record, Vist_colori_vetroExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int updateByPrimaryKeySelective(Vist_colori_vetro record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_colori_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    int updateByPrimaryKey(Vist_colori_vetro record);

    List<Vist_colori_vetro> find(Map pars);
}