package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_condc_grpatti_par;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_condc_grpatti_parExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Vist_condc_grpatti_parDAOImpl extends SqlMapClientDaoSupport implements Vist_condc_grpatti_parDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public Vist_condc_grpatti_parDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public int countByExample(Vist_condc_grpatti_parExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_condc_grpatti_par.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public int deleteByExample(Vist_condc_grpatti_parExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_condc_grpatti_par.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public int deleteByPrimaryKey(Long tkcondc_grpa_pa) {
        Vist_condc_grpatti_par key = new Vist_condc_grpatti_par();
        key.setTkcondc_grpa_pa(tkcondc_grpa_pa);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_condc_grpatti_par.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public void insert(Vist_condc_grpatti_par record) {
        getSqlMapClientTemplate().insert("pgmr_vist_condc_grpatti_par.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public void insertSelective(Vist_condc_grpatti_par record) {
        getSqlMapClientTemplate().insert("pgmr_vist_condc_grpatti_par.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    @SuppressWarnings("unchecked")
    public List<Vist_condc_grpatti_par> selectByExample(Vist_condc_grpatti_parExample example) {
        List<Vist_condc_grpatti_par> list = getSqlMapClientTemplate().queryForList("pgmr_vist_condc_grpatti_par.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public Vist_condc_grpatti_par selectByPrimaryKey(Long tkcondc_grpa_pa) {
        Vist_condc_grpatti_par key = new Vist_condc_grpatti_par();
        key.setTkcondc_grpa_pa(tkcondc_grpa_pa);
        Vist_condc_grpatti_par record = (Vist_condc_grpatti_par) getSqlMapClientTemplate().queryForObject("pgmr_vist_condc_grpatti_par.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public int updateByExampleSelective(Vist_condc_grpatti_par record, Vist_condc_grpatti_parExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_grpatti_par.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public int updateByExample(Vist_condc_grpatti_par record, Vist_condc_grpatti_parExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_grpatti_par.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public int updateByPrimaryKeySelective(Vist_condc_grpatti_par record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_grpatti_par.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    public int updateByPrimaryKey(Vist_condc_grpatti_par record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_grpatti_par.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_condc_grpatti_par
     *
     * @ibatorgenerated Tue Jun 24 15:49:04 CEST 2014
     */
    private static class UpdateByExampleParms extends Vist_condc_grpatti_parExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_condc_grpatti_parExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}