package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_iva;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_ivaExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Vist_ivaDAOImpl extends SqlMapClientDaoSupport implements Vist_ivaDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_ivaDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int countByExample(Vist_ivaExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_iva.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByExample(Vist_ivaExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_iva.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByPrimaryKey(String cdvistiva) {
        Vist_iva key = new Vist_iva();
        key.setCdvistiva(cdvistiva);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_iva.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insert(Vist_iva record) {
        getSqlMapClientTemplate().insert("pgmr_vist_iva.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insertSelective(Vist_iva record) {
        getSqlMapClientTemplate().insert("pgmr_vist_iva.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Vist_iva> selectByExample(Vist_ivaExample example) {
        List<Vist_iva> list = getSqlMapClientTemplate().queryForList("pgmr_vist_iva.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_iva selectByPrimaryKey(String cdvistiva) {
        Vist_iva key = new Vist_iva();
        key.setCdvistiva(cdvistiva);
        Vist_iva record = (Vist_iva) getSqlMapClientTemplate().queryForObject("pgmr_vist_iva.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExampleSelective(Vist_iva record, Vist_ivaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_iva.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExample(Vist_iva record, Vist_ivaExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_iva.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKeySelective(Vist_iva record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_iva.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKey(Vist_iva record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_iva.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_iva
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    private static class UpdateByExampleParms extends Vist_ivaExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_ivaExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}