package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_scadenziario;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_scadenziarioExample;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_scadenziarioKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Vist_scadenziarioDAOImpl extends SqlMapClientDaoSupport implements Vist_scadenziarioDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_scadenziarioDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int countByExample(Vist_scadenziarioExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_scadenziario.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByExample(Vist_scadenziarioExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_scadenziario.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByPrimaryKey(Vist_scadenziarioKey key) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_scadenziario.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insert(Vist_scadenziario record) {
        getSqlMapClientTemplate().insert("pgmr_vist_scadenziario.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insertSelective(Vist_scadenziario record) {
        getSqlMapClientTemplate().insert("pgmr_vist_scadenziario.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Vist_scadenziario> selectByExample(Vist_scadenziarioExample example) {
        List<Vist_scadenziario> list = getSqlMapClientTemplate().queryForList("pgmr_vist_scadenziario.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_scadenziario selectByPrimaryKey(Vist_scadenziarioKey key) {
        Vist_scadenziario record = (Vist_scadenziario) getSqlMapClientTemplate().queryForObject("pgmr_vist_scadenziario.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExampleSelective(Vist_scadenziario record, Vist_scadenziarioExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_scadenziario.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExample(Vist_scadenziario record, Vist_scadenziarioExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_scadenziario.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKeySelective(Vist_scadenziario record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_scadenziario.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKey(Vist_scadenziario record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_scadenziario.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_scadenziario
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    private static class UpdateByExampleParms extends Vist_scadenziarioExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_scadenziarioExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}