package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseCRUDDao;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_condc_acc_posi;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_condc_acc_posiExample;
import com.ateikon.internet.generic.domain.BaseTableBean;
import java.util.Date;
import java.util.List;

public class Vist_condc_acc_posiDAOImpl extends SqlMapBaseCRUDDao implements Vist_condc_acc_posiDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public Vist_condc_acc_posiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public int countByExample(Vist_condc_acc_posiExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_condc_acc_posi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public int deleteByExample(Vist_condc_acc_posiExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_condc_acc_posi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public int deleteByPrimaryKey(Long tkcondcaccposi) {
        Vist_condc_acc_posi key = new Vist_condc_acc_posi();
        key.setTkcondcaccposi(tkcondcaccposi);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_condc_acc_posi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public void insert(Vist_condc_acc_posi record) {
        
        record.setTkcondcaccposi(getKeypoolsDao().getNextIdGest("VIST_CONDC_ACC_POSI", (BaseTableBean)record));

        if(record.getProfil()==null){ record.setProfil(getProfil().getProfil()); }
        if(record.getCdazie()==null){ record.setCdazie(getProfil().getCdazie()); }
        if(record.getCddipa()==null){ record.setCddipa(getProfil().getCddipa()); }

        record.setDtinse(new Date());
        record.setDtulag(new Date());
        
        getSqlMapClientTemplate().insert("pgmr_vist_condc_acc_posi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public void insertSelective(Vist_condc_acc_posi record) {
        
        record.setTkcondcaccposi(getKeypoolsDao().getNextIdGest("VIST_CONDC_ACC_POSI", (BaseTableBean)record));

        if(record.getProfil()==null){ record.setProfil(getProfil().getProfil()); }
        if(record.getCdazie()==null){ record.setCdazie(getProfil().getCdazie()); }
        if(record.getCddipa()==null){ record.setCddipa(getProfil().getCddipa()); }

        record.setDtinse(new Date());
        record.setDtulag(new Date());        
        
        getSqlMapClientTemplate().insert("pgmr_vist_condc_acc_posi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    @SuppressWarnings("unchecked")
    public List<Vist_condc_acc_posi> selectByExample(Vist_condc_acc_posiExample example) {
        List<Vist_condc_acc_posi> list = getSqlMapClientTemplate().queryForList("pgmr_vist_condc_acc_posi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public Vist_condc_acc_posi selectByPrimaryKey(Long tkcondcaccposi) {
        Vist_condc_acc_posi key = new Vist_condc_acc_posi();
        key.setTkcondcaccposi(tkcondcaccposi);
        Vist_condc_acc_posi record = (Vist_condc_acc_posi) getSqlMapClientTemplate().queryForObject("pgmr_vist_condc_acc_posi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public int updateByExampleSelective(Vist_condc_acc_posi record, Vist_condc_acc_posiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        record.setDtulag(new Date());
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_acc_posi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public int updateByExample(Vist_condc_acc_posi record, Vist_condc_acc_posiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        record.setDtulag(new Date());
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_acc_posi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public int updateByPrimaryKeySelective(Vist_condc_acc_posi record) {
        record.setDtulag(new Date());
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_acc_posi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    public int updateByPrimaryKey(Vist_condc_acc_posi record) {
        record.setDtulag(new Date());
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_acc_posi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_condc_acc_posi
     *
     * @ibatorgenerated Mon Dec 30 17:30:27 CET 2013
     */
    private static class UpdateByExampleParms extends Vist_condc_acc_posiExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_condc_acc_posiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}