package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.dao.ibatis.SqlMapBaseDao;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_offerte;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_offerteExample;
import java.util.List;

public class Vist_offerteDAOImpl extends SqlMapBaseDao implements Vist_offerteDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public Vist_offerteDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public int countByExample(Vist_offerteExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_offerte.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public int deleteByExample(Vist_offerteExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_offerte.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public int deleteByPrimaryKey(Long tkvistoff) {
        Vist_offerte key = new Vist_offerte();
        key.setTkvistoff(tkvistoff);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_offerte.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public void insert(Vist_offerte record) {
        getSqlMapClientTemplate().insert("pgmr_vist_offerte.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public void insertSelective(Vist_offerte record) {
        getSqlMapClientTemplate().insert("pgmr_vist_offerte.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    @SuppressWarnings("unchecked")
    public List<Vist_offerte> selectByExample(Vist_offerteExample example) {
        List<Vist_offerte> list = getSqlMapClientTemplate().queryForList("pgmr_vist_offerte.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public Vist_offerte selectByPrimaryKey(Long tkvistoff) {
        Vist_offerte key = new Vist_offerte();
        key.setTkvistoff(tkvistoff);
        Vist_offerte record = (Vist_offerte) getSqlMapClientTemplate().queryForObject("pgmr_vist_offerte.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public int updateByExampleSelective(Vist_offerte record, Vist_offerteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_offerte.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public int updateByExample(Vist_offerte record, Vist_offerteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_offerte.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public int updateByPrimaryKeySelective(Vist_offerte record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_offerte.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    public int updateByPrimaryKey(Vist_offerte record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_offerte.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_offerte
     *
     * @ibatorgenerated Tue Mar 27 10:06:31 CEST 2012
     */
    private static class UpdateByExampleParms extends Vist_offerteExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_offerteExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}