package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_condc_atti;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_condc_attiExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Vist_condc_attiDAOImpl extends SqlMapClientDaoSupport implements Vist_condc_attiDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public Vist_condc_attiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public int countByExample(Vist_condc_attiExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_condc_atti.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public int deleteByExample(Vist_condc_attiExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_condc_atti.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public int deleteByPrimaryKey(String cdatti) {
        Vist_condc_atti key = new Vist_condc_atti();
        key.setCdatti(cdatti);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_condc_atti.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void insert(Vist_condc_atti record) {
        getSqlMapClientTemplate().insert("pgmr_vist_condc_atti.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public void insertSelective(Vist_condc_atti record) {
        getSqlMapClientTemplate().insert("pgmr_vist_condc_atti.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    @SuppressWarnings("unchecked")
    public List<Vist_condc_atti> selectByExample(Vist_condc_attiExample example) {
        List<Vist_condc_atti> list = getSqlMapClientTemplate().queryForList("pgmr_vist_condc_atti.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public Vist_condc_atti selectByPrimaryKey(String cdatti) {
        Vist_condc_atti key = new Vist_condc_atti();
        key.setCdatti(cdatti);
        Vist_condc_atti record = (Vist_condc_atti) getSqlMapClientTemplate().queryForObject("pgmr_vist_condc_atti.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public int updateByExampleSelective(Vist_condc_atti record, Vist_condc_attiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_atti.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public int updateByExample(Vist_condc_atti record, Vist_condc_attiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_atti.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public int updateByPrimaryKeySelective(Vist_condc_atti record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_atti.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    public int updateByPrimaryKey(Vist_condc_atti record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_atti.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_condc_atti
     *
     * @ibatorgenerated Wed Jun 25 15:40:53 CEST 2014
     */
    private static class UpdateByExampleParms extends Vist_condc_attiExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_condc_attiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}