package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_condc_grpatti_note;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_condc_grpatti_noteExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Vist_condc_grpatti_noteDAOImpl extends SqlMapClientDaoSupport implements Vist_condc_grpatti_noteDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public Vist_condc_grpatti_noteDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public int countByExample(Vist_condc_grpatti_noteExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_condc_grpatti_note.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public int deleteByExample(Vist_condc_grpatti_noteExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_condc_grpatti_note.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public int deleteByPrimaryKey(Long tkcondc_grpa_n) {
        Vist_condc_grpatti_note key = new Vist_condc_grpatti_note();
        key.setTkcondc_grpa_n(tkcondc_grpa_n);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_condc_grpatti_note.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void insert(Vist_condc_grpatti_note record) {
        getSqlMapClientTemplate().insert("pgmr_vist_condc_grpatti_note.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public void insertSelective(Vist_condc_grpatti_note record) {
        getSqlMapClientTemplate().insert("pgmr_vist_condc_grpatti_note.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Vist_condc_grpatti_note> selectByExample(Vist_condc_grpatti_noteExample example) {
        List<Vist_condc_grpatti_note> list = getSqlMapClientTemplate().queryForList("pgmr_vist_condc_grpatti_note.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public Vist_condc_grpatti_note selectByPrimaryKey(Long tkcondc_grpa_n) {
        Vist_condc_grpatti_note key = new Vist_condc_grpatti_note();
        key.setTkcondc_grpa_n(tkcondc_grpa_n);
        Vist_condc_grpatti_note record = (Vist_condc_grpatti_note) getSqlMapClientTemplate().queryForObject("pgmr_vist_condc_grpatti_note.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public int updateByExampleSelective(Vist_condc_grpatti_note record, Vist_condc_grpatti_noteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_grpatti_note.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public int updateByExample(Vist_condc_grpatti_note record, Vist_condc_grpatti_noteExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_grpatti_note.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public int updateByPrimaryKeySelective(Vist_condc_grpatti_note record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_grpatti_note.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    public int updateByPrimaryKey(Vist_condc_grpatti_note record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_condc_grpatti_note.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_condc_grpatti_note
     *
     * @ibatorgenerated Thu Jul 18 12:08:12 CEST 2013
     */
    private static class UpdateByExampleParms extends Vist_condc_grpatti_noteExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_condc_grpatti_noteExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}