package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_var3;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_var3Example;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Vist_var3DAOImpl extends SqlMapClientDaoSupport implements Vist_var3DAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_var3DAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int countByExample(Vist_var3Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_var3.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByExample(Vist_var3Example example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_var3.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByPrimaryKey(String cdvistv3) {
        Vist_var3 key = new Vist_var3();
        key.setCdvistv3(cdvistv3);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_var3.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insert(Vist_var3 record) {
        getSqlMapClientTemplate().insert("pgmr_vist_var3.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insertSelective(Vist_var3 record) {
        getSqlMapClientTemplate().insert("pgmr_vist_var3.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Vist_var3> selectByExample(Vist_var3Example example) {
        List<Vist_var3> list = getSqlMapClientTemplate().queryForList("pgmr_vist_var3.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_var3 selectByPrimaryKey(String cdvistv3) {
        Vist_var3 key = new Vist_var3();
        key.setCdvistv3(cdvistv3);
        Vist_var3 record = (Vist_var3) getSqlMapClientTemplate().queryForObject("pgmr_vist_var3.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExampleSelective(Vist_var3 record, Vist_var3Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_var3.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExample(Vist_var3 record, Vist_var3Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_var3.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKeySelective(Vist_var3 record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_var3.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKey(Vist_var3 record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_var3.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_var3
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    private static class UpdateByExampleParms extends Vist_var3Example {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_var3Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    public List<Vist_var3> find(Map pars) {
        List<Vist_var3> list = getSqlMapClientTemplate().queryForList("pgmr_vist_var3.findByPars", pars);
        return list;
    }
}