package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_cp_collezioni;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_cp_collezioniExample;
import java.util.List;
import java.util.Map;

public interface Vist_cp_collezioniDAO {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    int countByExample(Vist_cp_collezioniExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    int deleteByExample(Vist_cp_collezioniExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    int deleteByPrimaryKey(String cdvistccol);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    void insert(Vist_cp_collezioni record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    void insertSelective(Vist_cp_collezioni record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    List<Vist_cp_collezioni> selectByExample(Vist_cp_collezioniExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    Vist_cp_collezioni selectByPrimaryKey(String cdvistccol);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    int updateByExampleSelective(Vist_cp_collezioni record, Vist_cp_collezioniExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    int updateByExample(Vist_cp_collezioni record, Vist_cp_collezioniExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    int updateByPrimaryKeySelective(Vist_cp_collezioni record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_cp_collezioni
     *
     * @ibatorgenerated Thu Aug 27 11:16:42 CEST 2009
     */
    int updateByPrimaryKey(Vist_cp_collezioni record);

    List<Vist_cp_collezioni> find(Map pars);
}