package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_finit_vetro;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_finit_vetroExample;
import java.util.List;
import java.util.Map;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Vist_finit_vetroDAOImpl extends SqlMapClientDaoSupport implements Vist_finit_vetroDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_finit_vetroDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int countByExample(Vist_finit_vetroExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_finit_vetro.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByExample(Vist_finit_vetroExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_finit_vetro.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByPrimaryKey(String cdvistfinv) {
        Vist_finit_vetro key = new Vist_finit_vetro();
        key.setCdvistfinv(cdvistfinv);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_finit_vetro.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insert(Vist_finit_vetro record) {
        getSqlMapClientTemplate().insert("pgmr_vist_finit_vetro.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insertSelective(Vist_finit_vetro record) {
        getSqlMapClientTemplate().insert("pgmr_vist_finit_vetro.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Vist_finit_vetro> selectByExample(Vist_finit_vetroExample example) {
        List<Vist_finit_vetro> list = getSqlMapClientTemplate().queryForList("pgmr_vist_finit_vetro.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_finit_vetro selectByPrimaryKey(String cdvistfinv) {
        Vist_finit_vetro key = new Vist_finit_vetro();
        key.setCdvistfinv(cdvistfinv);
        Vist_finit_vetro record = (Vist_finit_vetro) getSqlMapClientTemplate().queryForObject("pgmr_vist_finit_vetro.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExampleSelective(Vist_finit_vetro record, Vist_finit_vetroExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_finit_vetro.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExample(Vist_finit_vetro record, Vist_finit_vetroExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_finit_vetro.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKeySelective(Vist_finit_vetro record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_finit_vetro.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKey(Vist_finit_vetro record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_finit_vetro.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_finit_vetro
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    private static class UpdateByExampleParms extends Vist_finit_vetroExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_finit_vetroExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    public List<Vist_finit_vetro> find(Map pars) {

        List<Vist_finit_vetro> list = getSqlMapClientTemplate().queryForList("pgmr_vist_finit_vetro.findByPars", pars);
        return list;

    }
}