package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_articoli_ricambi;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_articoli_ricambiExample;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_articoli_ricambiKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Vist_articoli_ricambiDAOImpl extends SqlMapClientDaoSupport implements Vist_articoli_ricambiDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public Vist_articoli_ricambiDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public int countByExample(Vist_articoli_ricambiExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_articoli_ricambi.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public int deleteByExample(Vist_articoli_ricambiExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_articoli_ricambi.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public int deleteByPrimaryKey(Vist_articoli_ricambiKey key) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_articoli_ricambi.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public void insert(Vist_articoli_ricambi record) {
        getSqlMapClientTemplate().insert("pgmr_vist_articoli_ricambi.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public void insertSelective(Vist_articoli_ricambi record) {
        getSqlMapClientTemplate().insert("pgmr_vist_articoli_ricambi.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Vist_articoli_ricambi> selectByExample(Vist_articoli_ricambiExample example) {
        List<Vist_articoli_ricambi> list = getSqlMapClientTemplate().queryForList("pgmr_vist_articoli_ricambi.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public Vist_articoli_ricambi selectByPrimaryKey(Vist_articoli_ricambiKey key) {
        Vist_articoli_ricambi record = (Vist_articoli_ricambi) getSqlMapClientTemplate().queryForObject("pgmr_vist_articoli_ricambi.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public int updateByExampleSelective(Vist_articoli_ricambi record, Vist_articoli_ricambiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_articoli_ricambi.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public int updateByExample(Vist_articoli_ricambi record, Vist_articoli_ricambiExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_articoli_ricambi.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public int updateByPrimaryKeySelective(Vist_articoli_ricambi record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_articoli_ricambi.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    public int updateByPrimaryKey(Vist_articoli_ricambi record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_articoli_ricambi.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_articoli_ricambi
     *
     * @ibatorgenerated Thu Oct 01 17:49:58 CEST 2009
     */
    private static class UpdateByExampleParms extends Vist_articoli_ricambiExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_articoli_ricambiExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

    public int countByRic(Vist_articoli_ricambi record) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_articoli_ricambi.checkRicambi", record);
        return count;
    }


}