package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.Vist_fuori_standard;
import com.ateikon.internet.eprogen.domain.pgmr.Vist_fuori_standardExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Vist_fuori_standardDAOImpl extends SqlMapClientDaoSupport implements Vist_fuori_standardDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_fuori_standardDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int countByExample(Vist_fuori_standardExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("pgmr_vist_fuori_standard.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByExample(Vist_fuori_standardExample example) {
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_fuori_standard.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int deleteByPrimaryKey(String cdvistfsstd) {
        Vist_fuori_standard key = new Vist_fuori_standard();
        key.setCdvistfsstd(cdvistfsstd);
        int rows = getSqlMapClientTemplate().delete("pgmr_vist_fuori_standard.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insert(Vist_fuori_standard record) {
        getSqlMapClientTemplate().insert("pgmr_vist_fuori_standard.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public void insertSelective(Vist_fuori_standard record) {
        getSqlMapClientTemplate().insert("pgmr_vist_fuori_standard.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    @SuppressWarnings("unchecked")
    public List<Vist_fuori_standard> selectByExample(Vist_fuori_standardExample example) {
        List<Vist_fuori_standard> list = getSqlMapClientTemplate().queryForList("pgmr_vist_fuori_standard.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public Vist_fuori_standard selectByPrimaryKey(String cdvistfsstd) {
        Vist_fuori_standard key = new Vist_fuori_standard();
        key.setCdvistfsstd(cdvistfsstd);
        Vist_fuori_standard record = (Vist_fuori_standard) getSqlMapClientTemplate().queryForObject("pgmr_vist_fuori_standard.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExampleSelective(Vist_fuori_standard record, Vist_fuori_standardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_fuori_standard.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByExample(Vist_fuori_standard record, Vist_fuori_standardExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("pgmr_vist_fuori_standard.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKeySelective(Vist_fuori_standard record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_fuori_standard.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    public int updateByPrimaryKey(Vist_fuori_standard record) {
        int rows = getSqlMapClientTemplate().update("pgmr_vist_fuori_standard.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table pgmr.vist_fuori_standard
     *
     * @ibatorgenerated Fri Jun 12 17:05:36 CEST 2009
     */
    private static class UpdateByExampleParms extends Vist_fuori_standardExample {
        private Object record;

        public UpdateByExampleParms(Object record, Vist_fuori_standardExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}