package com.ateikon.internet.eprogen.dao.pgmr;

import com.ateikon.internet.eprogen.domain.pgmr.VoceSelezioneItem;
import com.ateikon.internet.eprogen.domain.pgmr.Voce_selezione;
import com.ateikon.internet.eprogen.domain.pgmr.Voce_selezioneExample;
import com.ateikon.internet.eprogen.domain.pgmr.Voce_selezioneKey;
import java.util.List;
import java.util.Map;

public interface Voce_selezioneDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    int countByExample(Voce_selezioneExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    int deleteByExample(Voce_selezioneExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    int deleteByPrimaryKey(Voce_selezioneKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    void insert(Voce_selezione record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    void insertSelective(Voce_selezione record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    List<Voce_selezione> selectByExample(Voce_selezioneExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    Voce_selezione selectByPrimaryKey(Voce_selezioneKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    int updateByExampleSelective(Voce_selezione record, Voce_selezioneExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    int updateByExample(Voce_selezione record, Voce_selezioneExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    int updateByPrimaryKeySelective(Voce_selezione record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table pgmr.voce_selezione
     *
     * @ibatorgenerated Mon Feb 23 19:20:40 CET 2009
     */
    int updateByPrimaryKey(Voce_selezione record);

    List<VoceSelezioneItem> getVoci(Map pars);
}